### ISSUE TITLE
Refactor error handling to comform to chaise dev guideline

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1012]
I have updated the [Chaise Dev Guide wiki](https://github.com/informatics-isi-edu/chaise/wiki/Chaise-Dev-Guide) to reflect our discussion on Thur. We should try to review the code and refactor it to conform to the convention..  What about? 
- [x] record: @howdyjessie 
- [x] recordedit: @jrchudy  
- [x] recordset: @chiragsanghvi 
- [x] ermrestjs: @RFSH 
- [x] common: @howdyjessie 

How does the above breakdown sound?

**Comment by jrchudy** [comment]
That sounds good to me. 

One thing to note: 
`ermrestJS` doesn't necessary need a robust error handler that follows the convention we outlined because `http.js` acts as an interceptor for all requests in `ermrestJS`. @RFSH do you want to think about this a bit for `ermrestJS`? 

My thoughts:
That common error handling can be managed in `http.js` for generic cases if you don't need to act on the response object in the error callback for that specific API request. If the response needs to be acted on for a failure case, that code would go in the error callback and then maybe a `catchAll` will need to be defined? So maybe we should have this same convention in `ermrestJS` to have a `finally` case defined for all errors. This finally would ultimately just re-throw the error though so that `chaise` can then act on it and have it's `catchAll` raise the proper notification for the user.

**Comment by robes** [comment]
@jrchudy I'd like to hear about a specific example where such an error callback in http.js would be useful.

**Comment by robes** [comment]
@hongsudt We should look into implementing a 'decorator' for angular's `$exceptionHandler` service. Not sure if that's another bullet here to be assigned or a separate issue.

References here:
https://github.com/informatics-isi-edu/chaise/wiki/Chaise-Dev-Guide#guideline-for-angular-components

**Comment by jrchudy** [comment]
I found out today that you can open a PR for a branch, but none of the files will show up for comments unless you make a change to each file you want to comment on.

For `recordedit`, I created a branch and went to each `.js` file and added a return character. After I pushed my branch to github and opened a PR so I could comment on the individual lines in the `.js` files.

**Comment by chiragsanghvi** [comment]
@hongsudt Recordset already makes call to catchAll in all error scenarios. The only place where we need to make change is for the 401 login handling. This code is partially going to be a part of ermrestjs as we discussed. `http.js` in Ermrestjs will have a callback that will be called on `401` error. This callback will be provided by Chaise.

Do we want to make that change now ?

**Comment by jrchudy** [comment]
@chiragsanghvi, please follow the email @hongsudt sent out today and open a PR with comments in the code about where changes may or may not need to be made. We are not going to make any changes to the code until each app has been reviewed and we have discussed the those potential changes.

**Comment by jrchudy** [comment]
Error handling has been handled and updated in of the current chaise applications that use the Reference API. For viewer and search there are statements to exclude some of the global error handling for app specific reasons.
