### ISSUE TITLE
recordedit submit for cpm_file

### ISSUE THREAD

**Issue by ankit081190** [informatics-isi-edu/chaise#1028]
while using recordedit to submit data for cpm_file, it says success but shows a popup error saying no filter found and redirects to the main search page.

Despite saying success, the values are not being reflected in the database

URL: https://dev.gpcrconsortium.org/chaise/recordedit/#1/assets:cpm_file/id=111@sort(id)

**Comment by jrchudy** [comment]
This [issue](https://github.com/informatics-isi-edu/ermrest/issues/142) was submitted to ermrest detailing that the cause might be in ermrest. After some investigation, it was determined that this was happening because of row-level security and that data wasn't allowed to be changed on the corresponding table. 

If multiple rows are submitted to be updated and 1 fails, it ignores the failed rows and returns only those that succeed. When `ermrestJS` sees a 200 response for a `PUT` request and there is no data returned, this is the case. We need to catch this case and have it throw a `403 Unauthorized Exception`.

**Comment by jrchudy** [comment]
This issue has been resolved. If the user submits 1 row or multiple rows but 0 rows are updated, the user is presented with a 403 forbidden error.

If they submit multiple rows and only a subset are updated, the user is presented with 2 tables including the rows updated and the rows not updated.
