### ISSUE TITLE
external link class

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1040]
Just like we have a `.vocab` class that we can use in markdown we should have some sort of external link class that we can use so that we can differentiate our URLs that take the user away from Chaise from those links automatically generated by ermrestjs.

**Comment by hongsudt** [comment]
@robes what would be the style that you want to use for external link?

**Comment by jrchudy** [comment]
I don't think it's so much about "what the style should be" but rather, we should have a class that is attached to the element that represents a vocabulary link. Then each deployment can provide styling for those links using the `customCss` property of `chaiseConfig`.

**Comment by hongsudt** [comment]
We already have the .vocab and .download classes available as a default for
all deployments. If we want to distinguish internal vs external link, the
challenge is the default style which I can't think of a good one that is
understandable by general users without explaining.

**Comment by jrchudy** [comment]
We had a discussion about this today. This is related to changes included in issue #1823 . 

We are going to make changes in chaise so that when the `external-link` class is set, chaise will prompt the user with a dialog notifying them that they will be navigated away from the application.

For now, this class will only be set if there is no display annotation for an asset. The default display heuristic for assets will check if the asset url is from the same origin, if it is not, this class will be appended to the asset display template that is generated.

There was further discussion around showing an icon at the end of any asset OR link that is from a different origin. This icon would give a visual indicator that any link to an outside source would be just that. Some relevant icons:

| source | icon |
|--------|-----|
| wikipedia | ![image](https://user-images.githubusercontent.com/2932600/61758283-03eca800-ad79-11e9-9fff-9daa0faa2f48.png) |
| gaming wiki | ![image](https://user-images.githubusercontent.com/2932600/61758408-7f4e5980-ad79-11e9-8f3b-e48f7d70eb9c.png)|

Bootstrap icon suggestions:

|name|icon|note|
|-----|----|----|
|share|![image](https://user-images.githubusercontent.com/2932600/61758533-fd126500-ad79-11e9-8464-4643ad972e41.png)| We would then change the share icon to ![image](https://user-images.githubusercontent.com/2932600/61758572-1d422400-ad7a-11e9-88d2-0f41cdce8531.png)|
|globe|![image](https://user-images.githubusercontent.com/2932600/61758586-33e87b00-ad7a-11e9-8070-199045fae567.png)| |
|new window|![image](https://user-images.githubusercontent.com/2932600/61758611-4793e180-ad7a-11e9-935b-2052f30691af.png)| |
|link|![image](https://user-images.githubusercontent.com/2932600/61758688-9a6d9900-ad7a-11e9-8914-dafa4a014224.png)| We use the circle with an x in it for unlink ![image](https://user-images.githubusercontent.com/2932600/61758710-b3764a00-ad7a-11e9-89a4-bed862e5a800.png)|

**Comment by robes** [comment]
I think this could be useful still. IMO

I would slightly prefer the wikipedia icon or the bootstrap "new window" icon. No strong preference.

**Comment by jrchudy** [comment]
Above I mentioned:
> The default display heuristic for assets will check if the asset url is from the same origin, if it is not, `external-link` will be appended to the asset display template that is generated.

> With this class present, chaise will prompt the user with a dialog notifying them that they will be navigated away from the application.

The corresponding display:
![image](https://user-images.githubusercontent.com/2932600/61834379-9b5f0300-ae2c-11e9-89a0-bbb94f1e4195.png)


The issue with this dialog is that we don't know how the browser will interpret a download link. Some browser's will download the file right away, some will prompt the user to "save as", and some other cases the browser will try to open the content in the browser without downloading it to the Downloads folder.

**Comment by RFSH** [comment]
I am going to close this issue. For further discussion please refer to the #1851 issue.
