### ISSUE TITLE
JSON column support in chaise

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1041]
Chaise applications need to properly support JSON columns. If a JSON column is present in a table definition and part of the visible columns list, the column needs to be submitted back to ermrest as a JSON object rather than a string representation of that object. This is the case for `recordedit`.

**Comment by karlcz** [comment]
To be explicit, any single JSON value should be supported, e.g.:

- null
- true
- false
- 2.0
- "a string"
- ["an", "array"]
- {"an": "object"}

**Comment by karlcz** [comment]
This overlaps with the ancient informatics-isi-edu/ermrestjs#146

**Comment by karlcz** [comment]
Oops I guess I got confused and thought this task was further along than it is.  So maybe the new #1163 is a duplicate and should be closed?

**Comment by jrchudy** [comment]
Yes @karlcz. We have yet to merge json column support into chaise.

**Comment by nitishksahu** [comment]
I have made certain changes and have added the JSON column support in chaise, these changes are available at:
https://dev.isrd.isi.edu/~nitish/chaise/recordset/#1/public:orders

@karlcz @hongsudt @robes any suggestions?

**Comment by robes** [comment]
worked for me

**Comment by nitishksahu** [comment]
As @hongsudt suggested, 

- the conversion of JSON object to string value must be done in the ermrestjs rather than to handle it in chaise, so going forward I will be updating ermrestjs code to accommodate this change for column type "JSON", where ermrestjs will stringify JSON object and provide a string value to chaise to display. 
Ermrest right now does not provide the formatted values in the case of "edit record" and passes the raw values, for that case as well we need to add a condition for JSON column type and pass the formatted value instead of raw values.

After having some discussion on this with @jrchudy and @RFSH, 

- we understand this, that chaise(recordedit) is the only application that submits data (PUT/POST) to ermrestjs and does all the manipulation of data to appropriate type before submitting it to ermrestjs, so the JSON value from the recordedit must be parsed to JSON object before submitting it to ermrestjs.
<img width="523" alt="screen shot 2017-06-15 at 3 57 08 pm" src="https://user-images.githubusercontent.com/7412235/27205047-567e7538-51e3-11e7-85e4-a0b90875ac97.png">

**Comment by robes** [comment]
Is there some special case here?

From what I recall, every data type works this way. That is,
- ermrestjs returns data in both formatted and raw forms (hence, for JSON they should be returned in string, and js object)
- chaise submits data to ermrestjs in its raw form (again, for JSON that means a js object)

Perhaps this is being a little pedantic but I don't think there is a "JSON Object" anywhere. It is simply an "Object".

**Comment by jrchudy** [comment]
There is not a special case here. The issue is that we did not support `json` and `jsonb` before, so changes need to be made to the existing process to accommodate this. The changes that need to be made are the following:
 - `ermrestJS` needs to properly format the value for `record` and `recordedit`. 
 - `chaise` needs to properly format the value when submitting data for create or update

I don't think that's being pedantic Rob. JSON is JavaScript Object Notation. It's redundant to use both together.

**Comment by robes** [comment]
What I meant was is our new handling of JSON following a different pattern than other types like Integer or Date. Don't we always do this for other types and now JSON:

- ermrestjs returns both formatted and raw values
- chaise inputs (to ermrestjs) raw data values

Thought that was the normal flow.

**Comment by jrchudy** [comment]
It is not following a different pattern. It is going to follow the normal flow just like Integer or Date.

**Comment by RFSH** [comment]
The only difference in case if JSON is that the raw value instead of actual JSON object will be the JSON text, which chaise displays it.

**Comment by karlcz** [comment]
Just to avoid any ambiguity I want to emphasize that a 'json' or
'jsonb' column in ermrest can store any literal value that has a valid
JSON representation including:

- null
- numbers (integer and floating point)
- boolean
- string
- object with string keys and values of any type in this list
- arrays with members of any type in this list

hopefully everyone already realizes that, but I wanted to emphasize
it since a lot of comments are talking about just "objects" here.

**Comment by nitishksahu** [comment]
To explain what I see in the ermrestjs code: 

In ermrestjs, both the raw and formatted values are being computed but when the context is (**entry/edit**) in that case ermrestjs returns the **raw data** instead of formatted data, but when the case is **other** than (entry/edit) like (**detailed**) then the **formatted** value is returned to chaise. This is the reason that we observed the difference on display in the two links provided in the issue #1163 .

For datatype other than json (like integer/date) the unformatted data would have worked but if a JSON data is unformatted then we see [object Object] in the UI and that is the issue.

**Comment by nitishksahu** [comment]
JSON column support changes have been merged to master with PR#1177

**Comment by nitishksahu** [comment]
All the changes are done with PR#1177, closing the issue.
