### ISSUE TITLE
More problems with float values

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1059]
[Example record](https://synapse-dev.isrd.isi.edu/chaise/recordedit/#1/Zebrafish:Behavior/RID=17DJ)
There is a small value `1e-12 ` stored in the table.

1. When I load the editor it shows the value `0.000000000001` correctly
2. If I edit another field like the `Trial Counts` and submit, I get a validation error "please enter a decimal value"
3. If I edit the field to remove and re-add the trailing `1` digit it validates
4. The submit works (the update was made to the server)
5. But the app sometimes dies with a terminal error instead of displaying the success (this seems to be intermittent)

It seems like both error and success flags flash at the top of the screen on success.  So I suspect a race condition...

**Comment by karlcz** [comment]
Sadly I accidentally closed the tab and can't yet reproduce the error to capture the terminal error details...

**Comment by jrchudy** [comment]
This is a weird issue. If you look at this page in Chrome, you notice that the value is not automatically changed from `1e-12` to `0.000000000001`. This causes a validation error 100% of the time until the user changes the value to a float format.

If you open this in Firefox, you can see that the browser changes the value for the input field. We are not doing that in our code so what is being represented in the UI and what is being validated is out of sync.

Maybe we need to format values that appear in scientific notation as their true float value before passing that to the UI. Maybe a change in what is returned from `Tuple.values` in `ermrestJS` would be more appropriate to fix this so the UI only deals with numerical floats.

Moving this to `Blocked` until @hongsudt and @karlcz come back.

**Comment by karlcz** [comment]
I confirmed that this bug is still present.  I created a new test record illustrating it:

https://synapse-dev.isrd.isi.edu/chaise/recordedit/#1/Zebrafish:Behavior/RID=17DJ

The original example record no longer exists..

**Comment by jrchudy** [comment]
I can create records for this table but I cannot update any. Could you update the permissions for `isrd-testers`?

**Comment by jrchudy** [comment]
Moving this from blocked to backlog. @hongsudt maybe this is something we can look into adding better support for?

**Comment by RFSH** [comment]
We had a brief discussion about precision issues in recordedit:

- The precision issue is not just about the ermrestjs/chaise logic truncating the values. For `float`, ermrest might also truncate the value stored in the database. So ideally, we should have a "dirty" flag for our inputs to check if an input has been touched or not. And if it hasn't, we should avoid sending that value.

- In multi-edit/create cases, we cannot always honor the "dirty fully" flag, as we cannot selectively let ermrest know that we want to update specific columns in specific rows in all scenarios. In these scenarios, we must ensure we send the raw value that ermrest gave us with the update/create request so that at least Chaise is not truncating the values.

- While discussing this, `jsonb` columns also came up. A `jsonb` column could have float values inside it. Also, the order of keys encoded inside might change, so change detection will be buggy regardless. Not sure if we want to do something about this.

**Comment by jrchudy** [comment]
This is behaving slightly differently in the react version of recordedit. 
 - The value returned from ermrest shows as `1e-12` in the network tab for firefox AND `0.000000000001` in the network tab for chrome
 - Looking at the `response.data` object from the `get` request in ermrestJS javascript, I see `1e-12` for both browsers
 - Looking at the  `page.tuples` object from the `read` request in chaise reactJS, I still see `1e-12` for both browsers
 - If I change no data in the form, ermrestJS returns a "no data changed error" for both browsers
 - If I change a value that is NOT the float column, the row is updated in the table for both browsers
 - If I modify the scientific notation displayed in the float input, react hook form validation occurs and the input becomes invalidated

Notes:
 - ECMAscript in the browser automatically applies [ToString](https://262.ecma-international.org/5.1/#sec-9.8) which converts a `Number` _m_ to String format for certain cases (really small floats is one of them)
   -
