### ISSUE TITLE
Bring back the 'Back' button on records pages

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1109]
@crisaless commented on [Wed Jan 13 2016](https://github.com/informatics-isi-edu/facebase-project/issues/67)

Flow can get disrupted after you login to FaceBase from a records page. 

After logging in, oauth will take you back to the records page, as it should. But if you want to get back to the search results from there, the browser's Back button will try to take you back to login, which is frustrating.

**Comment by karlcz** [comment]
Please test on dev.  The latest chaise uses a pop-up for globus
login and should never introduce the globus login interstitial
that disrupts the browser history...

**Comment by hongsudt** [comment]
@robes can we close this issue?

**Comment by robes** [comment]
Is it obviated because of the model login window?

**Comment by hongsudt** [comment]
yeah.. since the back button should work as expected, and it should be a good workaround for now..

**Comment by karlcz** [comment]
I don't see a comment here but I think there are remaining issues with interstitial login through the navbar or static sites.  The new modal login mechanism needs to be integrated into all of those before we can really get it out of the browser history.

Also, I've noticed that our apps don't make history updates even when I think they should, i.e. if you go into recordset and use the next-page button to page several layers deep, hitting the browser back button will immediately exit the recordset app instead of reverting to the previous page within the same app.

**Comment by jrchudy** [comment]
A similar issue (#670) is open for `recordedit`. Both of these issues can be returned to now that the login dialog opens as a popup window so it doesn't flood the browser history. As stated in the other issue, There needs to be some discussion around what the expectation for where the back button should go.

Record can be opened from all 3 apps, "view" action column button in both recordset and record. Record is also the landing page after creating a new record and copying or updating an existing record.
