### ISSUE TITLE
Transient error, maybe related to catalog caching

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1114]
I can't reproduce this, but I got:

```
ERROR: 200
ResponseText: 304 Not Modified
Resource not modified. 
TextStatus: parsererror
ErrorThrown: SyntaxError: Unexpected token N in JSON at position 4
URL: https://staging-gudmap3.gudmap.org/ermrest/catalog/2/schema
```
when trying to visit https://staging-gudmap3.gudmap.org/ermrest/catalog/2/schema (note: this system is running a version of the software stack from April 27, tagged `rbk-20170427`).

My guess is that it's trying to interpret the "304 Not Modified" response as the text of the catalog.
I fetched the schema (https://staging-gudmap3.gudmap.org/ermrest/catalog/2/schema) with curl and ran jsonlint with strict checking on it, and it didn’t report any problems.

**Comment by karlcz** [comment]
@ljpearlman  you didn't describe what chaise app or page state you were in when this happened.

**Comment by ljpearlman** [comment]
Just got this again when selecting  https://www.rebuildingakidney.org/chaise/search/#2/Antibody:Antibody_Tests from the menu bar.

**Comment by hongsudt** [comment]
@svoinea can you investigate this issue?

**Comment by svoinea** [comment]
The `search` application is using the `jQuery.ajax` library, and in case of success, it returns the response as a `JSON` object.

The displayed message shows:
- `ermrest` has returned `304 Not Modified`
- that means the client has already the valid cached response that will be treated as `200` OK success.
- the `jQuery.ajax` library will then parse the response to a `JSON` object
- somehow, instead of the cached response, the `304 Not Modified` string was provided to the parser, which obviously is not representing a `JSON` object. Therefore, the `jQuery.ajax` library has returned the `SyntaxError` to the `search` application which displayed it.

The error is not re-creatable (at least for the links specified in the issue) and therefore I consider it to be just transient.

**Comment by hongsudt** [comment]
I am closing this issue for now as it is not reproducible. We can generate a new issue if people come across it again.
