### ISSUE TITLE
InvalidFilterOperatorError

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1118]
This seems like a bug. Given this URL the above error is produced.
```
https://synapse-dev.isrd.isi.edu/chaise/recordset/#2/Weekly:Record%20Access
```

Text of the error reads:
> Invalid filter Filter=

**Comment by RFSH** [comment]
This is the url that ermrestjs cannot parse:
```
https://synapse-dev.isrd.isi.edu/ermrest/catalog/2/entity/Weekly:Record%20Access/Application=record&Catalog=1&Code=200&Filter=&Method=GET&Status=OK&Table=Zebrafish%3AImage&When=2016-12-05T00%3A00%3A00
```
The problem is the `Filter=` part. Database value of this column is `""` (empty string) and ermrestjs cannot parse that. It seems like `column=` is a valid filter in ermrest, which parser is not supporting.

How does this url get created? This table doesn't have any visible columns annotation, so as part of heuristics, emrestjs will add key-pseudo-column (the column which is a link to the current row) to the columns. And the link to this row, is the link mentioned above. When ermrsetjs tries to create a reference with that link, it will throw an error.

**Comment by RFSH** [comment]
Issue moved to [informatics-isi-edu/ermrestjs #428](https://github.com/informatics-isi-edu/ermrestjs/issues/428) via [**ZenHub**](https://www.zenhub.com/)
