### ISSUE TITLE
Display more descriptive information on apps

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1120]
This is a debatable UX improvement which we can all discuss... but the underlying issue is real from users that seem to agree that our apps are a little difficult to understand at first.

Our apps are pretty terse. The apps display model elements and data but have little in the way of explanation or descriptive text on them. At best we use the column comments as thumbnail text. Even that is a debatable UX decision which could be open for discussion. We also have a guided tutorial but I think its only on the search app and its optional and it has to be initiated by the user who will have no idea that it exists.

A few ideas come to mind to improve on this:
- use a cookie to recognize a new user (i.e., lack of cookie) and by default walk them through a tutorial explaining the features of each app (of course, allow users to dismiss);
- in addition, the walkthrough needs to have use case specific steps (e.g., to explain the various model elements on the page like Samples or Replicates etc);
- another thought is to display model comments (table comments from postgres/ermrest) on pages below the element name. for example, under each model element display name used as a heading or subheading display a few sentences (up to the data modeler) to explain what it is;
- or if you don't want to literally use the pg comments it could be some auxiliary annotation or subresource of a model element, and that annotation could be context-able.

**Comment by carlkesselman** [comment]
Yes, we here this repeatedly.  Perhaps this also shows up in in the other issue with table of contents.

I can see from watching people use the UI, that the length of some of these pages is an issue.  People hit the record and then scroll, scroll, scroll.

Starting with things closed is a start. Remembering what people opened up previously would help, as would in idea of what the layout is (perhaps starting with more things closed at start would help, but you still loose the global state…..

Carl


----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering
Professor, Preventive Medicine, Keck School of Medicine
University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl

**Comment by karlcz** [comment]
I believe we already expose column comments as tooltips on field names in the recordedit app. At minimum, we should make this more consistent across apps?

I also vaguely remember a debate where I requested a way to make these visible w/o hovering...

**Comment by jrchudy** [comment]
Issue #380  is related to this issue. That issue is specific to `recordedit` app but covers the same idea of showing more descriptive information. 

More related work is being discussed in issue #1842 to add an annotation that provides more descriptive information just for record app related tables.

**Comment by jrchudy** [comment]
Closing this issue since it is out of date. 

As mentioned in my previous comment, there have been improvements over the last few years to show model more comments in more contexts. We've also added "inline" comments to related table sections and to recordedit pages to provide more details. 

Issue #2393 (and the corresponding PR) added the inline comments to recordedit app.

As mentioned by Carl, we have also since added the "Table of Contents" panel to record app to reduce the "scrolling" that is done. The one issue not resolved from this is adding a tutorial/walkthrough which was part of the "search" application BEFORE angularJS but was never carried over during angularJS implementation (or now during reactJS implementation)
