### ISSUE TITLE
Login onClick function in navbar uses wrong login flow

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1133]
The `onClick` function bound to the login button in navbar points to the login function that uses the old login flow (where the login form appears in the same window). This should be adjusted to use the login function that @chiragsanghvi introduced to open a new window for login.

**Comment by nitishksahu** [comment]
As discussed with @RFSH , showing a modal window when the user clicks on the `Login` link in the navbar and then asking for click on the login button on the modal window is incurring extra user clicks, which seems unnecessary. So going forward the flow needs to be adjusted like this,

- Click on `Login` link on the navbar, opens a new pop window directly to log in.

- When a user is in middle of some operation (adding/ editing record) and the session expires, in that case, a modal window will be shown, with the message of "expired session" and asked to log in again.

**Comment by nitishksahu** [comment]
The changes have been merged to master, assigning it to @jrchudy to verify.

**Comment by jrchudy** [comment]
@nitishksahu: part of why were were using the intermediate modal popup was so that when the user clicked the login button, it would open a window *without telling the user a popup was blocked*.

It looks like the modal dialog controller has this line:
`params.login_url = $sce.trustAsResourceUrl(params.login_url);`

I think that's how we allow that window to open without it being caught as a popup by the browser. Could you adjust the link for login from the navbar to do this as well. It should automatically open a window without blocking a popup.

**Comment by nitishksahu** [comment]
It seems like `params.login_url = $sce.trustAsResourceUrl(params.login_url); ` will not help in this case. The popup is blocked because of the window.open() command was being issued in the `authen.js` and was not a part of tick/stack as the user-initiated event, which is click event in this case. 

Going forward creating a window instance with blank URL on user click and passing its reference to authen.js which can set the URL to login URL later will solve this issue.

But, talking about the stale sessions cases, when the user submits the recordedit page, in that case, we will have to pass a window reference everytime irrespective of the session validity and later close the window or set the location of the window to login URL based on session availability. And the refresh operation on the stale session would also need similar line of thought.

Suggestions?? @jrchudy @RFSH

**Comment by nitishksahu** [comment]
I have made the changes and have raised a [PR#1192](https://github.com/informatics-isi-edu/chaise/pull/1192) for this.

**Comment by hongsudt** [comment]
@karlcz can you please review this issue?

**Comment by jrchudy** [comment]
When selecting the navbar login button, it properly opens a new window that proceeds through the login flow. Upon successfully logging in, the window closes and the application page refreshes with a valid session.
