### ISSUE TITLE
Please change fileupload to not add the current hostname to the URLs it generates

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1135]
When I use fileupload with a relative url_pattern (i.e., starting with "/", like '/hatrac/resources/...'), the URL that's stored in the database is an absolute URL (like "https://_hostname_/hatrac/resources/..."). Because we port databases from production systems to dev and staging systems for testing, this can potentially cause problems for us in the future.

**Comment by hongsudt** [comment]
@ljpearlman I have thought more about this.. I think it might be a desirable feature.  The file is written to a specific server.. If the hostname is not there, then unless you plan to sync hatrac db and FS, the files will not be available.  There is no ability from chaise to delete the files on hatrac. So this is probably safe.  

@karlcz @robes what do you think?

**Comment by robes** [comment]
I'm inclined to agree with Laura on this. If the DBA wants an absolute path they can specify it, and if they want a relative path Chaise should honor it. My thoughts...

**Comment by karlcz** [comment]
I also test by dumping ermrest catalogs and hatrac state from production
to dev/test servers.

We haven't in general addressed single sign-on so cross-host
references to hatrac objects won't work anyway unless they are visible
to anonymous clients.

I also like keeping the URLs "relative" to the current ermrest host
when we are managing a coherent ermrest+hatrac pair.  Using a URL w/ a
different host-authority part seems to me something we should only do
when we're explicitly managing cross-host resource references.

**Comment by jrchudy** [comment]
The corresponding changes have been merged into master.

Reassigning this issue to @ljpearlman so she can verify that the recent changes have fixed the issue.

**Comment by karlcz** [comment]
Before we close this... does the code honor whatever URL is produced by the mustache template (whether or not a hostname part is present) or does it hard-code one behavior that overrides the template?  I think it should honor the template so that the DBA can decide if they want to make hostnames explicit...

**Comment by hongsudt** [comment]
@jrchudy @RFSH can you answer @karlcz 's question?

**Comment by RFSH** [comment]
The code first check if the URL is absolute or not (by matching `^(?:[a-z]+:)?//` regular expression). If it is, it won't make any changes to the URL, otherwise it will append the server uri.

**Comment by karlcz** [comment]
This sounds like the wrong approach to me.

What we want is to store just the path component returned from Hatrac
so that there IS NOT a scheme or hostname component in the stored
column value in ermrest.

If we want to make this configurable, we need to adjust the asset 
annotation to either have a boolean flag or to define some mustache
environment and template where the DBA can decide which component(s)
to include in the stored value.

The possible components from the perspective of the hatrac upload:

   - scheme (eg. https:)
   - authority (eg. //server.example.org)
   - path (eg. /hatrac/some/namespace/)
   - object_name (eg. myobject)
   - version (eg. 5U6KBMAOFCDFVCK3TKF6GRVMOQ)

The full versioned object URL is:

  https://server.example.org/hatrac/some/namespace/myobject:5U6KBMAOFCDFVCK3TKF6GRVMOQ

but many of us would like to store:

  /hatrac/some/namespace/myobject:5U6KBMAOFCDFVCK3TKF6GRVMOQ

and this may be the right default behavior. Someone might even want to
drop the versioning suffix:

  /hatrac/some/namespace/myobject

but that SHOULD NOT be the default.

**Comment by hongsudt** [comment]
I think this is the current behavior. I am closing the issue.
