### ISSUE TITLE
"Foo" not found

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#115]
If there are zero results in a search, we should have string that says "Foo not found" as opposed to "Foo found in;"

**Comment by howdyjessie** [comment]
@carlkesselman @robes I changed the wording from "'Foo' not found" to "'Foo' found in {{numberOfSearchResults}} attribute(s):" so that the text doesn't appear too jumpy between zero and > 0 search results cases. (And also to provide a count of search results.)

<img width="373" alt="screen shot 2015-10-07 at 7 27 24 pm" src="https://cloud.githubusercontent.com/assets/4585431/10356231/bca1de4a-6d29-11e5-81e8-9d69e44ef860.png">
<img width="360" alt="screen shot 2015-10-07 at 7 27 01 pm" src="https://cloud.githubusercontent.com/assets/4585431/10356232/be1dd468-6d29-11e5-9a83-88187a564acd.png">

Yay or nay?

**Comment by robes** [comment]
that works for me

**Comment by robes** [comment]
excuse me. i meant to say "yay".

**Comment by carlkesselman** [comment]
Yea 2....,

Carl

Sent from my iPad

----------------------------------------------------------
Dr. Carl Kesselman
Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering
University of Southern California

4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl


On Oct 7, 2015, at 8:02 PM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:


excuse me. i meant to say "yay".

-

**Comment by howdyjessie** [comment]
@robes :wink: 

Ok cool the yays have it. Moved to Done.
