### ISSUE TITLE
Unlink appears to succeed without actually unlinking the related entity

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1160]
Please investigate this with @ljpearlman  We saw this issue on production on Monday when a user tries to delete a protocol ("Protocol"."Protocol"). The browser didn't complain, but the page content didn't change even after refreshed.

**Comment by jrchudy** [comment]
This issue is related to [this issue](https://github.com/informatics-isi-edu/ermrestjs/issues/398) in ermrestJS. I am seeing the same exact issue when trying to unlink an entity through the related table action.

NOTE: The following URL points to *production* data.
This can be seen at this URL:
https://www.rebuildingakidney.org/chaise/record/#2/Protocol:Protocol/ID=30
Open the Browser tools and console tab.
If click `Edit` for the _Protocol Keyword_, and then the `Unlink` button for one of the 2 keywords, you can see 412 being retried infinitely.

I was not able to reproduce this in staging and dev by following a similar pattern for data in those environments.

**Comment by RFSH** [comment]
Issue moved to [informatics-isi-edu/ermrestjs #425](https://github.com/informatics-isi-edu/ermrestjs/issues/425) via [**ZenHub**](https://www.zenhub.com/)
