### ISSUE TITLE
recordedit keeps track of fields that have been modified by user

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1173]
There might be a problem to do with this with the multi-entry edit feature.. @jrchudy will list these issues for discussion.

**Comment by jrchudy** [comment]
In the case of create:
`Chaise` submits the the full set of visible columns with their data values to `ermrestJS`. So if a column was part of the visible columns, but the field was empty, we still send a key value pair of `column-name: null`. `ErmrestJS` uses these null key/value pairs to determine what the defaults projection set should be.

In the case of edit:
`Chaise` submits the full set of data, changed and unchanged. `EmrestJS` then aliases that data and submits all of it, changed and unchanged, to the database. All visible columns are part of the projection list, rather than only those that were changed.
