### ISSUE TITLE
generate test cases for Association Entities

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1202]
We need some test cases for pure binary association in chaise. Any feature that is testing "related" entities, should test both "pure and binary association" and also "inbound related" tables.

**Comment by jrchudy** [comment]
Action columns in the related tables should be tested for both inbound foreign related tables and association tables in the `related-table-actions` spec.
Inbound related tables:
 - View should show the related entity
 - Edit should allow the editing of the related entity
 - Delete should delete the related entity
Association related tables:
 - View should show the association entity
 - Edit should allow you to edit the associated entity (it doesn't make sense to edit the association because then you are just creating a new association, verify with @hongsudt about this though)
 - Unlink should remove the association

In the `related-table-link` spec, make sure:
 - view more points to the right recordset page
 - add allows you to create a new association (basically associating a new entity with the main entity)

**Comment by nitishksahu** [comment]
Every action item for an association lets you manipulate the association table, except **View** (Eye Icon)
- Add: Will let you add a relationship between the base and related table.
- Edit: Will let you edit a relationship between the base and the related table.
- View: Will land you the record page of the related entity (Leaf table) of the association.

**Comment by nitishksahu** [comment]
The test cases have been merged with master. Closing this issue.
