### ISSUE TITLE
support an annotation to hide the "add" link on top of related table

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1229]
There can be multiple forging key constraints between the main entity and a related table. I want to be able to control the flow for creating new entries (through the use of the "add" link) in the related table.  Having "add" on all constraints is confusing. 

Take a look at the example from rbk: sample, replicate, and file tables. 

@karlcz should we add this annotation to the foreign key?

**Comment by karlcz** [comment]
@hongsudt 

So, you want to hide the "add" link from the parent page, but still allow the foreign key to be populated by the user when editing the child record?  If so, this suggests it is not as simple as extending or reusing the "immutable" or "generated" concepts...

Is the idea that you're trying to impose a normalized hierarchy, i.e. only one of the outbound foreign keys is to the "parent" and the other foreign keys are considered non-hierarchical relationships?  If so, maybe we want an annotation to designate the "parent link" status?

Are there cases where the decision of which one to hide might depend on the client's privilege level?  I.e. more privileged users might be able to add via a preferred parent link, but less privileged users might need to be offered a different add path because they aren't allowed to set the primary parent link?  If so, this would suggest a need for a ranking annotation so that the UX could expose the highest ranked link that is writable by the user, while hiding the others!  But if this is not necessary, then a simpler "parent link" annotation seems better to me...

**Comment by karlcz** [comment]
Assigning more people to discuss the desired behavior/scope before we design anything...

**Comment by robes** [comment]
@hongsudt I think this makes sense in general. I would agree. However, before I can really give more comments here I would like to see an example. You mentioned some from RBK but I don't have enough context about that to jump in yet. I could imaging from my FaceBase experience and even CIRM that there are FK references that we use just to 'aggregate' information up to the so-called Dataset entity and you are absolutely right that it would be confusing to add an `assay` to a `dataset` when really we want the user to add the `assay` to the `sample` and the reference from assay to dataset should just be generated by the system. That's an example I can think of that would be applicable to this scenario.

@karlcz In the example I have in mind (paragraph above), in that particular scenario privilege level is not an issue. You raise a good question though.
