### ISSUE TITLE
support adding a batch of pure and binary association entries 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1231]
For pure and association entries, when a user click "add", it should open up a multi-select modal and allow users to select a set of entities to be added at once. This feature will be useful for adding members to a collection.. 

We will probably have to deal with users choosing a subset of entities that have been previously added to the table.

**Comment by amitjha21** [comment]
Steps:

1. When `Add` button is clicked of pure and association related table it should open a modal pop up.
2. Modal pop up will display table with all permitted domain value for the field.
3. Multi-select checkbox should appear in the left most column in pop-up table .
4. Modal would be modified to accommodate **Submit** button (Existing `modal` directive to be modified).
5. After clicking **Submit** button pop-up disappears and records are added in the table in the `record` page.

**Note: User Control never goes out of `record` page.**

### Example of Modal pop-up
![image](https://user-images.githubusercontent.com/9977014/29379494-8ba34436-8277-11e7-8d51-c43eb037e839.png)

**Comment by amitjha21** [comment]
Few suggestions:

1. Avoid the UI shifting when selecting your first pick. Maybe put a placeholder at the top so that the page doesn't shift.
2. after submitting the main record page's nested entity does not reflect the change.
3. If you pick something that has already been picked you get a 409 : This needs more discussion on how to fetch only permissible domain values. 

Future Changes:
1. Having pre-checked permissible values in the modal box.

**Comment by amitjha21** [comment]
Refresh issue for added record fixed. (_Bullet 2 in above comment_)

**Comment by amitjha21** [comment]
This has been merged. Assigning to @hongsudt to verify and close it.
