### ISSUE TITLE
Incorrect display of immutable asset column in the edit context

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1253]
In the edit mode, if the file url exist, it should be shown under the uri column. On GPCR, the current uri (though exists) is not shown. 
https://staging.gpcrconsortium.org/chaise/recordedit/#1/assets:cpm/sha256=00220d82f5b98a3f043eeac13b027b33a23dc9ad5ad597621fda16b064852103@sort(last_modified_timestamp::desc::,id)

Also, the (*) is not shown even though the uri column is NOT NULL. 

Note: I only see this issue on gpcr and not on RBK.  https://dev.rebuildingakidney.org/chaise/recordedit/#2/Protocol:Protocol/ID=2;ID=5@sort(ID)

**Comment by jrchudy** [comment]
After debugging the root cause of this issue, I noticed that the underlying column in GPCR has the `immutable` annotation. 

This uncovered some other bugs in `recordedit` though. 
 - The `*` for required is not showing up properly
 - The input field is not disabled properly (button as well)
 - The input field does not show the original value properly
