### ISSUE TITLE
More asset and download features

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1314]
The current uploader/downloader is pretty restrictive and doesn't work well for my use cases.

- The `url_pattern` field is required even though it only matters for upload.  This means you can't get a consistent download chicklet for existing assets where you don't intend to support upload via the GUI.
- There is no pattern field for filenames to allow a preferred download filename to be defined from metadata when there is no actual filename storage column.
- The download chicklet shows the full URL e.g. ugly hatrack URLs for download. Should there be a pattern to define the presentation value here too?  I'm not sure...

**Comment by hongsudt** [comment]
We will need to support the following case, so that the asset annotation can be used by other client tool. 
- If `url_pattern` is not provided, don't provide an upload interface during the editing. Treat it as a regular column. 
- Support `browser_upload = true/false`. This will allow the `url_pattern` to be used for other client upload.

**Comment by RFSH** [comment]
In the following I summarized the logic for creating an asset column (showing upload interface in entry contexts and download link in other contexts). It includes the new changes that we want:

- In entry contexts:
   - Show upload interface if `url_pattern` exists and it's well-formed (starts with `/hatrac/`), and the `browser_upload` is not `false`.
   - Otherwise treat is as a regular column.
- In other contexts:
  - If asset annotation exists (its value is not important) create the download link.
  - Otherwise treat it as a regular column.

If these logics are what we want, then this doesn't require any changes in chaise and only ermrestjs needs to be changed.

**Comment by RFSH** [comment]
These changes has been merged. I updated the annotation document too.
@karlcz Can you please review this feature?

**Comment by karlcz** [comment]
I see that this now works for example on 

https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Synaptic%20Pair%20Study/RID=EXA

However, I'd really like to see a heuristic to use a pattern-match to simplify the value displayed in the download chicklet.  For the common case of hatrac URLs, can we show just the basename without the version qualifying suffix nor the whole path to the file?  A regular expression like this might do the trick:

    ^/hatrac/([^/]+/)*([^/:]+)(:[^:]+)?$

when this matches the whole string (the `^` and `$` are beginning and end anchors), the first optional parenthetic group will match any namespace/folder path, the second parenthetic group will match the basename I would want to display, and the third parenthetic group will match the optional version suffix.

**Comment by RFSH** [comment]
I changed the filename logic to be what you explained. If `filename_column` is missing in the annotation, I am matching the value with the given regex. If it matched, it will return the filename; otherwise the whole url will be used.
