### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1389]
### Updated (Jan 23) Description

In here I tried to summarize what we discussed in person and also the comments. You don't need to follow the comments and this description should be sufficient. 

#### Errors
Currently we're only logging terminal errors (we might want to change that to log 5xx errors too). To find the errors in log, you can search for `terminal_error` path. This is what a error log would look like:

```
{
   e: 1,
   message: "ERROR MESSAGE",
   name: "ERROR TITLE"
}
```

#### CRUD Requests
Since we are using http headers for logging, we can only log on the functions that we are creating a request to ermrest. These are the scenarios that chaise is sending a request to ermrestjs and the object that we want to log (In all of the requests we're logging `schema_table`, `facet`, and 'page_size'):

| #  | Description                                                   | Action                                  | Extra            | Notes                   |
|----|---------------------------------------------------------------|-----------------------------------------|------------------|-------------------------|
| 1  | read primary table                                            | record/main                             |                  |                         |
| 2  | read related tables                                           | record/related                          | referrer         | secondary               |
| 3  | update related tables (after edit/delete)                     | record/related/update                   | referrer         | secondary               |
| 4  | create entities                                               | create/new                              |                  |                         |
| 5  | read foreignkey values for prefill                            | pre-create/prefill                      | referrer         |                         |
| 6  | create inbound related (click add on related)                 | create/prefill                          |                  |                         |
| 7  | read association values to add new one (click on add for p&b) | pre-create/prefill/association          | referrer         |                         |
| 8  | read currently available p&b entities in the modal            | pre-create/prefill/association/disabled |                  | secondary               |
| 9  | create p&b association (click on add related)                 | create/prefill/association              |                  |                         |
| 10 | create by add button on fk modal                              | create/modal                            |                  |                         |
| 11 | read current data before copy                                 | pre-create/copy                         |                  |                         |
| 12 | create by copying                                             | create/copy                             |                  |                         |
| 13 | get data for default value                                    | recordedit/default                      |                  | secondary               |
| 14 | read entities to be updated                                   | pre-update                              |                  | page_size is inaccurate |
| 15 | update entities                                               | update                                  |                  |                         |
| 16 | recordset main data read on load                              | recordset/main/load                     |                  |                         |
| 17 | recordset main data read on page change                       | recordset/main/page                     | sort, page       |                         |
| 18 | recordset main data read on sort change                       | recordset/main/sort                     | sort             |                         |
| 19 | recordset main data read on limit change                      | recordset/main/limit                    |                  |                         |
| 20 | recordset main data read on facet change                      | recordset/main/facet                    |                  |                         |
| 21 | recordset main data read on update                            | recordset/main/update                   |                  | secondary               |
| 22 | recordset get main count                                      | recordset/main/count                    |                  | secondary               |
| 23 | recordset read facet                                          | recordset/facet                         | referrer, source | secondary               |
| 24 | recordset click on show details                               | recordset/viewmore                      | referrer, source | secondary               |
| 25 | delete from record                                            | delete/record                           |                  |                         |
| 26 | delete from recordedit                                        | delete/recordedit                       |                  |                         |
| 27 | delete row from recordset table                               | delete/recordset                        |                  |                         |
| 28 | delete related entity rows                                    | delete/recorset/related                 |                  |                         |

Notice that the `source` is the source of facet (the array that represent the path), and also the `referrer` includes `schema_table` and `facet`. 

#### Truncating The Object

The object that we want to log might be lengthy so we should truncate this object if it's exceeding the maximum length (we're currently limiting it to 7000). If the object has `t:1` that means it has been truncated. If the content was longer than the limit, we should truncate based on this order: facet, source, referrer. Which means that referrer has more priority over source, and source over facet. 

---------------------
<details>
<summary>
<strong>Previous Description</strong>
</summary>
<br>

Here is a list of simple metrics and log parameters that I think we can use to start the logging/analysis activities. 

### Metrics:
* users
  * number of users
  * average number of sessions per week
* hatrac
  * user-download (need to distinguish between user-initiated vs auto-download)
* record
  * top 10 tables
  * top 10 entries for each table
* recordset
  * top 10 tables
  * top 10 facets
  * top 10 facet values (popularity)
* recordedit
  * top 10 tables?
  * change history --> analyze through history (provenance)

### Log parameters:
* client ID (cid)
* window ID (wid)
* page ID (pid)
* context (context): maybe this can be an array of sequential contexts
  * detailed
  * compact
  * facet
  * entry/create
  * entry/edit
  * entry/copy
* table
  * Schema:Table
* facets
  * Use the facet-structure json for facets
  * needed for all events except entry-create

### TODO:
* chaise decorate asset link with query parameter "uinit=1"
* dba annotates with the same query parameters for download link
* question: can we create a style class that does this automatically?
</details>

**Comment by hongsudt** [comment]
This needs informatics-isi-edu/ermrestjs#558.

**Comment by RFSH** [comment]
Instead of just having just `event-type`, we can have two different variables one for the `context` that the request has been generated from, and the other `action`. For instance if you load the page,
- The request for getting the data set: `context: "compact", action: "load page"`
- The request for getting data for one of the facets: `context: "compact/select", action: "load facet"`
- The request for getting next page of dataset: `context: "compact", action: "load next page"`

**Comment by RFSH** [comment]
We decided that we don't need `context` and `action`. Just an action field would suffice. Since we can only log events when we're talking to ermrest, the following are the list of ermrest actions and the log action.

| #  | App        | ermrestjs Action          | Summary                                                                         | Logged Action             |
|----|------------|---------------------------|---------------------------------------------------------------------------------|---------------------------|
| 1  | Record     | read                      | read main entity                                                                | record/main               |
| 2  |            | read                      | read related entities                                                           |                           |
| 3  |            | delete                    | delete main entity                                                              | delete/record             |
| 4  |            | read                      | read pure and binary association entities (on load)                             | pre-create/prefill/binary |
| 5  |            | read                      | read pure and binary association existing entities (on page, sort, search)      |                           |
| 6  |            | create                    | add pure and binary association                                                 | create/prefill/binary     |
| 7  | Recordedit | read                      | read main entity                                                                | pre-update                |
| 8  |            | read                      | read main entity for copy                                                       | pre-create/copy           |
| 9  |            | read                      | read the prefilled foreignkey column                                            | pre-create/prefill        |
| 10 |            | read                      | read foreignkey values for selecting                                            |                           |
| 11 |            | create                    | create new record                                                               | create/new                |
| 12 |            | create                    | create new record from copy                                                     | create/copy               |
| 13 |            | create                    | create new record having prefilled value                                        | create/prefill            |
| 14 |            | create                    | add a new entity (add button on fk modal)                                       | create/modal              |
| 15 |            | update                    | update the entity                                                               | update                    |
| 16 |            | delete                    | delete the entity                                                               | delete/recordedit         |
| 17 | Recordset  | read (resultset)          | read the main entity (on load)                                                  | recordset/main            |
| 18 |            | read (resultset)          | read the main entity after user changed sort                                    | recordset/main/sort       |
| 19 |            | read (resultset)          | read the main entity after user changed sort                                    | recordset/main/page       |
| 20 |            | read (resultset)          | read the main entity after user changed sort                                    | recordset/main/download   |
| 21 |            | read-entity               | initialize facet entities for main page (on open)                               |                           |
| 22 |            | read-agg or entit         | read facet entities for main page (on open, update facets, search, main search) |                           |
| 23 |            | read-agg or entity        | read facet entities for modal (on open modal)                                   |                           |
| 24 |            | read (select filter list) | after submitting the facet modal                                                | facet/selection           |
| 25 |            | delete                    | delete one of the rows                                                          | delete/recordset          |
| 26 |            | csv                       | getting the csv for the list                                                    | recordset/main/download   |

**Comment by RFSH** [comment]
One of the issues that the specification in the previous comment has is the facet that we cannot figure out the source of `update` log. Ending up in the recordedit page to edit a page with a url, clicking on edit on recordset, and clicking on edit in record page will be logged the same.

**Comment by RFSH** [comment]
Since we're adding a lot of extra information in the header, we should be cautious of the HTTP header limit size and truncate the log information before reaching the limit.

**Comment by RFSH** [comment]
This is done. I updated the issue description to reflect what has been implemented. I also created [this wiki page](https://github.com/informatics-isi-edu/chaise/wiki/Logging) so we can easily find the documentation for logging. @hongsudt Should we close this issue?
