### ISSUE TITLE
Make "Confirm Delete" dialog informative

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1430]
Currently it asks if you want to delete "this". If possible, let's replace "this" with the entity's row_name.

**Comment by RFSH** [comment]
In chaise we're using angular-ui modals. We wrote the `showModal` function to facilitate the usage of modals. To use this function you have to pass an object that has all the attributes of the modal, a success callback, and an optional reject callback. This is an [example](https://github.com/informatics-isi-edu/chaise/blob/master/common/faceting.js#L1003) of it in the code. As you can see you can pass parameters that you can use in the controller later.

The following are the two places that we're showing delete confirmation modal:

- [ellipses.js](https://github.com/informatics-isi-edu/chaise/blob/master/common/ellipses.js#L33) This directive is used in record table. `ellipses.html` represents each row of the table. `ellipses.js` has access to the `tuple` object. `Tuple` in ermrestjs represents a row of data. Calling `tuple.displayname` will give you the presentation object for that tuple (or what we call `row-name`). It has `value`, and `isHTML` which you can use. just pass the presentation object to the modal controller. Let's call the parameter that you're passing `displayname`.
- [deleteLink.js](https://github.com/informatics-isi-edu/chaise/blob/master/common/delete-link.js#L45) This directive was originally written so that we can use the same delete-link everywhere, but it's currently only used in [record](https://github.com/informatics-isi-edu/chaise/blob/master/record/index.html.in#L33). You need to pass the presentation object to this directive. We're attaching `tuple` to `$rootScope` in record app. You can just pass the `$rootScope.tuple.displayname`. Since `deleteLink` directive is written in a general sense (it can be used for bulk delete as well as deleting just one row) you shouldn't name the variable as `row-name`. You can call it `displayname`.

[This](https://github.com/informatics-isi-edu/chaise/blob/master/common/modal.js#L26) is the controller for the modal that we're using for confirmation of delete. In here, you can attach the `displayname` that you're passing to the controller and then use it in the template.

**Comment by RFSH** [comment]
This has been done as part of React migration.

**Comment by robes** [comment]
I noticed. It looks good!

From: Aref Shafaei ***@***.***>
Date: Wednesday, May 31, 2023 at 2:26 PM
To: informatics-isi-edu/chaise ***@***.***>
Cc: Robert Schuler ***@***.***>, Author ***@***.***>
Subject: Re: [informatics-isi-edu/chaise] Make "Confirm Delete" dialog informative (#1430)

This has been done as part of React migration.
