### ISSUE TITLE
verify that we can deploy multiple versions of chaise

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1498]

**Comment by jrchudy** [comment]
Looks like the only "hardcoded" relative path for `ermrestJS` is in our Makefile for `chaise`.

**Comment by jrchudy** [comment]
The following variables, `ERMRESTJS_RT_DIR` and `ERMRESTJS_BLD_DIR`, need to be made conditional in the `Makefile`. i.e. `ERMRESTJS_RT_DIR?=../../ermrestjs`.

Better documentation for the 2 environment variables would make it more obvious how this can be done in `chaise`. These 2 environment variables can be defined for each deployment so the location of `ermrestJS` relative to `chaise` doesn't matter at all.

One change needs to be made in `ermrestJS` as well so that the JS variable we use for attaching the vendor scripts in the proper order is no longer purely relative to the server root.

**Comment by hongsudt** [comment]
I am closing this issue..
