### ISSUE TITLE
batch unlink of members in pure and binary association

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1535]
For pure and binary association, there is no way to get to a full set of these entries. Users can only see what's shown under the related tables. We should mimic the multi-select add to provide multi-select delete. 

In the delete case, it should direct users to those records that are currently associated with the main entities, allow users to select multiple entries, then click submit.  On top of the related table in the record page, maybe we can have "Remove" or "Unlink" to trigger the batch delete flow.

**Comment by jrchudy** [comment]
Use "Remove" in the modal title instead of "unlink". The same goes for the "submission" button.

**Comment by jrchudy** [comment]
The changes for this issue have been merged into master. Reassigning to @hongsuda to verify and close.

**Comment by karlcz** [comment]
I tried to test this on synapse-dev.  I went to https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Cohort%20Analysis/RID=17AR and tried to remove items from the "Cohort" related entity section.

The modal lets me pick items and shows them in chicklets at the top.  But, the remove button closes the modal and nothing else happens.  I don't see any DELETE request on the server either.

**Comment by hongsudt** [comment]
I also find the plus button on the modal confusing.  We should remove that button from the remove modal.

**Comment by RFSH** [comment]
One of the confusing parts of the implementation of batch-unlink that we reverted was the fact that users could remove the existing facet. I [recently added](https://github.com/informatics-isi-edu/ermrestjs/pull/752) the `hidden` support to facets in the url. Now you can have facets in your url that won't be merged in the faceting UX and users won't be able to remove them. 

The reference that we are going to use for the modal picker should be the result of calling `.hideFacets()` on the related reference.

**Comment by jrchudy** [comment]
Related to issues #1060  and #1591 .

**Comment by jrchudy** [comment]
Enhancements that can be done before sending the delete request:
 - previously the request was based on the "filtered url", so if no filter was applied, all rows were being unlinked. Instead, iterate over the list of rows to unlink and use their "shortest keys" in the url to make sure the reference is specific to only the rows being "unlinked"
 - sanity check the data in ermrest before sending the delete request
    - send a get request to the url produced for delete and verify data is consistent with what the UI knows about
    - if deleting 10 rows, get request should return 10 matching rows etc.
 - change confirm delete dialog text to communicate number of rows being removed
    - current text for single delete:
       - "Are you sure you want to delete this?"
    - multi delete text:
       - "Are you sure you want to delete X rows?"

**Comment by jrchudy** [comment]
How to handle error for batch unlink:
 - only 1 reference (selection is under url limit)
   - error out and show user an alert as to what went wrong (ermrest or ermrestJS error)
 - 2+ references (selection over url limit)
   - error in 1st reference.delete
     - error out and show user an alert as to what went wrong (ermrest or ermrestJS error)
   - error in nth reference.delete
     - **Currently it succeeds and unlinks for references 1 through n-1 and rows in nth reference will remain linked**
     - _fill in an alternative_
     
Error cases in data sanity check:
 - only 1 reference (selection is under url limit)
   - error out and show user an alert saying "something went wrong, contact an admin"
 - 2+ references (selection over url limit)
   - error in 1st reference.getAggregates
     - error out and show user an alert saying "something went wrong, contact an admin"
   - error in nth reference.getAggregates
     - error out and show user an alert saying "something went wrong, contact an admin"
   - summation of ALL getAggregates does NOT equal length of selected tuples

**Comment by jrchudy** [comment]
Changes that were discussed in our meeting on Tuesday regarding how to best handle batch deletion:
 - create a new "delete" function in ermrestJS specific to deleting batch association references
   - [ ] return from function instantly if reference is not defined, tuples is not defined, or tuples is length < 1
   - [ ] instead of creating individual references and calling reference.delete(), write a function that uses http.delete with the proper ermrest path for each chunk of data to be deleted
   - [ ] verify the data being used to create a path is defined and non-null
   - [ ] verify the created paths can parse to a proper location object with one defined filter, which may be one or many filter predicates
   - [ ] further verify created paths' filter(s) are based on the same uniqueness constraints for all rows to be deleted
   - [ ] do deletion in sequence since ermrest doesn't like doing parallel mutations
     - collect all success and error responses in 2 arrays and return to calling site in chaise
 - in chaise, check success and errors arrays
   - [ ] all success
     - close modal
     - show success alert
     - update the record page data
   - [ ] some success and some errors
     - show alert describing the errors
     - update data in the modal to reflect deleted rows (refetch rows and count)
   - [ ] all errors
     - collect information about errors and show them to the user as an alert
     
To be done later:
 - [ ] change unlink modal to remove checkboxes for rows that violate trs rights
