### ISSUE TITLE
IE11 bug - checkmarks and icons do not appear

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1560]
@crisaless commented on [Fri Jan 26 2018](https://github.com/informatics-isi-edu/rbk-project/issues/424)

When you try to use chaise on IE11/Win - checkmarks do not appear when you click on checkboxes and the Action icons are blank

**Comment by dhanashritidke** [comment]
@crisaless                     

I tried to reproduce this issue with the following configurations :
1. Internet Explorer 11 and Windows 7.
2. Internet Explorer 11 and Windows 8.1.
3. Internet Explorer 11 and Windows 10.

On all of the above configs, both the check marks and Action icons were visible. 
I verified the following cases - 
1. Check marks on the Search page for attributes.
2. Check marks for Facets in the Panel for facets.
3. Action icons on Record set, Record pages and the div below the navigation bar.

If you could kindly confirm that the issue is still reproducible (rbk/chaise) on your end and provide further details about it, it'll be really helpful.

**Comment by hongsudt** [comment]
@crisaless can you please verify whether this is still an issue, if not, please close the issue.

**Comment by crisaless** [comment]
I just checked the facebase chaise, IE11/Win 7 and IE11/8.1, - checkboxes worked on the recordset filters - but if you go to "Show Details", I couldn't check the boxes on the modal window.

I didn't have access to IE11 on Windows 10 through vmware

**Comment by hongsudt** [comment]
@Divyata-Singh is this still an issue?

**Comment by hongsudt** [comment]
@crisaless Can you review the issue? If the nature of the problem has changed, please generate a new issue..

**Comment by crisaless** [comment]
yes checkboxes now work on the modal windows too on E11/Win8
