### ISSUE TITLE
Inconsistent and incorrect presentation of non-editable/insertable attributes

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1609]
In this screenshot, the user has permission to insert a row into the "Dataset" table but not insert values in the "Released" and "Release Date" columns. These columns have no further annotations set; i.e., they do not have "generated" or "immutable" annotations set on them.

Background:
- `released` is a `boolean`
- `release_date` is a `timestamptz`

*Inconsistency*: The cursor changes when hovering over the "Release Date" attribute but not the "Released" attribute

*Incorrect*: Chaise says "Automatically generated" on the "Release Date" which is not true. There is no default expression for that column and therefore it will just be Null.

![image](https://user-images.githubusercontent.com/4202842/43287484-06281e2c-90da-11e8-9766-cfd3fc337f20.png)

**Comment by RFSH** [comment]
There are two issues here:

- Since user doesn't have `insert` access to the `release_date`, we're handling it the same way as having generated annotation. We're not treating that as a specific case. We might want to change that but that's why this is happening as expected. This is part of ermrestjs.

- About the cursor, it seems like we're only changing cursor for [the inputs that have the specific class name](https://github.com/informatics-isi-edu/chaise/blob/master/recordedit/recordEdit.css#L149). In this case, the boolean main div doesn't have that class name. We might want to generalize that.

On the side note, can you please give write access to the `isrd-testers` group? It's hard for us to investigate facebase issues without actually being able to recreate the scenario.

**Comment by robes** [comment]
Understood, its just a potentially incorrect statement (“automatically generated”)

**Comment by robes** [comment]
I've added `isrd-testers` to the write acls.

**Comment by hongsudt** [comment]
@robes If you don't want the word "Automatically generated", what would you rather display for the Release Date?  Nothing? (but this is kind of wierd).. "Not allowed"?

**Comment by robes** [comment]
Good question. Maybe ‘No value’ or ‘None’ if there is:
- no insert permission, and
- no default expression, and
- no ‘generated’ annotation

If on the other hand, the DBA knows that there is a backend process (i.e., a python script or bash script that will generate a value later) then he/she should use the ‘generated’ annotation in that case, right?

> @robes<https://github.com/robes> If you don't want the word "Automatically generated", what would you rather display for the Release Date? Nothing? (but this is kind of wierd).. "Not allowed"?

**Comment by RFSH** [comment]
Instead of showing "Automatically generated" for the columns that user doesn't have access to, we're showing "Not Allowed" from now on.
