### ISSUE TITLE
Flow Control faulty logic

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1622]
While debugging an issue found when working on the recordset table performance changes to recursively push more rows into the DOM, we noticed that some requests were not being "canceled" correctly. 

Sometimes you can get the app into a state where 2 of the same request are sent to the server and both are acted on to completion. This isn't an issue in the normal functioning of the app but when the data is paging into the DOM, you can notice this occurring much more often.

**Comment by RFSH** [comment]
#1764 has fixed an issue related to generating duplicated requests. This issue might have been caused with the same flaw that I fixed. I'm not sure what's the best way to test this since the problem described in this issue is not very deterministic. But in my testing in `gudmap-dev`, I couldn't see any evidence of this.
Assigning to @jrchudy for more testing and verification.

**Comment by jrchudy** [comment]
I don't see any duplicate requests like I was before. 

With this being fixed we should go back and look at the [logic for paging](https://github.com/informatics-isi-edu/chaise/blob/master/common/table.js#L291-L320) the recordset content into the DOM when there is "more than X cells" to put data into.
