### ISSUE TITLE
Better Handling of Server Errros

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1670]
Currently all the 5x errors and "No Connection Error" ("No Connection Error" means that ermrestjs couldn't send the request to server for any reasons) are terminal. We should improve this. These are the few changes that comes to my mind:

- We might want to add "No Connection Error" to the list of retry errors in ermrestjs. This might cause some problems though. We should make sure that we're completely testing chaise behavior after this change. I remember the 401 error handling was not behaving properly when I made this change few months ago.

- The simplest solution would be offering a button to reload the whole page. The first issue with this would be the fact that we have already tried multiple times and reloading might make the user to wait a long time. Also this error might happen for just one request in the page and reloading the whole page might not be necessary.

- Allow error to be dismissible. This might be the better solution, but it would mean that we have to make sure chaise is going to be in a working state after dismissing the error.

**Comment by jrchudy** [comment]
To address the bullet points above:
 - we added the `No Connection Error` to the list of retry-able errors in [this commit](https://github.com/informatics-isi-edu/ermrestjs/commit/db68cadd76b4ab2e3696ad5f71cc91c62bae55bc) in `ermrestJS`.
 - There now is a reload button when a No Connection Error occurs while the app is still loading
 - We aren't allowing the error to be dismissible because the case we would want it to be dismissed in would be during submission of the `recordedit` form. In that case, the error is shown as an alert instead of a modal popup.
