### ISSUE TITLE
history: add "current snapshot" link to get from historical snapshot to the current snapshot

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1673]
When recordset and record displaying historical records, we should:
- make it clear that it is a historical record --- maybe adding version number somewhere in the title area
- provide a link to get to the latest snapshot

**Comment by hongsudt** [comment]
@carlkesselman this is now ready on dev..

**Comment by hongsudt** [comment]
@karlcz can you review this issue?

**Comment by karlcz** [comment]
Can someone provide some sample chaise page links to see this feature?

**Comment by karlcz** [comment]
I manually constructed a link to a record page w/ a snapshot in the chaise URL on my dev system.  I see some problems with the UX:

1. The `Live Data` link has no tooltip
2. The `Live Data` link is in the navbar when I think it should be in the toolbar.
3. The tooltop for the `Tablename (Version xxx-xxxx-xxxx)` does not include any explanation of the snapshot

In its current position next to the username, it looks more like a status indicator with the opposite intent of what it really means.  I.e. it seems to suggest this is "live data" when it is really a way to leave this historical data and go to live data.  If kept in its current position, it should be rewritten as `Historical Data` and have a drop-down with an action like `Go to current data` so it provides a UX more consistent with the login button next to it. (And perhaps we would add other history-related functions later?)

If moved to the toolbar, it should be rewritten as an action `View Current Data` so it acts like other buttons in the toolbar.

I wonder if we should duplicate a bit of snapshot ID decoding logic in ermrestjs so that Chaise can turn it into a timestamp and then use that for presentation purposes such as giving a (rounded off) timestamp in the tooltip for the tablename-at-snapshot.

Also, a minor nit is that if I construct a URL with a non-normalized snapshot ID, Chaise will stay at this catalog version and (I presume) make all ermrest requests to this snapshot. If we get sloppy clients producing sloppy versions, this will be confusing and reduce cache efficiency.  If we wanted to, Chaise could make an initial check to `/ermrest/catalog/N@snaptime1` to see if the snaptime1 value is the same as that in the `snaptime` field of the response.  If not, it could revise the app catalog location to `N@snaptime2` which is now normalized...

**Comment by hongsudt** [comment]
@karlcz @jrchudy can you paste a url here so I can see this feature? I don't know a valid version for me to see this.. 

I agree that there should be a time component to tell the rough time of the version.

**Comment by jrchudy** [comment]
What I did to look at versioned data was query the [catalog API](https://dev.rebuildingakidney.org/ermrest/catalog/2)(https://dev.rebuildingakidney.org/ermrest/catalog/2) and use the snaptime property as the version.

https://dev.rebuildingakidney.org/chaise/recordset/#2@2R5-T8JX-8NQ2/Common:Gene/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM4gEEIBPAfQBEwAXMEAGhCwAsUBLXJOeKjNHAXQC+QoA@sort(RID)

**Comment by jrchudy** [comment]
Changes discussed for this issue:
- [ ] change text from `Live Data` to `View Live Data`
- [ ] tooltip for this button
- [ ] displaying version text doesn't mean much to the user. Show a timestamp instead (#1733 )
  - should display `x minutes ago` when < 1 hour
  - should display `x hours ago` when < 1 day
  - should display `x days ago` when < 1 week
  - otherwise show the actual date (no time necessary)
- [ ] tooltip for the time content
- [ ] share dialog (both `record` and `recordset`) should have snapshot link & live link
