### ISSUE TITLE
Enforce a maximum limits on number of records on recordset to be exported

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1682]
Apply max limit for recordset export or throw a warning when total records to be exported is large (e.g. 1M row?)

**Comment by RFSH** [comment]
In ermrestjs currently we are adding a `limit=none` to the end of url to signal that we want every row. We can change that to a predefined number.
I don't think throwing a warning would be possible. We have no idea how many rows the queries in the template might return. Also we cannot simply turn all of them to a count request because the path can be arbitrary.

**Comment by hongsudt** [comment]
There is a total count on the page that can be used, correct?

**Comment by RFSH** [comment]
@hongsudt Yes, that is the total number of rows that we want the ermerst query to return. If it's set to `none` (which is the current implementation), it will return everything.

**Comment by hongsudt** [comment]
We discussed about this during the meeting and found that there is nothing that the frontend can do. The limit should be enforce by the export service. Once the export service supports asynchronous export, the size might be come less problematic. 

@karlcz do I summarize this correct? Anything to add?

**Comment by hongsudt** [comment]
I am closing this issue.. It can be reopened when we have a clear use case.
