### ISSUE TITLE
Error message on file upload in RecordEdit

### ISSUE THREAD

**Issue by Divyata-Singh** [informatics-isi-edu/chaise#1711]
When the network is disconnected while uploading a file in the recordedit app, the alert gives the angular stack trace instead of a proper error message.
![UploadError.PNG](https://images.zenhubusercontent.com/5b0458274b5806bc2bd42f17/f4f793d0-6fb0-46c3-a76c-ee1e8137449b)

**Comment by jrchudy** [comment]
To reproduce this error:
>1. navigate to `recordedit`
>2. add a file to be uploaded
>3. before clicking submit, disable the internet connection
>4. click submit

The error occurs because the browser can't fetch the `uploadProgress.html` template. This error will occur anywhere in any of the apps if the internet is disconnected while the app is trying to fetch templates. The error is only exposed in `recordedit` though. In record and recordset, this error is swallowed up (never shown to the user).

This can be reproduced in `recordset` by waiting for the app to load, then disconnecting the network, and finally try to open a "show more" dialog.

This can be reproduced in `record` by waiting for the app to load, then disconnecting the network, and finally try to open an "add" dialog for a pure and binary related table.

**Comment by jrchudy** [comment]
In both `record` and `recordset`, this error case recovers without incident if the network connection returns. The retry logic continues to run trying to fetch templates. When or if they resolve, those errors are swallowed up and no template is displayed to the user. If the user retries the action after the connection is restored, everything behaves as expected.

**Comment by jrchudy** [comment]
@hongsudt and I discussed this issue on Friday and the plan is to show a dismissible error popup when the user encounters this error in any of the chaise apps. This error being when we have a network outage that doesn't allow the user to communicate with the server and fetch templates after the page has loaded (usually when a secondary action is taken that shows a modal dialog).

One reasoning behind this is to not distract the user (move their attention by scrolling or simply adding another colored element to the top of the page). This is going to be handled the same everywhere in the application as a "blocking" error that's dismissible because the user should take an action to verify that it's not a loss of network connectivity on their end.
