### ISSUE TITLE
Serialize POST/PUT/DELETE Requests

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1723]
We should completely serialize all POST/PUT/DELETE requests to a catalog. There should NOT be any concurrent mutation requests as all but one of them will almost certainly fail with a 503 response.

We have to make sure we are preventing users from generating such requests. One example of this would be disabling the submit button in recordedit after submitting. This task is just to look at the behavior of current apps, and as a result we might find out that we don't have to change anything.

**Comment by karlcz** [comment]
Just to be clear, if making changes to the GUI you should disable the button during the click, before sending the request, and reenable after the promise is resolved.

However, I think the real issue is in the test suite slamming the service with concurrent changes, or if we ever add an app that programmatically initiates multiple mutation requests due to a single input event.

In practice, it is always possible that independent real users will hit the server concurrently but since user-initiated actions are so infrequent, the chances are pretty low and the normal backoff/retry on 503 should handle that OK.
