### ISSUE TITLE
History: Generate a proper timestamp based on the history version

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1733]
Instead of showing a string version (that is not time-based), we should convert this string to a time and present this value. 

@karlcz  Can you write out an algorithm for this conversion here? 

With this, we should present the time smartly e.g. 
- if the difference is less than 24 hours, report the difference in hours e.g. 5 hours ago
- if the difference is less than 1 week, report the difference in days e.g. 2 days ago
- Else report the actual date of the snapshot

We should look at examples from somewhere else for this..

**Comment by jrchudy** [comment]
I agree that a version that is less than a week old should be shown as relative to the current date and time. I think we should be precise down to minutes though if it's less than 1 hour (e.g. 34 minutes ago).

**Comment by jrchudy** [comment]
Javascript allows for the following [bitwise operations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators):
![image](https://user-images.githubusercontent.com/2932600/53830200-c22ca380-3f36-11e9-8a90-e2ccdffb68ac.png)

**Comment by karlcz** [comment]
# Example Values

First off, you can generate example values and results easily via SQL on an ermrest catalog db:

    SELECT _ermrest.tstzencode(now());
    tstzencode
    -------------
    2R6-QAMZ-AB8W

    SELECT _ermrest.tstzdecode('2R6-QAMZ-AB8W');
    tstzdecode
    ----------------------------
    2019-03-05 10:49:24.45915-08

My example values are in PST timezone because of where I ran the SQL. The encoded value itself does not carry a timezone indicator but is absolute time since epoch which is `1970-01-01 00:00:00 UTC`.

More illustrative values:

Postgres timestamp  | Notes | Integer  | Encoded String
----------|--|---------|------------
N/A | lowest integer `-2^63` | -9223372036854775808 | `G-0000-0000-0000`
4714-11-24 00:00:00 BC | earliest possible timestamp in postgres | -210866774822000000 | `Z-M9DK-J8QS-NN80`
1969-12-31 15:59:59.999999-08 | one microsecond before epoch | -1 | `Z-ZZZZ-ZZZZ-ZZZY`
1969-12-31 16:00:00-08 | epoch | 0 | `0`
1969-12-31 16:00:00.000001-08 | one microsecond after epoch | 1 | `2`
294247-01-09 20:00:54.775423-08 | `2^63-1` microseconds after epoch | 9223372036854775807 | `F-ZZZZ-ZZZZ-ZZZY`

Note that the encoded string `2` represents the integer 1 because of the extra bit of padding in the final encoding symbol. This can be confusing if you try to test with small integers!

## Encoding/Decoding Rules

Conceptually, the encoding is pretty simple:
1. A timestamp is converted to a 64-bit integer representing microseconds since the Unix "epoch" time.
2. The 64-bit integer is encoded using a base32 encoding variant meant to avoid typographical/transcription errors. (See below).

The decoding is obviously the reverse:
1. The string is decoded using base32 to obtain the 64-bit integer microseconds since "epoch" time.
2. The integer is converted back to the native timestamp format using environment-appropriate methods.

## Base32 Variant Codec

Like base32 in general, we use one 8-bit symbol to represent each 5-bit chunk of raw data. However, our codec is not interoperable with the standard base32 codecs:
- We convert lower case to upper case prior to decoding
- We strip `-` characters used as optional visual grouping separators prior to decoding
- Several optional symbols are mapped to a canonical symbol prior to decoding
   - letter `O` becomes digit `0`
   - letters `I` and `L` become digit `1`
- We use a different symbolic mapping that avoids certain visually ambiguous letters
   - The hexadecimal digits `0` ... `F` represent codes 0 ... 15
   - The letters `G`, `H`, `J`, `K`, `M`, `N`, `P` ... `T`, `V` ... `Z` (*skipping* `I`, `L`, `O`, and `U`) represent codes 16 ... 31

Our codec produces variable-length strings but implicitly expects to encode/decode a 64-bit value.
- The integer is encoded with most significant bit first.
- The longest encoded string uses 13 symbols (ignoring separators)
- The maximum encodable value is the integer 9223372036854775807 (i.e. `2^63 - 1`) which is encoded asarators) and the maximum integer is encoded as .
- Because the 13 symbols represent 65 bits, the least significant bit of the final symbol is ignored as padding.
- Leading `0` digits are optional, so `0` and `0-0000-0000-0000` encode the same integer 0.

## Implementation Issues

The codec algorithm can be written very directly using programming languages with arbitrary length bit-string manipulation. In this scenario, encoding and decoding are simple loops that convert one encoded symbol to 5 bits of raw data, shifting and masking bits as needed for the final padding bit.

However, extra care must be taken when attempting to implement this with limited precision bitwise operators or limited precision integers.

**Comment by karlcz** [comment]
Here is an implementation of decoding in Python using just basic string manipulation and floating-point arithmetic.  I think it should be pretty trivial to transcribe into Javascript...

```Python
# use 5-bit value as index to find symbol
# e.g. b32_symbols[15] == 'F'
b32_symbols = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'

# reverse mapping symbol -> 5-bit value
b32_values = {}
for i in range(32):
    b32_values[ b32_symbols[i] ] = i

def urlb32_decode_imprecise(s):
    """Decode 64-bit integer as approximate float value."""

    # map to canonical symbols w/o separators
    s = s.upper() \
         .replace('-', '') \
         .replace('O', '0') \
         .replace('I', '1') \
         .replace('L', '1')

    if len(s) > 13:
        raise ValueError('%d symbols exceeds limit of 13' % len(s))
    elif len(s) < 13:
        # normalize to full 13-symbol format as general case
        s = ''.join([ '0' for i in range(13-len(s)) ]) + s

    # interpret first symbol as 2's complement signed value
    accum = float(b32_values[s[0]])
    if accum >= 16:
        accum = accum - 32

    # interpret remaining symbols as unsigned values
    for c in s[1:]:
        accum = accum * 32 + b32_values[c]

    # remove least significant pad bit
    return accum / 2.0

def urlb32_decode_timestamp(s):
    """Decode ermrest 64-bit timestamp string."""
    # we will want milliseconds precision in javascript!
    ms = math.floor(urlb32_decode_imprecise(s) / 1000.0)
    # convert to python timetamp for testing...
    epoch_t = datetime.datetime(1970,1,1)
    result = epoch_t + datetime.timedelta(milliseconds=ms)
    print('decoded "%s" -> "%s"' % (s, result.isoformat(timespec='milliseconds')))
    return result

# test cases
assert urlb32_decode_imprecise('0') == 0.0
assert urlb32_decode_imprecise('2') == 1.0
assert urlb32_decode_imprecise('Z-ZZZZ-ZZZZ-ZZZY') == -1.0
assert urlb32_decode_imprecise('G-0000-0000-0000') == -9.223372036854776e+18
assert urlb32_decode_imprecise('Z-M9DK-J8QS-NN80') == -210866774822000000.0

assert urlb32_decode_timestamp('Z-ZZZZ-ZZZY-2YW0') == datetime.datetime.fromisoformat('1969-12-31T23:59:59')
assert urlb32_decode_timestamp('0') == datetime.datetime.fromisoformat('1970-01-01T00:00:00')
assert urlb32_decode_timestamp('1-X140') == datetime.datetime.fromisoformat('1970-01-01T00:00:01')
assert urlb32_decode_timestamp('2R6-QAMZ-AB8W') == datetime.datetime.fromisoformat('2019-03-05T18:49:24.459')

```

**Comment by jrchudy** [comment]
This is working for me. Thank you @karlcz .
