### ISSUE TITLE
improved test cases

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1744]
Our test process currently fails to run successfully on travisCI, mostly due to the longer network delay.  We don't have the same problem when the test suites are run locally. 

 @jrchudy has done some travis CI log analysis to identify test suites that often fails.. We should figure out why some of test keep failing..

**Comment by jrchudy** [comment]
Changes made in the catalog chaise configuration annotation PR, issue #1758 , fix the issues we have been seeing in the travis-ci build. We noticed some of our changes in PR #1700 fixed a good number of the issues with the tests but changes were made to change the loading of chaise apps in the catalog-annotation branch so those changes may not be necessary anymore.

Other changes to the tests (some the same and some different as #1700 ) were made in #1758 to address this change in configuration as tests were starting to fail locally as well instead of just in travis.

**Comment by jrchudy** [comment]
PR #1773  was merged today which fixed that last remaining test cases that were ALWAYS failing on travis. Closing this issue.
