### ISSUE TITLE
File Uploader Improvements

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1753]
After discovering a new bug in hatrac/uploader we decided to take a closer look at the current implementation. The following are the list of improvements that we should do:

- [ ] Add flow-control to file exists check.
- [ ] Add flow-control to job creation.
- [ ] Improve the progress logic to avoid looping over the files over and over again. 
- [ ] We might want to flatten the array of `uploadFile` objects too. Instead of the current two-dimension array that we have.
- [ ] Improve the chunk upload flow-control to keep track of pending/active/done requests.
- [ ] Calculate checksum for each of the chunks and send it with the chunk request.

**Comment by jrchudy** [comment]
For bullets 1 and 2:
 - Not sure if flow-control is necessary since the app will issue requests to the browser and the browser will manage sending the requests 
   - resume works in limited cases for file upload and properly queues/skips "file exists" and "job creation" steps
   
The rest are features we should still consider adding to file-upload.

**Comment by jrchudy** [comment]
Moving to wishlist wiki page
