### ISSUE TITLE
multi-edit doesn't show the file URI properly

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1755]
If you go to this page, you will see that there is no way for user to see the existing file URI. We should provide a way to visualize the value.. maybe when they hover over, the full URL should show up?  

https://www.gudmap.org/chaise/recordedit/#2/RNASeq:File/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM6JHQBcAjdafEAJQDkBBAZRwEcQAaEAMQEsAbHAPpUcAB17csYIoKoBJACICAZgGscATxABdAL5tQxMmgoJq9Jqw7CxEqYICiADxE4M3ALY4IRIQuVrNXSsFbQ4sAAsUCRwkSgBGADYAWgBhAHUAcXttHV0gA@sort(Replicate_RID::desc::,File_Type,RID)?limit=25

**Comment by RFSH** [comment]
The following is how Chrome and Safari show a simple file input given this html:

```html
<input type="file">
```


![](https://dev.isrd.isi.edu/~ashafaei/wiki-images/chaise-issue-1755-01.png)

As you can see by default the truncated filename is displayed and on hover, it will show the full filename. We might be able to replicate the same behavior. 

(I didn't mention Firefox because its UI is a bit different. The button says "Browse..." and it's not doing any truncation).

**Comment by jrchudy** [comment]
Some changes that have been merged into master with PR #1759 include:
 - tooltip on hover (currently only includes filename)
    - should it be extended to include filesize, md5, and sha256?
 - filename will be shown in edit mode, if the filename was stored in the database with the record
    - defaults to hatrac url if no filename is present

**Comment by jrchudy** [comment]
Some more changes discussed this morning to implement:
 - [ ] tooltip should include filesize as well
 - [ ] copy mode should try to copy all of the asset's data if present on other columns in the model

**Comment by jrchudy** [comment]
More changes have been made to handle the comments made in PR #1781 before it was merged into master.
