### ISSUE TITLE
Odd error handling behavior

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1762]
When the user is not logged in and navigates to a recordset page where they can't "see" a column that includes a valid facet filter, an error is thrown that _should_ suggest the user try logging in first before removing all filters from the url.

https://dev.gudmap.org/chaise/recordset/#2/Protocol:Protocol/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM6JHQBcAjdafEABQxSJSxQBsQAaa2+xpgfQGFMYIgEsUEHgGUiQtEh4AzANY4AniAC6AX3YAlAJIARDeywALFMNxJKARQC0ATQBsARh0bNWoA@sort(RMT::desc::,RID)

**Comment by RFSH** [comment]
We might want to add the same message that we are doing for table/column/schema/data not found to any of these url related errors too ("You may need to login to see the model or data. Please login to continue."). This requires change in ermrestjs too, since currently the error thrown when the facet string is completely invalid (and therefore cannot be decoded) is the same as this given case (when facet string is correct but the path is invalid).

**Comment by jrchudy** [comment]
Changes for this issue have been merged into master. Reassigning to @hongsudt . The link in the original description should be valid for testing this issue has been resolved.
