### ISSUE TITLE
viewer: incorporate the svg objects ontop of open-seadragon in the viewerapp

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1779]
Background:
* The viewer app replies on the open-seadragon repo. https://github.com/informatics-isi-edu/openseadragon-viewer. You can ask @lperman or @svoinea on how this component is deployed. @jrchudy might be able to help you as well since he briefly worked on the viewer app before. 
* The annotation (an area and an anatomical name) is done in the viewer app. There should be some code that allow you to render a rectangle in multi-zoom display. 

Test data
* Specimen: [Q-296R](https://www.gudmap.org/id/Q-296R) 
* czi file: https://www.gudmap.org/hatrac/resources/histological_images/2017/c8334e8d29b9261493d922fafc81350c?uinit=1&cid=record
* location to pyramid: /var/www/html/openseadragon-viewer/mview.html?url=/data/2017/c8334e8d29b9261493d922fafc81350c
* Sample svgs can be found on https://dev.gudmap.org/data/annotations/poc/Q-296R_all_contours_cw_named.svg on rbk-dev.  This svg corresponds to specimen Q-296R. 
* XML: https://dev.gudmap.org/data/annotations/poc/Q-296R_20160707-hKDCS19_133-JAM-0-30-000_all-contours.xml

Tasks: 
* Assume an svg input (or multiple svg files), make sure we can toggle the display of each annotation object. 
* Provide a navigation for users to turn on/off the overlay. 
* There should be a way to get from the overlay to the term, and vice versa.

**Comment by carlkesselman** [comment]
There seem to ba a number of ways to do this.  Should consider best approach.  Here is one:

https://bl.ocks.org/fabiovalse/71bbbd5c87a148f1c7fabc97b0bbc980

and
https://github.com/openseadragon/openseadragon/issues/1425


D3 is probably the most general way of doing this.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 9, 2019, at 4:17 PM, Hongsuda <notifications@github.com<mailto:notifications@github.com>> wrote:


Background:

  *   The viewer app replies on the open-seadragon repo. https://github.com/informatics-isi-edu/openseadragon-viewer. You can ask @lperman or @svoinea<https://github.com/svoinea> on how this component is deployed. @jrchudy<https://github.com/jrchudy> might be able to help you as well since he briefly worked on the viewer app before.
  *   The annotation (an area and an anatomical name) is done in the viewer app. There should be some code that allow you to render a rectangle in multi-zoom display.

Tasks:

  *   Assume an svg input (or multiple svg files), make sure we can toggle the display of each annotation object.
  *   Provide a navigation for users to turn on/off the overlay.
  *   There should be a way to get from the overlay to the term, and vice versa.

**Comment by iamyle0710** [comment]
The coordinates used in the XML file doesn't seem to match with one used in `openseadragon`. I was able to draw the contours, but unable to locate/resize them without knowing the coordinate system used in the file. It appears that the contours are meant for the third section from just visually matching them with the original image. 

* The drawn contours from the XML file
![image](https://user-images.githubusercontent.com/14816171/61331654-1eea7580-a7d7-11e9-9d26-64f9e377e73e.png)

* Third section of the image in `openseadragon`
![image](https://user-images.githubusercontent.com/14816171/61331679-3590cc80-a7d7-11e9-82cc-94a33f795374.png)
