### ISSUE TITLE
Make alphabetical ordering of columns optional

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#180]
Alphabetical ordering of the columns on the details page should be optional, and should be disabled by default. We can add a config parameter to the chaise config to enable the alphabetical column ordering.

**Comment by robes** [comment]
@karlcz : or do you think this should be an annotation on the table, to specify the ordering?

**Comment by karlcz** [comment]
I think the ordering should have a series of control points:

1. Global config setting for alphabetic vs. table orderered
2. Per-table annotation to override the global setting
3. Per-table annotation to override with a specific column order

I don't know that we need to implement the third option immediately,
but it would be a workaround for systems where it isn't practical to
restructure the table to have the preferred column order in SQL.

I'm also not sure if that third option should just be a table
annotation with a list of column names or some rank annotation on each
column.  Either case raises the complication of how to cope with
annotations which may be out of date or incomplete, i.e. some columns
not given a specific order.  A table-level list could also contain
names which are not actually columns, if annotation gets out of sync
with a table definition over time!  A column-level rank annotation
would avoid this inconsistency but of course some columns might lack
the annotation so the method still needs to handle sparse
instructions.

We should probably consider it something like a primary, secondary
sort order like:

1. Explicit rank if present, otherwise a minimum rank below all explicit ones
2. Alphabetic or table order depending on setting which comes from global and table-level as above

**Comment by robes** [comment]
Okay, thanks. I agree with that.

For the purpose of this github issue, let's just do:
1. Global config setting for alphabetic vs. table ordered

Which is essentially what I specified in the first comment.

**Comment by robes** [comment]
heh. okay, apparently we dont' sort the columns anyway. they are just presented in natural order returned from the catalog. we should revisit this sometime *if* we want to support sorting.
