### ISSUE TITLE
Add structured data to record pages

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1801]
What we want to do is provide an annotation that can be used in record pages (this is a row-level thing) to add metadata that will be recognized by Google Dataset Search. Google wants metadata in the form of a [schema.org Dataset](https://schema.org/Dataset) object in json-ld wrapped in a script tag. More information about the subset of Dataset that Google wants (and an example) can be found [here](https://developers.google.com/search/docs/data-types/dataset#Examples).

There are a couple ways of generating the json-ld. For pages that have datacite DOIs defined, datacite generates its own json-ld and [suggests we use that](https://support.datacite.org/docs/how-do-i-expose-my-datasets-to-google-dataset-search). This has the advantage of being relatively simple, but it means we'd have to fetch data from datacite every time we serve up one of these records, we'd need to use the chaise url instead of the resolver url, and if we decide to change something, metadata for existing records won't change until we change it in datacite.

The other option is to generate the metadata ourselves, which is significantly more involved but would give us more control. Here's a draft for an annotation that would take these arguments:

- NAME: mandatory, the name or title of the record
- DESCRIPTION: mandatory, a description of the record
- RELATED_PUBLICATION: optional - determines whether the "citation" element appears
- SERVER: optional (and probably only ever used in rbk/gudmap), the beginning part of urls on the site (e.g., "https://www.gudmap.org"), to be used when constructing resolver URLs
- KEYWORDS: optional, determines whether the "keywords" element appears.
- LICENSE: optional, determines whether the "license" element appears
- CREATOR_*: at least CREATOR_TYPE and CREATOR_NAME must be present for "creator" element to appear. CREATOR_TYPE must be either "Organization" or "Person".
- SITE_CATALOG: a reference to a DataCatalog object representing the site (e.g., facebase, gudmap)

And produce something like this:

```
<script type="application/ld+json">{
  "@context": "https://schema.org/",
  "@type": "Dataset",
  "url": SERVER_or_default/id/RID,
  "name": NAME,
  "description": DESCRIPTION,
  "citation": RELATED_PUBLICATION,
  "identifier":  [DOI or SERVER_or_default/id/RID],
  "keywords": [KEYWORDS],
  "license": LICENSE,
  "creator":{
     "@type": CREATOR_TYPE,
     "url": CREATOR_URL,
     "name":CREATOR_NAME,
     "contactPoint":{
        "@type": "ContactPoint",
        "email": CREATOR_EMAIL
     }
  },
  "includedInDataCatalog":{
     "@type":"DataCatalog",
     "name": SITE_CATALOG
  }
}
</script>
```

Note that the output would have to be valid json, so things like quotes in the arguments would need to be escaped.

Google has a syntax tester at https://search.google.com/structured-data/testing-tool?utm_campaign=devsite&utm_medium=jsonld&utm_source=dataset

I'd like to get comments from at least @robes, @hongsudt, and @carlkesselman before going any further.

**Comment by jrchudy** [comment]
[Link to wiki page](https://github.com/informatics-isi-edu/chaise/wiki/SEO) that was created based on our conversations with more relevant information.

**Comment by RFSH** [comment]
Based on my understanding so far,
- We want data-modelers to be able to define a JSON-LD that google expects.
- [JSON-LD can be inserted by Chaise](https://developers.google.com/search/docs/guides/generate-structured-data-with-javascript) based on instructions that will be encoded in annotation.
- Some properties might be data-dependent and therefore require pattern support. It seems like different type of JSON-LD can be used for record and recordset.
- We might want to add the JSON-LD only for certain records.

So the following are the steps that I think we should take to implement this:

- [ ] Find the required and optional attributes. Figure out the difference between `Dataset` and `DataCatalog`. Whether it makes sense to have this in recordset page or not.
- [ ] Finalize the list of attributes and structure that we want to include in chaise apps.
- [ ] To demonstrate how our annotation would work, map the attributes to an existing record in RBK. For example, lookin at this [record](https://dev.rebuildingakidney.org/chaise/record/#2/Common:Collection/RID=Q-3K5C), what are the attributes and how they will be used.
- [ ] Finalize the annotation:
  ```json
  "json-linked-data:2021": {
    "detailed": {
      "template_engine": "handlebars",
      "filter": {
        "and": [
          {
            "source": [{"outbound": ["Common", "Collection_Data_Provider_fkey"]}, "Abbreviation"],
            "choices": ["USC"]
          }
        ]
      },
      "definition": {
        "@context": "http://schema.org",
        "@type": "Dataset",
        "@id": "",
        "name": "",
        "url": "",
        "description": "{{{Description}}}",
        "datePublished": "",
        "dateModified": "",  
        "provider": "{{{$fkey_Common_Collection_Data_Provider_fkey.rowName}}}"
        ...
      }
    }

  }
  ```
  - What should be the name of the annotation?
  - Should we only allow a certain list of parameters?
  - Should we apply pattern to all the parameters?
  - We don't need to support filter now, it can be added later.

- [ ] Add an API for this to ERMrestJS that would return the `json-ld`:
  - There should be a new `Refernece.JSONLinkedData` API that behaves the same way as
    `Reference.citation` (minus the waitFor logic)
  - The `JSONLinkedData` API should validate the given schema.
  - Add a new spec to `specs/annotation/tests` called `08.json-linked-data.js` which
    would test this newly added API.
- [ ] Use the added API in Chaise.
  - Since we're not adding waitFor support for now, it could simply be added to
    `run` block of `record.app.js`.
  - (_needs more info_) Do we need automated testing?

- [ ] Define annotation in RBK or any other deployment that we want to test this new feature for

**Comment by carlkesselman** [comment]
A question.

Google expects that the names of attributes will come from schema.org.  Right now, we don’t have a way of associating identifiers with column names.  It seems to me that something we might want to have is a more structured connection between a column name and an ontology such as schema.org to make these mappings more direct.  I understand this is probably an ERMrest issue, not a chaise issue, but its something I’ve been thinking about for a while.

Carl

----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Professor, Ostrow School of Dentistry
Professor, Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  ***@***.***
Web: http://www.isi.edu/~carl
On Jun 3, 2021, 2:30 PM -0700, Aref Shafaei ***@***.***>, wrote:

Based on my understanding so far,

  *   We want data-modelers to be able to define a JSON-LD that google expects.
  *   JSON-LD can be inserted by Chaise<https://developers.google.com/search/docs/guides/generate-structured-data-with-javascript> based on instructions that will be encoded in annotation.
  *   Some properties might be data-dependent and therefore require pattern support. It seems like different type of JSON-LD can be used for record and recordset.
  *   We might want to add the JSON-LD only for certain records.

So the following are the steps that I think we should take to implement this:

  *    Find the required and optional attributes. Figure out the difference between Dataset and DataCatalog. Whether it makes sense to have this in recordset page or not.

  *    Finalize the list of attributes and structure that we want to include in chaise apps.

  *    To demonstrate how our annotation would work, map the attributes to an existing record in RBK. For example, lookin at this record<https://dev.rebuildingakidney.org/chaise/record/#2/Common:Collection/RID=Q-3K5C>, what are the attributes and how they will be used.

  *    Finalize the annotation:

"json-linked-data:2021": {
  "detailed": {
    "template_engine": "handlebars",
    "filter": {
      "and": [
        {
          "source": [{"outbound": ["Common", "Collection_Data_Provider_fkey"]}, "Abbreviation"],
          "choices": ["USC"]
        }
      ]
    },
    "definition": {
      ***@***.***": "http://schema.org",
      ***@***.***": "Dataset",
      ***@***.***": "",
      "name": "",
      "url": "",
      "description": "{{{Description}}}",
      "datePublished": "",
      "dateModified": "",
      "provider": "{{{$fkey_Common_Collection_Data_Provider_fkey.rowName}}}"
      ...
    }
  }

}

     *   What should be the name of the annotation?
     *   Should we only allow a certain list of parameters?
     *   Should we apply pattern to all the parameters?
     *   We don't need to support filter now, it can be added later.
  *    Add an API for this to ERMrestJS that would return the json-ld:

     *   There should be a new Refernece.JSONLinkedData API that behaves the same way as
Reference.citation (minus the waitFor logic)
     *   The JSONLinkedData API should validate the given schema.
     *   Add a new spec to specs/annotation/tests called 08.json-linked-data.js which
would test this newly added API.
  *    Use the added API in Chaise.

     *   Since we're not adding waitFor support for now, it could simply be added to
run block of record.app.js.
     *   (needs more info) Do we need automated testing?
  *    Define annotation in RBK or any other deployment that we want to test this new feature for

**Comment by kpherwan** [comment]
While testing on Google rich results test, we can see many resources getting partially loaded, need to investigate further on how we can fix this. Example tests - 

https://search.google.com/test/rich-results?view=fetch-info&id=Iwra_lwMenPWYbl8Io6KRw
https://search.google.com/test/rich-results?view=fetch-info&id=iofPoZPgqVpU54QHxwQh1A
https://search.google.com/test/rich-results?view=fetch-info&id=TVeNn-qVEd6Z3ckiEiA77g
https://search.google.com/test/rich-results?view=fetch-info&id=9-vnOC-Iy-QUtUR9DtP0ZA
https://search.google.com/test/rich-results?view=fetch-info&id=ij2rYah3sNNaNCeYj75hTg

**Comment by robes** [comment]
Thanks that’s interesting. We should tune the robots.txt on facebase so that we don’t block the genesummaries images. In general, we are disallowing hatrac so that Googlebot doesn’t crawl the data files. But genesummary picture would be useful to let google crawl.

On 6/10/21, 5:34 PM, "Karishma Pherwani" ***@***.******@***.***>> wrote:


While testing on Google rich results test, we can see many resources getting partially loaded, need to investigate further on how we can fix this. Example tests -

https://search.google.com/test/rich-results?view=fetch-info&id=Iwra_lwMenPWYbl8Io6KRw
https://search.google.com/test/rich-results?view=fetch-info&id=iofPoZPgqVpU54QHxwQh1A
https://search.google.com/test/rich-results?view=fetch-info&id=TVeNn-qVEd6Z3ckiEiA77g
https://search.google.com/test/rich-results?view=fetch-info&id=9-vnOC-Iy-QUtUR9DtP0ZA
https://search.google.com/test/rich-results?view=fetch-info&id=ij2rYah3sNNaNCeYj75hTg

**Comment by kpherwan** [comment]
Adding the progress and blocker so far:

- Completed the development for the annotation in ermrestjs and chaise that would generate the metadata and append it to the DOM

- For the task of validation of the JSON-LD, there is a weird situation. There are a lot of UI tools to validate the JSON-LD like https://search.google.com/structured-data/testing-tool https://search.google.com/test/rich-results https://validator.schema.org/ but no popular or established solution to do it programmatically before appending it to the DOM.

Google Search Console provides a report for all the pages https://developers.google.com/search/blog/2019/05/monitoring-structured-data-with-search-console?hl=en but that would be a way of cure rather than prevention as it would flag after those pages are published with the metadata.

There are some repos out there that have some similarities to what we need and I am in the process of exploring those -

Relevant URLs-
https://github.com/schemaorg/schemaorg/issues/2790

https://github.com/google/schemarama

https://github.com/semantifyit/sdo-check

https://github.com/google/schema-dts (for TypeScript)
https://www.npmjs.com/package/schema-dts

https://github.com/mulesoft-labs/json-ld-schema

**Comment by RFSH** [comment]
Based on the conversation that we had, we want to stick with the [vocabularies provided by the Schema.org](https://github.com/schemaorg/schemaorg/tree/main/data/releases/12.0). But since these definitions are huge, we want to extract a subset of the vocabulary and only have the ones that are related to `Dataset`.

This process must be reproducible and doesn't really have to be done in JavaScript. Whenever Schema.org releases a new version that we want to support, we would just have to run the extraction script without any change in the Chaise/ERMrestJS code. The following is an example that @karlcz provided demonstrating how we can achieve this in Python using `rdflib` package:

> Karlcz: This is an example to process the schema.org definition and dump all properties defined for schema:Dataset and supertypes, using the Python rdflib package:

```python
import rdflib
# load schema.org turtle download into a graph
g = rdflib.Graph()
g.parse("schemaorg-current-https.ttl", format="n3")
# query the graph
result = g.query("""
SELECT DISTINCT ?label ?prop ?dtype ?rtype
WHERE {
  schema:Dataset rdfs:subClassOf* ?dtype .
  ?prop a rdf:Property .
  ?prop schema:domainIncludes ?dtype .
  ?prop rdfs:label ?label .
  ?prop schema:rangeIncludes ?rtype .
}
""")
prop_labels = {}
prop_dtypes = {}
prop_rtypes = {}
for label, prop, dtype, rtype in result:
    prop_labels.setdefault(prop, set()).add(str(label))
    prop_dtypes.setdefault(prop, set()).add(str(dtype))
    prop_rtypes.setdefault(prop, set()).add(str(rtype))
for prop in prop_labels:
    print("prop=%s\nlabels=%s\ndtyes=%s\nrtypes=%s\n\n" % (
        prop,
        prop_labels[prop],
        prop_dtypes[prop],
        prop_rtypes[prop]
```

> Karlcz: That's pretty standard SPARQL inside the python string literal `""" ... """`  so you may be able to use that in any other SPARQL processor you try.  it does depend on the path syntax to have that `*` operator for zero-or-more `rdfs:subClassOf` relationships.

> Hongsuda: In our case, we probably need to explore `schema:rangeIncludes` as well for data type.

**Comment by kpherwan** [comment]
Draft of gudmap.org DataCatalog jsonld -

```
{
    "@context": "http://schema.org",
    "@type": "DataCatalog",
    "url": "https://www.gudmap.org/",
    "license": "https://creativecommons.org/licenses/by/4.0/",
    "name": "GUDMAP/RBK",
    "description": "The GenitoUrinary Development Molecular Anatomy Project (GUDMAP) provides data and tools that facilitate research on the GenitoUrinary (GU) tract for the scientific and medical community.",
     "publisher": {
        "@type": "Organization",
        "name": "GUDMAP (www.gudmap.org) and (Re)building a Kidney (www.rebuildingakidney.org)"
      },
    "funder": 
     {
       "@type": "Organization",
       "name": "National Institute of Health (NIH)"
    },
    "hasPart": ["The URLs of each smaller DataCatalog within this DataCatalog collection."],
    "dataset": [{"name": "dummy", "description": "lorem ipsum"}], //can be skipped if we don't want to point to any record pages
    "datePublished": "2017",
    "keywords": ["kidney", "GenitoUrinary", "Imaging", "Transcriptomic"]
}
```

<img width="1438" alt="Screen Shot 2021-06-15 at 6 26 37 PM" src="https://user-images.githubusercontent.com/78573171/122143958-59b41880-ce07-11eb-8587-980d02c01825.png">

Schema - https://schema.org/DataCatalog
Validator - https://validator.schema.org/

URL that has DataCatalog JSON-LD in head tag for Gudmap - https://registry.identifiers.org/registry/gudmap#!

**Comment by kpherwan** [comment]
Since templates are written in a string and produce a string, the annotation for Google Dataset would not be able to support the non-string types out of the box, below are all the types and their status of being accepted and transformed by Google from string to the desired type.

| Type       | Is String format accepted  |
| ----------- | ----------- |
| URL      | Yes       |
| Date/DateTime   | Yes        |
| Number/Integer   | Yes (Validation tool doesn't show a marked difference between primitive and string)        |
| Boolean   | Yes        |
| Array of Primitives  | No        |
| Object   | No        |
| Array of Objects  | No        |

**Comment by RFSH** [comment]
We had a discussion regarding how we might want to support arrays. The issue is that our templating engine accepts a string as input and returns another string. And based on the previous comment by @kpherwan we cannot just pass an array-like string and expect it to work the same as array.

For instance, let's assume `key_words` is an array column in the table (with the value of `["one", "two"]`). We could write an array-like string this way (notice how we have to add double quote and escape it):
```json
{
  "keywords":  "[{{#each _key_words}}\"{{{this}}}\"{{#unless @last}}, {{/unless}}{{/each}}]"
}
```
Which result in:
```json
{
  "keywords":  "[\"one\", \"two\"]"
}
```

Running this string by `JSON.parse` function would give us the array object that we want. Since this would be a new mode and we don't want the other patterns to be affected, we should come up with a way to mark this specific pattern as an object (to signal that we want it to be parsed.) Based on our discussion, we came up with the following ways to do this:

**1. We could have a new flag alongside `template_engine` to signal this (we didn't agree on a name but let's use `parse_as_json` for now.)**
  - Pros: Straight-forward. Easy to implement and understand. 
  - Cons: Since `template_engine` is a top-level property in this new annotation, then every string value in the `dataset` will be treated the same, and we have to make extra changes to all the template values in this annotation based on that. For instance let's assume we have the following:
    ```json
    {
      "keywords":  "[{{#each _key_words}}\"{{{this}}}\"{{#unless @last}}, {{/unless}}{{/each}}]",
      "description": "{{{Description}}}"
    }
    ```
    We have to add the `parse_as_json` for `keywords`, but by doing so, then the existing value for `description` is an invalid JSON and we have to wrap it in double quotes as well. And since most of the properties are like `description`, we would have to make a lot of unnecessary changes for just a few properties that we want to treat as object.

**2. For this `dataset` annotation specifically, we could come up with a prefix/suffix to signal that the property should be treated as JSON. For example instead of using `keywords` we have to say `keywords_parse_as_json` in the example above.**
  - Pros: Limited to only the properties that we want to treat specifically without the need to change anything else.
  - Cons: To avoid clashing with existing propreties we have to come up with a proper name, and also a way to "escape" names. This solution also only works in this specific annotation.

**3. (_Requires more research_) We might be able to create a helper function in handlebars to signal the output type.** Assuming that's possible, the above example would look like this:
  ```json
  {
    "keywords":  "{{#parse_as_json}}[{{#each _key_words}}\"{{{this}}}\"{{#unless @last}}, {{/unless}}{{/each}}]{{/parse_as_json}}"
  }
  ```
  - Pros: Self contained to the template, and can be used in other places as well. 
  - Cons: Not sure if this is even possible.

**Comment by RFSH** [comment]
GUDMAP was the first deployment that used this annotation and we did an experiment based on those annotations. You can find more information about the experiment in [here](https://github.com/informatics-isi-edu/chaise/wiki/SEO-Experiment).
