### ISSUE TITLE
Missing eyes after multi-add

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1804]
If I use multi-add to add two related records, the result page shows the created records without the View/Edit/Delete controls. For example, if you:

1. Go to https://dev.gudmap.org/id/W-RCE4
2. Scroll down to "Cluster Group" and click "add"
3. Click the "+" in the resulting Create window.
4. Type two unique names in the "Cluster Group Name" fields
5. Hit "Submit"

then you'll get something like:

![image](https://user-images.githubusercontent.com/8785501/59895425-6d078700-9399-11e9-8130-4ac784e8ece6.png)

**Comment by karlcz** [comment]
I think this is as-designed. We do not redirect but instead directly
render the POST /entity/ API's response.  This is rendered in the
recordedit app and uses a more primitive presentation template since
the response data is not as rich as expected by our normal recordset
presentation.

For single create, we can redirect to the regular record page for the
new record and give a fully enriched presentation.

For multi-create, we had a corner case to worry about: we get back a
potentially long list of new record keys and it would be impossible to
form an equivalent recordset query to view that set (because the URL
would be too long when encoding the filter criteria w/ all the new
keys).

However, it occurs to me that we could revisit this now for catalogs
with history-tracking on tables with system columns. We could
determine the new records' RCT value, say `T0`, and we can assume the
filter `RCT=T0` will return only the newly created records in that
table.

The only risk with this approach is that under a perverse
race-condition or policy environment, the query might return a subset
of the created records still visible to the client.  We could only
determine this by doing a counting aggregate for the filter and
comparing that to the size of the original POST /entity/ response.

**Comment by ljpearlman** [comment]
When I described this to @hongsudt, she told me it shouldn't happen! Anyway, I think it would make sense to do something like what you suggested.

**Comment by jrchudy** [comment]
What @karlcz mentioned above is the initial design and intention for that page. This page was designed that way exactly because of the data that is returned in the response object. It would get really messy trying to define a recordset url with a proper filter set for "X" number of created records. 

You will notice that the url still includes `recordedit`. This is an intermediary page to provide as much info as we can so the user is made aware of what was successfully created (and what wasn't). This page will also show a 2nd table of rows that couldn't be created for whatever reason.

I agree with the last part as well. There can be more enhancements made to this workflow to give better (or more appropriate) navigation options to the user after multi-create.
