### ISSUE TITLE
Images disappear in recordset in one specific case

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1805]
Try this:

1. Go to https://www.gudmap.org/chaise/recordset/#2/RNASeq:Visualization

2. Look at the first four rows -- they're for gene "A1BG", and each has an image in the "Reference Image" column.

3. In the facet panel, under Gene, click on "A1BG". This should show the same content as those first four rows, but for me in Firefox, Chrome, and Safari, the "Reference Image" images are missing.

4. In a new window or tab, go to https://www.gudmap.org/chaise/recordset/#2/RNASeq:Visualization/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM6JHQBcAjdafEAJQDkBBAZRwEcQAaEANQEsk0wANtwBeYItxQQA+jQDCAIQCSUgOI4IORQBEpAMwDWOAJ4gAugF8OVbWY5YAFim64klAIoBaAMwBpACoATGbmFkA@sort(NCBI_GeneID,RID)
(or just cut and paste the URL from the URL bar in your browser). This is the same faceted search as in the previous step, but now the images are visible again.

**Comment by RFSH** [comment]
This bug has been introduced with the changes in [this PR](https://github.com/informatics-isi-edu/ermrestjs/pull/765). The bug is only limited to the output of `markdown_pattern`s that are defined directly in the source syntax. It didn’t have any effect on the other parts of the code and was only limited to the new feature that I’ve added. 

If you had multiple columns that had `display` settings in their definition, chaise would use the wrong `display` settings for the columns because of a referencing issue in ermrestjs.

[This commit in ermrestjs](https://github.com/informatics-isi-edu/ermrestjs/commit/556fcb1a31043838d6942840456d0f7b674fddb1) fixes this issue. I also added [new test scenarios](https://github.com/informatics-isi-edu/chaise/commit/2e21f04bf4fa56bc4419c481b96b0059dfdb6712) for this in chaise.

Assigning to @ljpearlman for verification.

**Comment by ljpearlman** [comment]
That fixes it, thanks!
