### ISSUE TITLE
Provide option to display descriptive information 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1842]
In some cases, explicitly displaying more descriptive information about the tables/fks will make it easier for users to follow. This is particularly useful for tables or related tables. The info can be table/fk comments or annotation that overwrite the table/fk comments.  
 
This issue is related to #1120.

**Comment by jrchudy** [comment]
@RFSH  stated the following in a related issue:
> For annotation, we can reuse the table-display annotation or add a new attribute to the source-syntax that is only available in case of visible-foreign-keys (related tables).

I don't think this should be a new annotation but a modification to a previous one. We would want the attribute name to be more specific to what it's labeling, rather than just being "comment". Maybe something like `subheader-comment`?

**Comment by jrchudy** [comment]
I think we want this to be a markdown pattern (`comment_markdown_pattern`) because it could be defined to use content for the table rather than just a static string (maybe there isn't a use case for that though). 

1. As an attribute for `table-display` annotation:
    ```json
    "tag:isrd.isi.edu,2016:table-display": {
      "compact/brief" : {
        "hide_column_headers": ...,
        "row_markdown_pattern": ...,
        "row_order": ...,
        "comment_markdown_pattern": <markdown-pattern>,
        "page_size": ...
      }
    }
    ```
    - could enforce that `comment_markdown_pattern` only shows in this context and subcontexts

2. As an attribute for source syntax in `visible-foreign-keys` annotation:
    ```json
    "tag:isrd.isi.edu,2016:visible-foreign-keys": {
      "detailed": {
        [
          {
            "source": ...,
            "markdown_name": ...,
            "display": { ... },
            "comment": ..., // default comment for table name tooltip
            "comment_markdown_pattern": <markdown-pattern>,
            ...
          }
        ]
      }
    }
    ```

**Comment by RFSH** [comment]
@jrchudy I recently added `comment` to [display annotation](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2015-display). I think this annotation would be a better place for this new attribute than `table-display`. `table-display` is mainly used for data-level annotations.

When we were discussing this, I remember we said we want the same kind of capabilities for normal columns (in record and recordedit) as well. I remember we talked about just adding a flag that signals whether we should show the comment as a tooltip, or below the column (in this case table). Isn't this something that we want to do here as well? or do we want a completely different definition? (if we move this to `display` annotation, then this definition will be identical for table and columns)

If we want to add a new attribute, I suggest naming it differently so it's more differentiated from the `comment`. `comment_markdown_pattern` might be misleading as the name suggests that it will behave exactly like a comment but it has markdown and pattern. Besides this annotation cannot be a pattern since it should be general for the table and cannot be based on the values.

**Comment by RFSH** [comment]
By the way, I noticed that we're not showing any tooltip for related tables. Shouldn't we add tooltip to related tables? or are we going to add only this new "descriptive information"?

**Comment by jrchudy** [comment]
From further discussions we have had, the change is going to be made to the `tag:misd.isi.edu,2015:display` annotation. The changes to the annotation will only be supported for columns and foreign key relationships. The intention is to add extra information that describes a column's purpose further with an inline comment that users will see. 

This could be used for any column, but first we want to make sure support works in the case of pseudo-columns and other foreign key relationships. One could consider implementing this at the table level for the cases with foreign key relationships, but that information may not want to be displayed when that table is viewed (single records from that table). The descriptive info would only be displayed when it is used as part of a foreign key relationship (if we attached it to table).

There were 2 different ways we discussed this being implemented, as a separate comment from the already existing comment and as a way to override the existing comment.
#### New attribute:
 - If we decide to have it exist alongside the existing comment from the column, it simplifies the possible scenarios for where and when the "new comment" would be shown. This new property would then be defined only when a more descriptive comment would be shown.

#### Existing attribute:
 - One could also imagine defining this new property as a way to override the default table or column comment with another property added as a flag for when the comment should show in the descriptive text location. Basically we would be adding an attribute to trigger showing the current comment as the descriptive text.

Adding this to the display annotation means we should also add this support to the display property of the visible columns annotation for both detailed and entry. As well as for the visible foreign keys annotation (which applies to record app). This will allow data modelers to define this for a single relationship as needed rather than everywhere the column is seen.

**Comment by RFSH** [comment]
Based on the discussion that @hongsudt  and I had, we decided that we should show tooltips for related entities. This requires both ermrestjs and chaise changes since we might want to change where this `comment` comes from. Currently, it's going to return the `comment` defined on the leaf table. But it should at least use the `comment` defined in the source-definition (and maybe the foreign key comment).

While we're thinking about this, we should also review the `comment` heuristics for the inline related tables. The heuristics are using the `comment` defined in the source-definition, and if it's missing, it's using the leaf table's comment. We might want to add an extra step in between to use the foreign key comment instead.

**Comment by hongsudt** [comment]
Instead of "descriptive_comment" what about "show_comment" or "explicit_comment"?

**Comment by RFSH** [comment]
The following is how the new attribute should look like in different annotations that we define `comment` on:

```javascript
"2015:display": {
  "comment": {
    "context": "comment value"
  },
  "comment_display": {
    "context": {
      "table_comment":  "tooltip|inline",
      "column_comment": ""
    }
  }
},

"tag:isrd.isi.edu,2016:foreign-key": {
   "from_comment": "",
   "to_comment": "",
    "display": {
      "*": {
        "from_comment_display": "tooltip|inline",
        "to_comment_display": "tooltip|inline"
      }
   }
}

"tag:isrd.isi.edu,2016:visible-columns": {
   "*": [
     {"source": "id", "comment": "", "comment_display": "inline|tooltip"}
   ]
}
```

**Comment by jrchudy** [comment]
The following is what we have for heuristics for each of the options for the display annotation.
### comment:
 - false for no tooltips
   - what if `comment_display` is also defined?
   - `comment_display` should override
 - does not apply to any other element but the one annotated

### name:
 - in place of model element `name`
markdown_name:
 - in place of `display.name` or model element `name` if above `display.name` is undefined

### name_style:
 - applies only to model element `name`
 - applies to any nested elements
   - Column-level name
   - Column-level name_style.
   - Table-level name_style.
   - Schema-level name_style.

### show_null:
 - inherited to each nested element below 
   - catalog -> schema -> table -> column
 - inherited for contexts
   - "*" -> "compact" -> "compact/brief"
 - anything defined on a more specific model element or context overrides anything inherited

### show_foreign_key_link:
 - treated the same as show_null

NOTE: For all properties with inheritance, explicitly setting `null` will turn off inheritance


For `comment_display`, we need to define what the heuristics should be for inheritance. We have 2 types of inheritance listed above, between the model elements and between the contexts. We  don't care about between model elements in this case since that won't make sense. We want the inheritance to occur at the context level.

Since context will now apply to `comment` too, we have to decide how to handle the inheritance. **Does it make sense to set a global `comment` or `comment_display` on the `"*"` context that can be inherited across contexts?** 

I think yes. This would allow for it to be defined once for all contexts, or once for compact and all sub contexts like the popup dialog and the related tables in record app.

**What if there is an annotation defined but it is null?** Ignore and use the default comment from the model element.

**How should comment be handled as an inline related table?** Not sure about this case, maybe only show when the table is visible and hide when showing the custom display mode?

**How should comment be handled for Related Tables section?** Both `comment` and `comment_display` should follow inheritance and inherit from `"*" -> "compact" -> "compact/brief"`.

**How should comment be handled for Pure and Binary popup?** This should be inherited from compact if it's defined. This should be shown as part of the page title, but under it the same way we decide to show it for `recordset` under the title.

**Comment by jrchudy** [comment]
# Foreign Key annotation changes
```
"tag:isrd.isi.edu,2016:foreign-key": {
  "display": {
    "context": {
      "from_comment": "",
      "to_comment": "",
      "from_comment_display": "tooltip|inline",
      "to_comment_display": "tooltip|inline"
    }
}
```

## Related Tables section
#### How will `comment` for **Related Tables** be chosen?
 - `comment` from source definition in `visible-foreign-keys` annotation
 - next look at `display` property of `foreign-key` annotation
   - if simple inbound, use `from_comment` from annotation
   - if pure and binary, use `to_comment` from annotation on FK relationship from association table to related table
 - `comment` defined on related table model

NOTE: If no `comment`, then nothing will be used for the tooltip or inline display.

#### How will `comment_display` for **Related Tables** be chosen?
 - `comment_display` from source definition in `visible-foreign-keys` annotation
 - next look at `display` property of `foreign-key` annotation
   - if simple inbound, use `from_comment_display` from annotation
   - if pure and binary, use `to_comment_display` from annotation on FK relationship from association table to related table

NOTE: If no `comment_display`, default to showing the comment as a tooltip, if comment exists based on above rules.


## Inline Related Tables
#### How will `comment` for **Inline Tables** be chosen?
 - `comment` from source definition in `visible-columns` annotation
 - next look at `display` property of `foreign-key` annotation
   - if simple inbound, use `from_comment` from annotation
   - if pure and binary, use `to_comment` from annotation on FK relationship from association table to related table
 - `comment` defined on related table model

NOTE: If no `comment`, then nothing will be used for the tooltip or inline display.

#### How will `comment_display` for **Inline Tables** be chosen?
 - `comment_display` from source definition in `visible-columns` annotation
 - next look at `display` property of `foreign-key` annotation
   - if simple inbound, use `from_comment_display` from annotation
   - if pure and binary, use `to_comment_display` from annotation on FK relationship from association table to related table

NOTE: If no `comment_display`, default to showing the comment as a tooltip, if comment exists based on above rules.

# Display annotation changes
```
"tag:misd.isi.edu,2015:display": {
  "comment": {
    "context": "comment value"
  }
  "comment_display": {
    "context": {
         "table_comment_display": "tooltip|inline",
         "column_comment_display": "tooltip|inline"
     }
  }
}
```

#### How will `comment` for **Table** be chosen?
 - `comment` from `display` annotation
 - `comment` defined on related table model

NOTE: If no `comment`, then nothing will be used for the tooltip or inline display.

#### How will `comment_display` for **Table** be chosen?
 - `comment_display` from `display` annotation

**Comment by jrchudy** [comment]
|                                   | comment | comment_display |
|---------------------|-----------|------------------|
| simple related table | source syntax -> `from_comment` from `foreign-key` annotation -> `display` annotation on leaf table -> leaf table model `comment` | source syntax -> if `from_comment` from `foreign-key` annotation is used, use `from_comment_display` or default value of `tooltip` -> if `comment` from `display` annotation is used, use `comment_display` or default value of `tooltip` |
| pure and binary        | source syntax -> `to_comment` from `foreign-key` annotation -> `display` annotation on leaf table -> leaf table model `comment` | source syntax -> if `to_comment` is used, use `from_comment_display` or default value of `tooltip` -> if `comment` from `display` annotation is used, use `comment_display` or default value of `tooltip` |
| multi hop                  | source syntax -> `display` annotation on leaf table -> leaf table model `comment` | source syntax -> if `comment` from `display` annotation is used, use `comment_display` or default value of `tooltip` |

### simple related table
#### comment
 - source syntax
 - `from_comment` from `foreign-key` annotation
 - `display` annotation on leaf table
 - leaf table model `comment`

#### comment_display
 - source syntax 
 - if `from_comment` from `foreign-key` annotation is used, use `from_comment_display` or default value of `tooltip` 
 - if `comment` from `display` annotation is used, use `comment_display` or default value of `tooltip` 

### pure and binary
#### comment
 - source syntax
 - `to_comment` from `foreign-key` annotation
 - `display` annotation on leaf table
 - leaf table model `comment`

#### comment_display
 - source syntax
 - if `to_comment` is used, use `from_comment_display` or default value of `tooltip`
 - if `comment` from `display` annotation is used, use `comment_display` or default value of `tooltip`

### multi hop
#### comment
 - source syntax
 - `display` annotation on leaf table
 - leaf table model `comment`

#### comment_display
 - source syntax
 - if `comment` from `display` annotation is used, use `comment_display` or default value of `tooltip`

**Comment by jrchudy** [comment]
- [ ] `comment` and `comment_display` for inline and related tables in record app
 - [ ] `column_comment_display` property for controlling the display of tooltips for columns
 - [ ] inheritance from `display` annotation defined on schema

**Comment by jrchudy** [comment]
The 2 connected PRs have been merged to support inline comments for related tables in record app. The changes included use the heuristics defined above for displaying the inline comments from source syntax, foreign key annotation, table display annotation, and finally the model itself.

**Comment by jrchudy** [comment]
Moving this issue back to "This Month" since more work needs to be completed at a later date according to [this comment](https://github.com/informatics-isi-edu/chaise/issues/1842#issuecomment-653107751).

**Comment by RFSH** [comment]
After applying the recent changes in rbk/gudmap, @hongsudt mentioned that supporting markdown in the comment value would be very useful (especially when it's displayed inline.)

There are two ways to do this:
- Start treating the comment value as markdown. This means that even the comments in the model will be treated as markdown values.
- Add a new `markdown_comment` (same as `markdown_name`) to explicitly signal chaise/ermrestjs about the type of comment that we want.

**Comment by RFSH** [comment]
The only feature that is missing from what was described in the comments above is " inline comments for recordset popups, `compact/select` context".

I'm going to close this issue. If we would like to implement inline comments in other places in chaise, we should create new issues.
