### ISSUE TITLE
chaise may not work in an iframe

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1856]
It gets a terminal error on `localStorage is null`.

<img width="1717" alt="Screen Shot 2019-10-02 at 1 58 31 PM" src="https://user-images.githubusercontent.com/4202842/66081653-40791480-e51d-11e9-899b-e9f4efb5cb4a.png">

**Comment by RFSH** [comment]
@robes 
I created this very simple page to test accessing iframe from other domains:

https://dev.isrd.isi.edu/~ashafaei/iframe.html

As you can see it shows the iframe from dev.facebase, facebase, dev.rbk, and rbk without throwing any errors.

Based on the error it seems like the `window.localStorage` API is not available in your case. I can think of the following as cause of this error:

- The storage setting in the browser is off. But this should not be the case since I'm assuming that you can access chaise without any issues. 

- You're accessing facebase from an origin that is not trusted by facebase. And browser is turning off the `localStorage` API to avoid this cross-origin access.

**Comment by robes** [comment]
Did you test with FF? I opened your page in FF and all iframes show the same `localStorage is null` error and if I open in Safar they all display correctly. I can’t think of any restrictive settings in my FF, but it does wipe its history clear on each restart of FF. That’s all.

**Comment by robes** [comment]
OK. Here we go. I did have these (see attached screen shot, hopefully) Custom Content Blocking rules et. Maybe it was the blocking of “Cookies from unvisited websites”? I guess you could just close this. Not sure what we can or should do about it.

Thanks for setting up the test page!!


[cid:image001.png@01D579DC.8096A520]

**Comment by karlcz** [comment]
I can reproduce on Firefox by setting a custom block policy to block "all third-party cookies" (a setting advertised right in Firefox as likely to break sites).

With the default "standard" blocking level, I do not see errors.

**Comment by RFSH** [comment]
The only feature that currently relies on `localStorage` is the warning message that we show to inform users that their session has been expired. So chaise can function without `localStorage`. Therefore I added a check to storage service to make sure `localStorage` API is available before using it. Chaise will not throw terminal error anymore and instead will print the following in the console

```
localStorage is disabled by the browser settings. Some features might not work as expected
```

@robes Can you please review and verify the new behavior?

**Comment by robes** [comment]
Yes, it worked for me. I tested with Firefox in Strict mode. Thanks
