### ISSUE TITLE
Edit buttons are active in generated pure/binary association tables in the record related-tables section

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1862]
In RBK/GUDMAP, we have a pure and binary association table called Gene_Expression:Specimen_Gene_Association that's annotated with

```
{
  "tag:isrd.isi.edu,2016:generated": null
}
```

The recordset page for this table (https://dev.gudmap.org/chaise/recordset/#2/Gene_Expression:Specimen_Gene_Association) correctly omits the edit button, but if you go to a Gene page (e.g., https://dev.gudmap.org/id/Q-4HFY) and scroll to the Specimens section, you'll find that each row has an edit button that attempts to open a recordedit button on the corresponding entry in Specimen_Gene_Association (which will fail because of permissions on that association table).

**Comment by RFSH** [comment]
In the case of pure and binary related tables, the "edit" button opens a recordedit page of the association table, which is different from the normal related tables that redirect users to the related table itself. And now this bug is caused because we're checking the permissions on the related table and not the association table. I'm going to fix this as part of the #1889.

**Comment by ljpearlman** [comment]
This fix will also resolve #1863

**Comment by RFSH** [comment]
I am going to close this issue and we should continue the discussion on #1863.
