### ISSUE TITLE
show_nulls true is not honored in record page

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1865]
By default record page is hiding all the columns with `null` value. Setting the `show_nulls` to `true` for any of the columns is supposed to override this heuristics and instead show the null value.

ermrestjs will send `null` if we're not supposed to show the null value (otherwise it will return empty string). And in chaise we used to check for `null` and if the value wasn't `null` we would show the column. So in case of `"show_nulls": true` you could see the column name without any value.

But it seems like [when I added pseudo-column support to record page](https://github.com/informatics-isi-edu/chaise/commit/a7a80fee101d4e87ef7ebde562f15ed2b4dcb217) I changed the condition without considering `show_nulls`. 

We should fix this. But what should be the expected behavior? Should we show empty column value like we used to? or should we use the special "_No Value_" display?

**Comment by jrchudy** [comment]
When showing inline related tables that have no related entities, we are currently showing the text _`None`_ . This text should be consistent with what we decide to show for columns that are marked with `"show_nulls": true`.

**Comment by jrchudy** [comment]
In [annotation.md](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2015-display), we have defined the value for `show_null` as the following:
> Supported JSON nshow patterns:
> - true (or ""): Show NULL values as an empty field.
> - " _marker_ " (a quoted string literal): For any string literal marker, display the marker text value in place of NULLs.
> - false: Completely eliminate the field if feasible in the presentation.

Issue #519 was created to track this feature when we designed it in 2016. This was originally designed to support simple column definitions and we later expanded the support to aggregates when we introduced pseudo-columns. 

When first designed, the intention was to show an empty value field next to the column label (record app). This was to allow for a way to communicate to the user that there's a field that could have data but that data is missing. We later added support for _No Value_ and _Empty_ in the faceting panel to communicate some of the column data that users weren't seeing before or couldn't search on (#1276).

This brought up a discussion about doing this in the facet pop up modal after clicking show more (#1379). Since then we have added aggregate pseudo-columns and inline related tables to `record` app. With those additions, we never spec'ed out a consistent way of displaying "null or empty" content in `record` app based on the `show_null` annotation (#1844). 


#### In summation
We initially added the modification to the display annotation with the intention of allowing for the ability to show an empty input field, while giving the data modeler the option of defining a value to display instead. 

For the cases outlined for `record` app, I think we want to be conscious of this decision (showing no column/value unless the data modeler explicitly states so in the display annotation). This strategy should be the same for each "visible column" (column value, aggregate value, inline related table in custom display mode, and composite display values). This decision is about how to consistently show/hide null/empty column values, not what the value should be if the column is shown.

**NOTE**: For composite display values, if the value of any of the columns which are being used in the markdown_pattern are either null or empty, then the pattern will fall back on the show_nulls display annotation to return respective value.


A second decision to make is about the actual values to display. The annotation was modified with the intention of giving the data modeler control over the display value, with the default being an empty value field when `"show_nulls": true`. We could continue to do this for record app and show an empty value field for each column type unless the data modeler specifies otherwise.

**NOTE**: Given the above 2nd decision I proposed, an inconsistency can be seen between the recordset app and record app (in faceting panel and show more popup vs the main entity section).

If we decide to change this definition to show default text instead, then we need to decide on a consistent way to display this content in record app. For each type, this is what I'm proposing:
 - regular column where value = :
   - `null` => `No Value`
   - `''` => `Empty`
 - aggregate column where value = :
   - `null` => `No Value`
   - `[]` => `Empty`
 - inline related table where value = :
   - `null`... can't have "null" as a value
   - `[]` = > `Empty`
- composite display where value = :
   - both (or all) values are `null` => `No Value`
   - one is `null` => `No Value`


There are a few special cases where the data returned is an "empty string" or an "empty set". Do we want to handle this differently? Will the users understand the difference if it is presented that way? Is that important to communicate?

**Comment by RFSH** [comment]
Instead of honoring the `show_nulls` annotation, we decided to honor the "Show/hide empty sections" button for column directives that rely on a secondary request (aggregate, etc).
