### ISSUE TITLE
Versioned "share" links are broken

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1877]
Whenever I go to a record page on one of our dev servers and click on the "Versioned Link" from the "Share and Cite" button, I get this error:

```
Invalid Input
Given catalog object is not the same catalog used in the url. You may need to login to see the model or data. Please login to continue.
```

I'm pretty sure this will happen on any record page, but an example of one I've tried is https://dev.facebase.org/id/1-4ZW6. I'm also pretty sure this was working two weeks ago.

Note: for this issue, it's probably better to test somewhere other than rbk-dev, since rbk-dev is currently running on a non-master ermrest branch.

**Comment by RFSH** [comment]
This is because of a recent change that I made in ermrestjs. This should be fixed with [the recent commit in ermrestjs](https://github.com/informatics-isi-edu/ermrestjs/commit/89faac5be403e1b673509de95f5f9b55dca50c8a). The following versioned link is working now:

https://dev.facebase.org/id/1-4ZW6@2SG-NYW0-BNPW

@ljpearlman Can you please verify it?

**Comment by ljpearlman** [comment]
Looks good, thanks!
