### ISSUE TITLE
Support ACLs in `navbarMenu` chaise config

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1887]
We want to be able to control which links show up in the navbar dropdown lists based on ACLs so logged in users, less privileged users, and logged out users can potentially see different dropdown menu lists of links to navigate to.

A proposed solution for this is to extend the `navbarMenu` chaise config option to include another attribute as a sibling to `name` and `url`:
```
navbarMenu: {
  "children": [{
    "name": "Add Anatomical Record",
    "url": "/chaise/recordset/#1/vocab:anatomy",
    "acls": {
      "show": [attribute, ...],
      "enable": [attribute, ...]
    }
  }, {...}, ...]
}
```

The 2 lists in `acls` will be used to control 2 things, whether the option/link is displayed and whether it is interactable. The `show` array will control what group or groups of users can see the current option. The `enable` array will control what group or groups can click that displayed option.

The attributes should match the attributes that are returned as part of the user's session object from webauthn when they login.

**Comment by karlcz** [comment]
I will edit the issue to fix one syntax problem.  The "acls" value is the object containing the "show" and "enable" lists.  There is no extra list around this object.

Otherwise, I think we're on the same page, but I'll add that these ACLs should be located hierarchically, so if not found on the current navbar tree node, look up towards root to find an ACL by that name.  so a top-level ACL can set default rules for the whole bar, then each parent can set defaults for all its `children` entries and each leaf node can have a custom rule.  This should be done for each of `show` and `enable`, i.e. so I could inherit one ACL but set the other.

I would suggest that when a node is determined to have show=false, you skip it and all its children. If show=true but enable=false, it is disabled and so is visible but a disabled interior node (with children) gets converted to a disabled leaf, so there is no way to click/reach its children.

As for implementation, I would suggest that you digest the attribute.id list of the client's webauthn session into a hashmap like `{ "attribute_url_1": true, "attribute_url_2": true, ..., "*": true }` at the beginning. (So even anonymous users have `{"*": true}` as their attribute summary.)  Then, you can quickly iterate an ACL until you find the first element that is a key in the hashmap to answer true or reach the end of the ACL and answer false.

When searching up the navbar tree, to find the applicable ACL, consider a top-most inherited default of `"acls": { "show": ["*"], "enable": ["*"] }` which yields a backwards-compatible default behavior for navbars without any ACLs.

**Comment by jrchudy** [comment]
@karlcz the changes for this issue have been merged into master. Reassigning to you for review.

**Comment by karlcz** [comment]
I can confirm it is working on my dev site. Thanks.
