### ISSUE TITLE
Transposed table view inconsistencies

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#189]
There are several HTML and CSS issues with the tranposed table view

- [ ] The field header styling changes too much between default and tranposed view. Having more consistent style will emphasize that these are the same headings moving around. I'm not sure if the default headings need to be less stark or the transposed headings more stark...
- [ ] The odd/even shading should probably be adjusted to emphasize the flip in table orientation?  I'm less certain of this since in general the horizontal breaks are packed more tightly and thus might benefit more from alternated shading. But, having the same shading before and after leaves less visual indication that there was a mode switch.
- [ ] The scrollable area should exclude the headings consistently in both default and transposed mode.

**Comment by karlcz** [comment]
@hongsudt @robes I suspect this issue is a wontfix unless we are going to turn it into requirements input for revised apps?  Are we still going to support the transposed view at all in the future...?

**Comment by carlkesselman** [comment]
I’m not convinced the transposed view is worth supporting…..

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Jun 8, 2016, at 2:00 PM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:


@hongsudt<https://github.com/hongsudt> @robes<https://github.com/robes> I suspect this issue is a wontfix unless we are going to turn it into requirements input for revised apps? Are we still going to support the transposed view at all in the future...?

**Comment by karlcz** [comment]
Closing as wontfix.
