### ISSUE TITLE
megamenu support

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1907]
Megamenu support for chaise navbar is intended to extend the current navbar dropdown implementation to be more similar to recent web page styles. One example can be found at https://viterbischool.usc.edu/. When you hover over the "About" or "Academics" navbar option, a megamenu shows under the navbar with all the options and suboptions shown to the user.

In our case, we want this to be able to support any number options in each navbar menu and any number of nested menus. We need it to be flexible to cover all cases. One thing to also consider is the responsiveness of this menu when the screen is smaller or wider. How does it change when there are a lot of options available in a tiny amount of screen space? 

Another important piece is to allow this to be customizable. Classes or identifiers should be used in appropriate places so each deployment can customize the megamenu the way they want to.

Here is a good reference to learn from Nielsen Norman Group.
https://www.nngroup.com/articles/mega-menus-work-well/

**Comment by ljpearlman** [comment]
FWIW, I've looked at a few megamenus, and I think the implementation makes a big difference for usability. The two factors that the good menus seem to have are requiring a click to open the menu and having strong visual clues that you're looking at a menu and haven't just navigated to a different page.

Bad example: https://osteopathic.org/
Good example: https://www.who.int/

where "good" and "bad " are defined as "liked by Laura" and "disliked by Laura" (how else would you define them?).

**Comment by carlkesselman** [comment]
I concur with this assessment.  I find the WHO site more intuitive and less confusing.

Megamenus would seem in general to be a good way to go.

Carl


----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On Mar 11, 2020, 8:12 PM -0700, ljpearlman <notifications@github.com>, wrote:

FWIW, I've looked at a few megamenus, and I think the implementation makes a big difference for usability. The two factors that the good menus seem to have are requiring a click to open the menu and having strong visual clues that you're looking at a menu and haven't just navigated to a different page.

Bad example: https://osteopathic.org/
Good example: https://www.who.int/

where "good" and "bad " are defined as "liked by Laura" and "disliked by Laura" (how else would you define them?).

**Comment by RFSH** [comment]
@DamCousik 

### Background knowledge
The current navbar that you see in all chaise apps is dynamic. There are multiple chaise-config properties that dictate how navbar should look like. The notable properties are:
- `customCSS`: the location of a css file that will be included in every chaise page.
- `navbarBrand `, `navbarBrandText `, `navbarBrandImage `
- `navbarMenu `: the navbar menu definition.

You don't need to know how these properties are used, but you have to keep in mind that the new megamenu should be customizable as well. Most probably we're going to have to change how `navbarMenu` is defined when we adopt the new megamenu design. You might realize that changing the structure might actually help the design or responsiveness of the navbar.


### How to approach this task
This task can be broken down into two steps:

#### 1. Designing a static megamenu that is responsible.

The focus is mainly on responsiveness. You have to make sure it's behaving properly in different screen/viewport sizes. Your megamenu should be able to handle having different numbers of menu items or levels.  The CSS that you're writing should not assume a very strict structure. However while designing your megamenu you might realize that making some reasonable assumptions about the structure might actually help the responsiveness. In those cases you should consult with the team. 

To start working on a static megamenu you can,

-  create a `index.html` under your public_html folder in your user directory of dev.rbk. Then you should be able to access it by going to `https://dev.rebuildingakidney.org/~cousik/` (you can add it to a folder if you want, it's up to you.)
- make sure you're including these css files from chaise
```html
<head>
<link rel='stylesheet' type='text/css' href='/~cousik/chaise/styles/vendor/bootstrap.min.css'>
<link rel='stylesheet' type='text/css' href='/~cousik/chaise/styles/vendor/fontawesome.min.css'>
<link rel='stylesheet' type='text/css' href='/~cousik/chaise/common/styles/app.css'>
</head>
```
- Add your megamenu HTML (and possibly js code) to the HTML file that you've created. You can copy the main content of the dev.rbk if you want too. Just so your HTML page looks more like an actual website. You can use the `body` content of `/var/www/html/index.html` (or dev.rebuildingakidney.org) for that matter.

- The CSS rules for navbar are defined [here](https://github.com/informatics-isi-edu/chaise/blob/master/common/styles/scss/_navbar.scss). You can remove the old rules or modify them. Any rules that are going to be in that file should be only based on your new design (remove any unused old rules).

- As I mentioned you're going to add your CSS rules to Chaise, so in order to test your static site, you need to run `make install` anytime that you changed the `_navbar.scss` file.

#### 2. Integrating the static megamenu with chaise and making it dynamic.

**Comment by carlkesselman** [comment]
You are probably already thinking of this... but as we move forward, we need to make sure that as much of the configuration information is stored in the catalog as possible as we currently do with the current navbar.

Carl

----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On May 26, 2020, 6:07 PM -0700, Aref Shafaei <notifications@github.com>, wrote:

@DamCousik<https://github.com/DamCousik>

Background knowledge

The current navbar that you see in all chaise apps is dynamic. There are multiple chaise-config properties that dictate how navbar should look like. The notable properties are:

  *   customCSS: the location of a css file that will be included in every chaise page.
  *   navbarBrand , navbarBrandText , navbarBrandImage
  *   navbarMenu : the navbar menu definition.

You don't need to know how these properties are used, but you have to keep in mind that the new megamenu should be customizable as well. Most probably we're going to have to change how navbarMenu is defined when we adopt the new megamenu design. You might realize that changing the structure might actually help the design or responsiveness of the navbar.

How to approach this task

This task can be broken down into two steps:

1. Designing a static megamenu that is responsible.

The focus is mainly on responsiveness. You have to make sure it's behaving properly in different screen/viewport sizes. Your megamenu should be able to handle having different numbers of menu items or levels. The CSS that you're writing should not assume a very strict structure. However while designing your megamenu you might realize that making some reasonable assumptions about the structure might actually help the responsiveness. In those cases you should consult with the team.

To start working on a static megamenu you can,

  *   create a index.html under your public_html folder in your user directory of dev.rbk. Then you should be able to access it by going to https://dev.rebuildingakidney.org/~cousik/ (you can add it to a folder if you want, it's up to you.)
  *   make sure you're including these css files from chaise

<head>
<link rel='stylesheet' type='text/css' href='/~cousik/chaise/styles/vendor/bootstrap.min.css'>
<link rel='stylesheet' type='text/css' href='/~cousik/chaise/styles/vendor/fontawesome.min.css'>
<link rel='stylesheet' type='text/css' href='/~cousik/chaise/common/styles/app.css'>
</head>

  *   Add your megamenu HTML (and possibly js code) to the HTML file that you've created. You can copy the main content of the dev.rbk if you want too. Just so your HTML page looks more like an actual website. You can use the body content of /var/www/html/index.html (or dev.rebuildingakidney.org) for that matter.

  *   The CSS rules for navbar are defined here<https://github.com/informatics-isi-edu/chaise/blob/master/common/styles/scss/_navbar.scss>. You can remove the old rules or modify them. Any rules that are going to be in that file should be only based on your new design (remove any unused old rules).

  *   As I mentioned you're going to add your CSS rules to Chaise, so in order to test your static site, you need to run make install anytime that you changed the _navbar.scss file.

2. Integrating the static megamenu with chaise and making it dynamic.

**Comment by hongsudt** [comment]
This issue doesn't change the flow of information, therefore no change to how to get the chaise-config parameters. The chaise config can be supplied through the old chaise-config.js deployed with chaise or catalog annotation.


________________________________

**Comment by carlkesselman** [comment]
Perfect.

Carl


----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On May 27, 2020, 10:20 AM -0700, Hongsuda <notifications@github.com>, wrote:

This issue doesn't change the flow of information, therefore no change to how to get the chaise-config parameters. The chaise config can be supplied through the old chaise-config.js deployed with chaise or catalog annotation.


________________________________

**Comment by RFSH** [comment]
Moving to wishlist. We should create a new issue with more information if we would like to implement this.
