### ISSUE TITLE
Inappropriate button height in search popup modal

### ISSUE THREAD

**Issue by iamyle0710** [informatics-isi-edu/chaise#1931]
When I reused the search modal component in `viewer` app, the select button height doesn't seem to have appropriate height. @RFSH mentioned this is a UI bug that we didn't notice before and we should increase the height of the whole row (increase the padding that increased the height), but deciding which one is better is better is something we should do in group and @hongsudt should decide in the end

For now, the current give button height is `auto`, and this can be fixed by adding `min-height: 25px` to the `recordset.scss` rule. 

 
![image](https://user-images.githubusercontent.com/14816171/78932987-5b44bc80-7a5d-11ea-8b7f-67258b0cbf12.png)

**Comment by RFSH** [comment]
This has been fixed. It took me a while to figure this out but it turned out this was because of the missing doctype definition in viewer/index.html.in file. 

If an HTML file lacks the proper doctype definition, it will use the quirks mode, which is meant only for backward compatibility for "legacy code". So it will process the HTML/CSS a bit differently from the standard HTML 5 that we're used to. This was causing some other spacing issues as well.
