### ISSUE TITLE
navbar app: not appearing on page

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#1935]
On the FaceBase website, the navbar app is not appearing at all on one particular page - currently on the staging server:

https://staging.facebase.org/facial_norms/search/

From the console in Chrome dev tools I can see that it failed to load common/templates/navbar.html

AND it's looking for it in an unexpected location:

https://staging.facebase.org/facial_norms/common/templates/navbar.html?v=null

At first I thought it was because this is page is two directories down from the root. But there are other pages at a similar level, even in that same directory that are not experiencing this problem - for example:

https://staging.facebase.org/facial_norms/tools/

One thing about this facial norms search page is that is a javascript app - so it may be some JS clashing going on...

**Comment by jrchudy** [comment]
We assume certain app names to extract the deployment path. In this case, `facial-norms/search` is being run through our function, but since it has search in it's path, `facial-norms` is being treated as the chaise root folder. We need to think about the `chaiseDeploymentPath` function when it is used in other projects that use our navbar embedded on pages that might have the same name in the url as our apps.

I think these are the offending lines:
https://github.com/informatics-isi-edu/chaise/blob/master/common/utils.js#L830-L834

**Comment by RFSH** [comment]
@jrchudy One simple fix is moving up the next `else if` case so we first check for that instead of app name. Then we should make sure that chaise-config property is defined for all deployments.

**Comment by RFSH** [comment]
@crisaless 
As part of the changes that I'm working on for #1936, I will improve this logic in the code. But for now, I removed `search` from that function so it works in this case.

Also if your static site has  `record`, `recordset`, `recordedit`, or `login` as part of the URL, it will break because of the same function.  As I mentioned this will be fixed later and this is done just so we can have a functional navbar for now.

**Comment by crisaless** [comment]
I confirmed there are no urls in the facebase static site with those words. 

ok, sounds good!

**Comment by RFSH** [comment]
This has been properly fixed by the latest changes in Chaise. We're not making any assumption about the app names and we're using the environment variables that are used to build the chaise to signal chaise javascript code where the code is actually installed.
