### ISSUE TITLE
Adding a separate class to <figcaption> to differentiate captions for images and iframe

### ISSUE THREAD

**Issue by DamCousik** [informatics-isi-edu/chaise#1961]
### **Issue:** 

When the `<figcaption>` tag is currently used, the styling elements apply commonly to both images and `<iframe>` that have captions. 

`<iframe>`
E.g. Iframe with treeview app: https://dev.rebuildingakidney.org/chaise/record/#2/Gene_Expression:Specimen/RID=N-GXA4
embedded viewer app: https://dev.rebuildingakidney.org/chaise/record/#2/Gene_Expression:Image/RID=14-47YP
Iframe to plot app (violin): https://dev.rebuildingakidney.org/chaise/record/#2/RNASeq:Study/RID=Q-Y4GY
iframe to cell browser: https://dev.rebuildingakidney.org/chaise/record/#2/RNASeq:Study/RID=W-RAHW
Iframe to genome browser: https://dev.facebase.org/chaise/record/#1/isa:dataset/RID=TMJ
Ifrane to plot app (bar): https://staging.gudmap.org/

`<img>`
E.g.: https://dev.facebase.org/chaise/record/#1/isa:dataset/RID=1-3VKE

### **Solution**

Adding a separate class selector to the `<figcaption>` for images and `<iframe>` which would help customize the respective captions independently and thus provide more design flexibility.

**Comment by RFSH** [comment]
(It seems like we also show figcaption in the case of `video` tag, for a complete list of markdown tags [refer to this documentation](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/markdown-formatting.md).)

## Prerequisite

We need to first agree on the class name that we're going to use. Currently, we're attaching `embed-caption` class to `iframe` and `image` captions. So we could use

- `iframe-embed-caption` for iframe,
- `image-embed-caption` for image,
- `video-embed-caption` for video.

## Where to change

1. Add your class names to the constant list that we have [in here](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/utils/constants.js#L278). 


2. The code responsible for processing `iframe`, `image`, and other markdown supported tags are in ermrestjs. You can simply search for `figcaption` and find the different places that we're using it. These are the different places:
    - [iframe](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/utils/helpers.js#L1901,L1905)
    - [image](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/utils/helpers.js#L2086,L2090)
    - [video](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/utils/helpers.js#L2182,L2186)
  You just need to add the class name to these lines of codes. 

### How to test

1. Now that you've made this change, you can just `make install` and make sure your change is correctly applied in the server that you're manually testing. 

2. You need to make sure automated test cases are passing too. We use `dev.isrd.isi.edu` server for running test cases. So update your environment variables to point to this server and install ermrestjs in this server.

3. The test suite [needs some extra environment variables](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/dev-docs/unit-test.md#sample-enviroment-variables). Make sure those are defined too.

4. Clone [ErmrestDataUtils](https://github.com/informatics-isi-edu/ermrestdatautils) and make sure it's in the same folder as your ermrestjs folder. So assuming you've cloned ermrestjs in `/path/to/ermrestjs/`, it should be available by `/path/to/ErmrestDataUtils`.

5. Run `npm install` to make sure all the dependencies that the test suit relies on are available. 

6. Run the test cases by doing `make test`. It will take a few minutes to complete.

7. After running test cases, you will most probably notice that some of them are broken. It's simply because the expected HTML elements have changed (you added a new class to them). So you just have to find where the test case failed and fix the expected value.

**Comment by jrchudy** [comment]
Not sure why this issue is "Blocked". Moving back to "This Week".

**Comment by RFSH** [comment]
I am going to close this issue since CSS rules can be customized to look for specific tag and we don't need specialized class names for each type.
