### ISSUE TITLE
SVG annotation thickness issue

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1963]
In the viewer app, users can change the thickness of SVG annotations. But the thickness is not adaptive based on the image. We're only allowing a scale of 1-6 where the middle value is the default thickness of the image. If the image is very thin, even scaling it to 6 might not be enough.

We could set the default thickness based on the pixel size of SVG outlines, or the simpler solution might be allowing a bigger scale change (1-10 maybe?).

**Comment by rastogi-bhavya** [comment]
Adding "vector-effect:non-scaling-stroke" to the style fixed the issue for that particular case. Adding it manually to all the files while parsing them cold cause some unexpected behavior, therefore need to do more research on that.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/vector-effect

**Comment by rastogi-bhavya** [comment]
vector-effect=“non-scaling-stroke”
in this case while drawing a line, instead of drawing the line in the user coordinate space (normal behavior i.e. when this value is set to ‘none’), the line is first drawn in the host coordinate space (screen coordinate space i.e. 2px according to the screen resolution). This line is then converted into the user coordinate space, so according to zoom level this might equate to 1px (fully zoomed in) or 100px (fully zoomed out)![zoomed in.JPG](https://images.zenhubusercontent.com/5ebddb0b7e863dce4ee7e1ff/80bf5dd7-fb86-4736-9f25-c48cc7666af5)![zoomed out.JPG](https://images.zenhubusercontent.com/5ebddb0b7e863dce4ee7e1ff/88d54fb2-b321-48b9-9db6-084515c0b1dc)

**Comment by RFSH** [comment]
@rastogi-bhavya If this is done please close the issue. If it's applicable, mention the PR and related issues that fixed this and "close and comment" the issue.

**Comment by RFSH** [comment]
This has been fixed. [This issue in openseadragon-viewer](https://github.com/informatics-isi-edu/openseadragon-viewer/issues/37) adds a new parameter so we can signal the app to change the thickness logic.
