### ISSUE TITLE
set html page title based on annotation at least for record app

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1967]
I'd like to be able to set the 'title' of a page at least for the Record app. One approach might be to:

a) check for the (to be added) `row_name/page_title` subcontext on the `tag:isrd.isi.edu,2016:table-display` annotation
b) fall back to `row_name` if subcontext is not set
c) fall back to the current default if the `row_name` is not set

This would be useful for a variety of UX reasons:
* the page title is used in the header of the page when printing a page (so its very useful for the print feature and cannot be nicely done via print css), and ...
* it will make the browser tabs more meaningful when you have several open
* it will make browser bookmarks meaningful

**Comment by karlcz** [comment]
Should the title still include any additional info beyond the row-name?
- table name
- host/domain name
- catalog number?

**Comment by robes** [comment]
Ah good question. That slipped my mind because I was actually thinking at one point that we might want to have “{Table Display Name}: “ as a prefix before the `row_name/page_title` (or whatever) annotation. I hadn’t thought about the others.

**Comment by RFSH** [comment]
We had a brief conversation about this, and the following are the different points that came up:

- Chaise currently is using the `headTitle` chaise-config property for the title, and if this property is using will use `Chaise`.  Going forward are we going to ditch this solution? or should the new annotation be added to the current title? so `<the current heuristics> | <row_name/page_title value>` (e.g., `Chaise | Homo Sapien`). If we add these together we're going to have length issue. I don't think there's a defined limit on the title, but if it's too long, it will be useless. 
- The same way that we're currently exposing the catalog number in the template environments using `$catalog` variable, we could do the same for host/domain name. Although I'm not sure if the host/domain name is useful or not. For example in the case of rebuildingakidney and gudmap, they are using `RBK/GUDMAP resources` which is more human-readable than the host/domain itself. 
- Adding table name to templating environments might be messier than catalog number and host/domain name. These two variables are global and won't change from template to template, but the table name will change. Should we limit accessing the table name to this `row_markdown_pattern` annotation? Or should it be a global solution? What would be a proper name for this? We currently have
  - `$moment`: to get the current date and time 
  - `$catalog`: access catalog info
     ```
     "$catalog": {
       "snapshot": "",
       "id": "",
       "version": ""
     }
     ```
  - `$fkey_<schema>_<constraint>`: the outbound foreignkey value
  - `$self`: In `markdown_pattern` defined on source objects to access the value of the current pseudo-column.
  - `$page`: Only available on `page_markdown_pattern`, with the following structure (this was added as a hack):
    ```
    "$page": {
        "values": {
          "RID": "",
          "_RID": "",
          ...
        },
       "parent":  {
         "values": {
           "RID": "",
           "_RID": "",
           ...
         },
         "table": "table name",
         "schema": "schema name"
       }
    }
    ```
- This issue is only describing the desired behavior of the record app, but what should do for the other apps? Should they continue to behave the way they are? Should we define appropriate annotations for those? Should we at least append table name and app name to the current heuristics?

**Comment by robes** [comment]
I would be fine with a `row_name/page_title` with the same markdown environment given to the usual `row_name`. I do not care about having `<table_name> | ` prefixing it. I also don’t care about host/domain name. I personally would argue against doing extra work on this to expand the markdown environment.

**Comment by karlcz** [comment]
I think that browser tabs show the prefix of the page title when they
are long, so it would be good for the default heuristics to front-load
the record-specific info and follow with more general stuff that might
be less useful for distinguishing multiple tabs from the same site (but
useful for a full-size window title)...

**Comment by RFSH** [comment]
Ok, so it seems like I misinterpreted the requested feature. So then we just want to 
- Change the default page title heuristics
- Allow data-modelers to override heuristics (and define the page title). 

## Heuristics
- Based on what I found out, there is no limit on the length of page titles. The limiting factor is just the number of characters that are usually visible on browsers (which is different from browser to browser and also depends on the number of opened tabs). The suggested length is 50-60 characters. Since we cannot dictate this, we just have to make sure the most important piece of data is displayed first. So I suggest using the same titles that we have right now. 
- The page title will be displayed in Google's search result, and also when you share this link on social media websites. That's why I think only the data/model-oriented information is not enough, and we should add the `chaiseConfig.headTitle`. 
- To separate these two pieces of information we could use `-` or `|`. I propose the usage of `|` since `-` is used in RID values (and can be used in the row name as well). The `|` character is unique enough that most probably won't be part of the row name or table name.

Therefore the following is the suggested formats with some examples:

You can test this in [facebase](https://dev.facebase.org/~ashafaei/chaise_title/record/#1/isa:project/RID=25NR) and [rbk](https://dev.rebuildingakidney.org/~ashafaei/chaise_title/recordset/#2/Common:Gene).

|               | format                                   | example 1                               | example with longer values                                                                                                |
|---------------|------------------------------------------|-----------------------------------------|---------------------------------------------------------------------------------------------------------------------------|
| Recordset     | `<table> \| <headTitle>`                 | Gene \| RBK/GUDMAP Resources            | Project \| Data Browser \| FaceBase                                                                                       |
| Record        | `<table>: <rowname> \| <headTitle>`      | Gene: A1BG \| RBK/GUDMAP Resources      | Project: Hallgrimsson, Marcucio: Developmental Nonlinearity Drives Phenotypic Robustness \| Data Browser \| FaceBase      |
| Edit single   | `Edit <table>: <rowname> \| <headTitle>` | Edit Gene: A1BG \| RBK/GUDMAP Resources | Edit Project: Hallgrimsson, Marcucio: Developmental Nonlinearity Drives Phenotypic Robustness \| Data Browser \| FaceBase |
| Edit multiple | `Edit <table> \| <rowname>`              | Edit Gene \| RBK/GUDMAP Resources       | Edit Project \| Data Browser \| FaceBase                                                                                  |
| Create        | `Create new <table> \| <headTitle>`      | Create Gene \| RBK/GUDMAP Resources     | Create Project \| Data Browser \| FaceBase                                                                                |
   

## How to override heuristics

The suggested approach by @robes makes sense for record page and it follows the existing pattern of defining `row_markdown_pattern`. So for the record page title, the following can be used:

```
"tag:isrd.isi.edu,2016:table-display": {
  "row_name/page_title": {
    "row_markdown_pattern": "<title>"
  }
}
```

But what about other apps? If we want to follow the same pattern and allow them to define title based on data content, we can use `page_markdown_pattern`, so

```
"tag:isrd.isi.edu,2016:table-display": {
  "row_name/page_title": {
    "page_markdown_pattern": "<here>"
  }
}
```

But how should we contextualize this? should we introduce `row_name/page_title/detailed`, `row_name/page_title/compact`, etc?

If we don't want a data-oriented solution, we could add a `page_title` attribute that is contextualized to display annotation too.

```
"tag:misd.isi.edu,2015:display": {
  "page_title": {
     "compact": "<title>",
     "entry/edit": "<another title>"
  }
}
```

So we use `table-display` for record and `display` annotation for other pages. I don't like this solution, but I cannot think of a better way.

**Comment by jrchudy** [comment]
Implementation of heuristics will be done first. Ability to configure and override heuristics will be added as part of a separate issue.

**Comment by robes** [comment]
Works for me :+1:

**Comment by jrchudy** [comment]
The default heuristics for this have been merged into master. The html page title will follow the outline in [this comment](https://github.com/informatics-isi-edu/chaise/issues/1967#issuecomment-651242988).

Reassigning to @robes .

**Comment by robes** [comment]
The title itself looks good, however, this seems to have inadvertently altered the browser history in a way that should be fixed.


  1.  Go to any record page
  2.  Navigate to a related record
  3.  Navigate to another related record
  4.  Look at your browser history

What you’ll see is the generic title interleaved between the newly updated title. And if you click on one of the generic history entries you’ll go to the same location as the following non-generic title.

For example, see attached screenshot. (disregard the last several generic titles as those were either from recordset or an earlier comparison against our prod server)

[Graphical user interface  Description automatically generated]

**Comment by jrchudy** [comment]
This seems to be an issue with firefox and is not seen in chrome. I will investigate further what could be causing this.

**Comment by robes** [comment]
With Chrome on MacOS, I get double entries in history but they are both non-generic.

**Comment by jrchudy** [comment]
Ah ok, I see that now. What I was looking at on firefox was the history for the back button that seems to capture something similar.

**Comment by jrchudy** [comment]
Looks like the address is the same page in the cases I looked at but the difference is from when we remove the pcid and ppid from the url. Sometimes this is removed before the title is updated and sometimes it's removed after. This might explain why it's more noticeable now.

**Comment by jrchudy** [comment]
Issues #2035 and #2036 have been opened based on the comments in this issue.
