### ISSUE TITLE
Modular search and search-within

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#197]
This is somewhere between user-story and software architecture...

We eventually need an entity-result-set presentation that includes a number of features we've explored already in different places:
1. Defined by an ERMrest search
   - The base entity aka table
   - Search criteria as predicates
   - Possibly a complex path accumulating several related entity navigation links
2. Nice tabular presentation
   - ERMrest-based pagination or infinite scroll to handle potentially large results sanely
   - ERMrest-based sorting to let user control presentation order of result set
   - Optional/alternative presentations for things like images or downloads
3. ERMrest-based search within the set
   - Refines search by adding more predicates
   - Facet-based or other

This result-set presentation needs to be modular so it can be applied in different UI contexts:
1. Replacing current search app when started on a table w/o any predicates
2. Replacing related entities in record app
3. Possibly appearing in nested/modal search controls, e.g. to allow search app to define a search criteria in terms of filters on related entities.
4. Possibly a new records or relatedsearch app that lets you navigate the ERM without narrowing to a single record ID first.  E.g. "filter a set of mice" then "filter a set of data files for those mice".

**Comment by robes** [comment]
how do we break this down? start a design discussion? otherwise this will sit here until it gets demoted to wishlist, i think.

**Comment by karlcz** [comment]
@robes Is this even wishlist anymore, or just wontfix since we are talking about record app navigating to recordset for related entity exploration?

**Comment by robes** [comment]
This seems to apply to recordset app not record app. We have started down the path of "search within" by the fact that you can enter the recordset app with a URL that defines some initial filters. Then we want to enable "search within" or perhaps I should say "filter within" by applying additional predicates to the query. Hope I followed this correctly.

**Comment by karlcz** [comment]
I think this issue's original text is describing something like having search capabilities on each embedded related entities table in the record app.  But, I think in other issues we've since discussed having a much simpler table representation and link back to recordset for that case...?

**Comment by carlkesselman** [comment]
Yes, I think that sounds right.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Jun 8, 2016, at 4:27 PM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:

I think this issue's original text is describing something like having search capabilities on each embedded related entities table in the record app. But, I think in other issues we've since discussed having a much simpler table representation and link back to recordset for that case...?

**Comment by karlcz** [comment]
If we continue the search-within story here, it seems it will involve record2 and recordset:

1. Record2 needs to form appropriate recordset links to restrict a recordset by path context.
2. Recordset needs to allow its search options to compose with the existing path context.
3. Eventually we need to understand the UX around visually describing the search context and/or allowing revision or "go back" capabilities to prune or amend the context?

**Comment by RFSH** [comment]
I am going to close this issue. It's very old and I don't think it's applicable to the current chaise. Besides, the "new" record and recordset apps are designed based on the previous comment on this issue.
