### ISSUE TITLE
Timestamptz facet UX problems

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1974]
The timestamptz facet control has a couple UX problems

1. It displays UTC times instead of times in browser's local timezone.  Not ideal but ok if no way around.
2. It picks bad value for upper bound which may exclude latest rows of table. This seems to be due to truncating fractional seconds.

For example, I have a table where the newest records have "2020-07-06T16:53:02.488702-07:00" as the RCT returned by ermrest. But the upper bound selected by the facet control is displayed as  "2020-07-06" and "23:53:02" which corresponds to the value sent to ermrest as "2020-07-06T23:53:02.000+00:00".  This excludes the records which were created 488ms later.

If I just click the checkmark button to apply the default range filter, the page updates and indicates slightly fewer records than were originally found in the unfiltered set. If this were really full range, the same number of records should still be visible.

If I manually edit the filter to increment by 1 second, I then find all the expected rows.

### Proposed solution for timestamp[tz] columns:
For the range picker in timestamp[tz] facets, we decided on the following:
 1. The returned min and max value will be adjusted by an epsilon value to make sure the full set is included if the returned min/max are used to query.
    - The max will be increased by 1 second, and then have the fractional seconds removed (if any are present)
    - The min will only have the fractional seconds removed (if any are present)
 2. This "adjusted" min/max will be displayed in the inputs for the user, and submitted as shown if the user decides to apply that as a filter.
 
NOTE: The inputs for time will not change. The input will continue to disallow fractional seconds to be typed.
 

### Proposed solution for float columns:
For the range picker in float facets, we decided on the following:
 1. The returned min and max value will be adjusted by an epsilon value to make sure the full set is included if the returned min/max are used to query.
    - The max will be increased by a very small "calculated" epsilon value, then truncated to precision 4 (calling the **ceiling** function to always round up)
    - The min will be decreased by a very small "calculated" epsilon value, then truncated to precision 4 (calling the **floor** function to always round down)
 2. This "adjusted" min/max will be displayed in the inputs for the user, and submitted as shown if the user decides to apply that as a filter.
 3. The user can submit float values of any precision, but these values will be truncated to precision 4 as detailed above.
 
#### Calculating epsilon for floats
The general function for calculating epsilon will be `pow(2, exponent_base + log2(abs(x)))`. The `exponent_base` value is determined based on the column type. For `float4` we will use `-23` and for `float8` we will use `-52`. `x` in this case is the returned `min` or `max` value depending on which value we are calculating the epsilon value for.

Once epsilon is calculated, we then decide whether the epsilon value should be used by doing 2 checks. First, we make sure that the absolute value of `x` is greater than 0. This prevents using a zero or negative value in the `log2()` function which returns non numeric values if that is done. 

Next we take the max of tiny and our above calculated epsilon to get our new epsilon, `max(tiny, epsilon)`. Tiny is calculated as `pow(2, -127)` for `float4` and `pow(2, -1022)` for `float8` (-127 and -1022 being the smallest possible exponent for their respective float types).

**Comment by jrchudy** [comment]
From our discussion in chaise standup today, we talked about 2 scenarios. The default functionality for ranged facets has both the min and max value as inclusive. So when a request is sent to the server, it matches values like the following:
```
min <= value <= max
```

This works great for integer, float, and date inputs. The issue comes back to what is stated above, `timestamptz` values including fractional seconds (to the precision of 6, i.e. `12:30:02.123456`). The UI doesn't account for this currently, it is truncating those fractional seconds and ignoring them as part of the request.

Proposed fix:
- default case with `min <= value <= max`
  - increment the max by 1 second and floor the value
  - truncate the min
  - request to server will be `min <= value <= max+1sec` with no fractional seconds
  - display the user's input value of min/max without the "1 second increment"
- min is exclusive (`value > min`)
  - fractional seconds will be matched
  - min is `12:30:02`, `12:30:02.123456` will be included
  - `12:30:02` will be excluded
- max is exclusive (`value < max`)
  - don't increment the seconds before truncating
  - max is `12:30:02`, `12:30:02.123456` will be excluded
  - `12:30:02` will be excluded
