### ISSUE TITLE
Color picker support

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2015]
In the new Image Channel table, we are going to store the color value. And then users should be able to modify this color through the recordedit app. These are the list of tasks that should be done for this change (it's not limited to chaise):

- [x] Determine the web standard color format  (hex, rgb, etc)
- [x] Define a custom type in ERMrest
- [x] Expose the new type to ERMrest
- [x] Add color picker in recordedit
  - We can use [the color input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color). Although this input is not supported by IE.
- [x] For display purposes we should display a rectangle with that color + the raw color value

- [ ] ETL the existing Pseudo_Color column values.
  - The color in dzi images are currently stored as tuples with three values where they respectively represent red, green, and blue. Each value is represented as a number in 0-1 range. To convert to a 0-255 scale, you just need to multiply each one by 255. And then to convert to hexadecimal format, you would convert each value to base 16, and then concatenate them together. For example:

    - the color in dzi image: `(1.000000 0.000000 0.000000)`
    - converted to RGB 0-255 format: `(255, 0, 0)`
    - converted to hexadecimal format: `#FF0000`

**Comment by RFSH** [comment]
Based on [w3 specification](https://www.w3.org/TR/2018/REC-css-color-3-20180619/#colorunits) (and more user friendly [MDN web docs page](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value)), the color CSS3 data type represents a color in the sRGB color space. It may also include an alpha-channel transparency value, indicating how the color should composite with its background. It can be defined,

- using a keyword (such as blue or transparent)
- using the RGB cubic-coordinate system (via the #-hexadecimal or the `rgb()` and `rgba()` functional notations)
- using the HSL cylindrical-coordinate system (via the `hsl()` and `hsla()` functional notations)

I couldn't find any documentation that says one format is better than the other, or one is standard and the other one is not. So I don't think there really is a single "standard" web color format and we just have to pick a format that fits our needs. As was suggested by @karlcz, we should be specific about the format in the name of the custom type and that would also allow us to introduce other color types in the future (if needed.)

Therefore,
- in this case, we most probably want users to pick a fully opaque color. So we don't want to offer `rgba` or `hsla` formats. 
- If we end up using the `color` input in HTML, we can tailor the type based on its specification. This input only accepts 7 character hexadecimal (`#rrggbb`) color format.
- The `#rrggbb` format is easier to understand and encode. Since we want the base type to be string, with the other `rgb()` and `hsl()` formats you have to remember the parenthesis and commas in the color values which can be easily missed.

So I think we should use `#rrggbb` format and use `color_rgb_hex` for naming the custom type.

**Comment by carlkesselman** [comment]
This is probably the right choice.

Carl

----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On Sep 30, 2020, 5:26 PM -0700, Aref Shafaei <notifications@github.com>, wrote:

Based on w3 specification<https://www.w3.org/TR/2018/REC-css-color-3-20180619/#colorunits> (and more user friendly MDN web docs page<https://developer.mozilla.org/en-US/docs/Web/CSS/color_value>), the color CSS3 data type represents a color in the sRGB color space. It may also include an alpha-channel transparency value, indicating how the color should composite with its background. It can be defined,

  *   using a keyword (such as blue or transparent)
  *   using the RGB cubic-coordinate system (via the #-hexadecimal or the rgb() and rgba() functional notations)
  *   using the HSL cylindrical-coordinate system (via the hsl() and hsla() functional notations)

I couldn't find any documentation that says one format is better than the other, or one is standard and the other one is not. So I don't think there really is a single "standard" web color format and we just have to pick a format that fits our needs. As was suggested by @karlcz<https://github.com/karlcz>, we should be specific about the format in the name of the custom type and that would also allow us to introduce other color types in the future (if needed.)

Therefore,

  *   in this case, we most probably want users to pick a fully opaque color. So we don't want to offer rgba or hsla formats.
  *   If we end up using the color input in HTML, we can tailor the type based on its specification. This input only accepts 7 character hexadecimal (#rrggbb) color format.
  *   The #rrggbb format is easier to understand and encode. Since we want the base type to be string, with the other rgb() and hsl() formats you have to remember the parenthesis and commas in the color values which can be easily missed.

So I think we should use #rrggbb format and use color_rgb_hex for naming the custom type.

**Comment by RFSH** [comment]
The required changes in ERMrestJS and Chaise for this feature are merged. 

I'm going to assign this @svoinea and @hongsudt  for the last step (ETL the existing Pseudo_Color column values) which is outside of Chaise/ERMrestJS scope.
