### ISSUE TITLE
Update recordedit multiset to use table directive properly

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2020]
The multiset view for recordedit uses the table directive directly without calling the recordset directive and uses some of the functionality of the flow control. For instance, the data that is used for the table comes from the table model definition [here](https://github.com/informatics-isi-edu/chaise/blob/master/recordedit/form.controller.js#L131) but the [attached columns](https://github.com/informatics-isi-edu/chaise/blob/master/recordedit/form.controller.js#L125) are ignored in favor of using the `columModels` attached [here](https://github.com/informatics-isi-edu/chaise/blob/master/common/table.js#L902-L908).

We should decide to keep the functionality limited to the table directive without including flow control logic or have all of the [table model definition](https://github.com/informatics-isi-edu/chaise/blob/master/recordedit/form.controller.js#L122-L143) align with what we use now for the table directive and flow control (it looks like the model definition is out of date and should be re-evaluated).

**Comment by RFSH** [comment]
The flow-control in recordset/table directive is used for "initialization" (populating the values in the start) as well as "internal update" (when sort or some other setting from outside the table directive has changed and we need to update the table data.) Since this directive is used in different apps in different modes, this logic might or not might be called in different apps. If we don't want the directive to handle the initialization, we can just pass the `rowValues` and then signal the directive that it can start showing the data right away.


- In the recordset app (as well as recordset popups), the full functionality of flow-control is used for initialization and internal update. We're just setting the model attributes, and by sending a signal, the recordset app starts the initialization. 

- In the record app, since we wanted to have an app-wide flow-control, it will take care of the initialization part (sends the requests, populated `rowValues` and then let the directive now that it can show the data.) But we still want users to be able to sort or change the page size for each individual table. So the directive will take care of the internal update for us.


- In the recordedit app, we only want to show some static data in a tabular format. So the initialization is done by the app itself, and since we're completely disabling sort and other "update" features, it will never run any of the flow-control code.


The `columnModels` object is not part of the flow-control at all. It's just a container for our columns. As you pointed out the `columns` that is passed from the `SearchPopupController` is not used at all. It's just something that was forgotten when the refactoring was done in this directive to use the `columnModels` instead of `columns`. So the only actionable thing that we should do is just removing this `vm.columns` attribute from the table directive (and then `SearchPopupController` and anywhere else that is using it.)

I think it might be better if we just close this issue and add move this as a comment to our code. it's a refactoring/cleanup task that is not really a high priority either.
