### ISSUE TITLE
CFDE: Customize or override csv export

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#2074]
We should allow customization of the csv export feature.

1. **Allow default to be disabled per table or globally** (priority)
2. Define heuristics to adjust based on visible columns (a new context?)
3. Allow custom export rule to override/replace default
4. Allow quota/limit settings. Disable recordset export if current result set is larger than a specified limit?

**Comment by karlcz** [comment]
I don't really see how you can decouple it from Chaise as it is
exporting a query result set.  Chaise does the hard part which is
defining the ermrest query with facet filters, and knows the
additional context needed to define the desired result set projection
as well.

To move this boundary would be to pretty much start over from scratch
on an entirely different export service that is far more model-aware
and chaise-aware.

**Comment by RFSH** [comment]
- With the changes in [#2113](https://github.com/informatics-isi-edu/chaise/pull/2113) and [ermrestjs#897](https://github.com/informatics-isi-edu/ermrestjs/pull/897),  we modified csv export to honor the `visible-columns` annotation.

- Since we allow empty column list, you can define an empty array list to disable the csv export for each table. 

- As [we discussed](https://github.com/informatics-isi-edu/chaise/issues/2100#issuecomment-892907966), for "customizing the csv export", you would have to disable it and then add your own CSV template using `export-2019` annotation.

This will only leave the following from the original issue description:
 - Allow quota/limit settings. Disable recordset export if current result set is larger than a specified limit?
 - Allow default to be disabled _globally_

This two requires more discussion among the group, so I'm not going to close the issue.
