### ISSUE TITLE
CFDE: Saved Query - remap facet keys for persistence across catalogs

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2098]
### Summary
This is an extension to issue #2073. In CFDE, the model might change and the facet definitions are optimized to be performant and not persistence. So when we're saving the facets, we have to make sure we're storing a more persistent object.

Therefore each facet will go through a transformation and will attach more attributes to the blob (or modify existing ones). And on the consumer side (#2077), we will use these extra attributes to properly handle model change and offer a better recovery option to users.

### Transformed facet structure

In the following I will go over each attribute that we're going to add/modify:

- `markdown_name` (the displayname of facet) will be stored to produce better error messages.
- Given that the model and therefore the foreign key paths might change, we are going to store the `sourcekey` (if available) instead of `source`.
- We cannot blindly apply the facet if its UX mode has changed, so we're going to store `entity` attribute as well.
- In case of entity mode, we want to transform the `choices` to be based on a more robust key column.
- We want to make sure that the end table has not changed, so we have to store the `schema` and `table` names. Since we're going to transform the encoded `choices`,  we also need to store the `column`. We're going to add these three attributes in a `source_domain` object.

Based on this, assuming the following is the current encoded facet:

```json
{
  "and":[ 
    {
      "source": [ {"outbound": ["CFDE", "subject_species_fkey"]}, "nid" ],
      "entity": true,
      "choices": [ 1, 5 ]
    },
    {
      "source": [ {"outbound": ["CFDE", "subject_species_fkey"]}, "title" ],
      "entity": false,
      "choices": [ "title1" ]
    }
  ]
}
```

We are going to store the following instead:
    
```json
{
  "and": [
    {
      "sourcekey": "S_species",
      "markdown_name": "Subject Species",
      "entity": true,
      "choices": [ "NCBI:txid9606", "NCBI:txid9611" ],
      "source_domain": {
        "schema": "CFDE",
        "table": "ncbi_taxonomy",
        "column": "id"
      }
    },
    {
      "sourcekey": "S_species_title",
      "markdown_name": "Species title",
      "entity": false,
      "choices": [ "title1" ],
      "source_domain": {
        "schema": "CFDE",
        "table": "ncbi_taxonomy",
        "column": "title"
      }
    }
  ]
}
```

### Details

- As I mentioned in the previous section, in entity modes we want to map the existing facet definition end column to a more persistent key definition. For that, we could introduce the same annotation that we mentioned in [here](https://github.com/informatics-isi-edu/ermrestjs/issues/874#issuecomment-824264390). So

  ```json
  "tag:isrd.isi.edu,2021:table-config": {
    "stable_key_columns": ["name1"],
    "stable_key": ["schema", "constraint"]
  },
  ```
  - If both `stable_key_columns` and `stable_key` are defined, we're going to use `stable_key_columns`.
  - If any of the defined columns are nullable, we should invalidate and ignore the annotation.
  - For now composite columns are not allowed.

- For scalar modes, we only capture the current `source_domain` based on the source definition (mapping to a different column is not needed.) The goal is to ensure consistency of definition when we want to use this transformed facet.

**Comment by RFSH** [comment]
We had a conversation about this and in this comment I will try to summarize my understanding of it:

There are two ways to apply the saved query to recordset:
  - User is in the same recordset page, clicks on "show saved queries" and selects one of the queries.
  - User is in the "dashboard" or saved query table, and clicks on a link associated with one of the saved queries and navigates to a table with applied saved query.

When users save a query, we cannot just store the current facet blob as the model might change overtime and we want to make sure the saved query can recover. So while saving the query we are going to transform the facet blob:
  - Instead of saving the `source` attribute, we might want to save `sourcekey` as it's more robust. Choosing `source` or `sourcekey` could also be configurable per facet, table, or deployment.
  - We are going to add some extra attributes to ensure the facet state has not changed. These attributes will be used for validation and if they don't match, we are going to show a warning to users:
    - `markdown_name`: The computed title of facet. Useful to form a human-readable error message. 
    - `entity`: Whether it's in entity or scalar mode.
    - `choices`: An array of values. Eventually this might be an array of arrays.
    - `source_domain`: Information about the domain (leaf) table/column.
      - `schema`: For detecting model conflict
      - `table`: For detecting model conflict
      - `column`: For mapping the given `choices` values to the displayed facet column.

For example, assuming the following is the current encoded facet in url:
    
```json
{
  "source": [ {"outbound": ["CFDE", "subject_species_fkey"]}, "nid" ],
  "entity": true,
  "choices": [ 1, 5 ]
}
```

We want to store the following instead:
    
  ```json
{
  "sourcekey": "S_species",
  "markdown_name": "Subject Species",
  "entity": true,
  "choices": [ "NCBI:txid9606", "NCBI:txid9611" ],
  "source_domain": {
    "schema": "CFDE",
     "table": "ncbi_taxonomy",
     "column": "id"
    }
}
```

So we would need to add an API to ERMrestJS to translate a facet state into this object. And then we have to change the ERMrestJS logic that is merging the filters in facet blob with facet panel to consumes this new object. The following is the current logic:
  
  https://lucid.app/lucidchart/9bdde76f-ab56-4e07-8099-ed6987fb391d/edit?page=gHjjwlkrc_Jt#
  ![](https://i.imgur.com/umVe4qr.png)
  
And now we just want to modify this logic, to do verification and transformation. The following how I'm imagining the new process would be (**subject to change and requires discussion**):
  
  https://lucid.app/lucidchart/5e978d3e-d2f3-4f57-998a-b1ec978811d6/edit?beaconFlowId=FD431162594A6337&page=gHjjwlkrc_Jt#
  ![](https://i.imgur.com/Wnh5lgZ.png)
  
  - What if the extra `source_domain` is missing? Should we skip the validation?
  - What if the `sourcekey` is valid and just not part of the facet list? Should this be a configuration to switch between throwing error and adding a new facet to the panel?
  - In scalar mode, we're doing the filtering based on the raw value and the formatted raw value is displayed to the users. So I don't see the point of doing column mapping in this case. In entity mode, we're displaying the "rowname" to users and the raw value is just used internally, so it makes sense if we want to change the internal logic (based on model change) without changing what's displayed to the users.

**Comment by karlcz** [comment]
On Aug 02, Aref Shafaei modulated:

>   • What if the extra source_domain is missing? Should we skip the
>     validation?

Right, I think absence of source_domain means you just try to use
the choices/values for the column designated in the actual source
path that is defined for the source key.  See comments at end
of this message about related error scenarios.

I would also ignore a source_domain that is supplied along with an
actual source path. The path is authoritative, if present. The domain
is meant to validate the sourcekey being defined in a "compatible"
manner.

>   • What if the sourcekey is valid and just not part of the facet list?
>     Should this be a configuration to switch between throwing error and
>     adding a new facet to the panel?

I think it should add the facet to the list. An option to suppress
this seems reasonable but not necessarily important for the MVP...  If
a DBA really doesn't want the facet to work anymore, they could remove
the definition for that sourcekey, causing an error.

>   • In scalar mode, we're doing the filtering based on the raw value
>     and the formatted raw value is displayed to the users. So I don't
>     see the point of doing column mapping in this case. In entity mode,
>     we're displaying the "rowname" to users and the raw value is just
>     used internally, so it makes sense if we want to change the
>     internal logic (based on model change) without changing what's
>     displayed to the users.

That's right, I think remapping is only applicable for choosing
alternate keys in entity facets.  To allow for schema evolution, I
think it would be more useful to be generous about using scalar facets
even if the sourcekey has been moved from one source column (or
table!) to another.

What about type mismatches?  Do we want to include a
source_domain.type field to record the column type and detect a
mismatch, e.g. a saved filter using values incompatible with the
source column of the catalog?  Or do we just handle 409 Conflict
responses and signal the facet error asynchronously?

What about missing entity choices? I think we plan to check for
absent/unmappable entities during the facet pre-processing, and we
should notify the user that certain saved choices cannot be satisfied,
and ask how to proceed:

1. Drop affected choices: makes query _more selective_
2. Drop affected facets: makes query _less selective_

If all choices are missing, (2) is the only option possible, as the
facet goes from having filters set to having no filters!

It is less important for the MVP, but we might want to propose a
backlog enhancement to do similar tests for scalar filters. E.g. if a
choice or range limit cannot be satisfied by the source_domain column
at all, then the user might want to review that facet and adjust the
criteria.

The main difference here is that we can provide the filter UX for
"missing" literal values or ranges, unlike entity facets where we do
not have the row_name info to display unknown entities.

**Comment by RFSH** [comment]
I realized that this issue was mainly talking about how to produce the augmented facet blob, and not how to consume it. So I marked the previous two comments related to that topic as hidden and moved the content to #2077. I'm also working on updating the body of this issue to reflect our latest conversations.

**Comment by RFSH** [comment]
The changes related to this have been merged into master.
