### ISSUE TITLE
CFDE: Suppress CSV export per table

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2100]
Currently the csv option is hardcoded in chaise and there's no way to customize or suppress it. In this issue we want to introduce a way to suppress it per table.

<details>
<summary>To see the first suggestion click here (we decided to not do this)</summary>
Since eventually we want to have an option to override the heuristics for the csv, the solution should be future proof. The following is how export annotation looks like, and where we can add a new attribute for this:

```js
"tag:isrd.isi.edu,2019:export": {
  "detailed": {
    // to turn off csv:
    "default_csv_option": false,
    
    // to customize csv:
    "default_csv_option": {
      "displayname": <chaise-display-name>, // name displayed in dropdown menu in the client
      "output": {
        "source": {
          "api": <ermrest-query-type>,
          "path": <optional-ermrest-predicate>
        }
      }
    },

    // what we currently have:
    "templates": [
      {
        "displayname": <chaise-display-name>, // name displayed in dropdown menu in the client
        "type": <FILE or BAG>,
        "outputs": [
          {
            "source": {
              "api": <ermrest-query-type>, // entity, attribute, attribute-group
              "path": <optional-ermrest-predicate> // used to represent more complex queries
            },
            "destination": {
              "name": <output-file-base-name>,
              "type": <output-format-suffix>, // FILE supports csv, json; BAG supports csv, json, fetch(?), download(?)
              "params": <params> // conditionally optional
            }
          }, ...
        ]
      }
    ],
  }
}
```
</details>

**Comment by jrchudy** [comment]
If the default csv is hidden and there are no other options configured, the export menu should be hidden from record/recordset page.

**Comment by RFSH** [comment]
We discussed about this and @hongsudt mentioned that adding an extra attribute is unnecessary. If CSV download honors the visible-column in `export` context, then data-modelers should be able to just define an empty visible-columns list in `export` to turn of CSV download option.

So in order to suppress CSV export you would do
```json
"tag:isrd.isi.edu,2016:visible-columns": {
  "export": []
}
```

I implemented this in [`csv-download-honor-vis-cols`](https://github.com/informatics-isi-edu/ermrestjs/compare/csv-download-honor-vis-cols) branch. There are two things missing from it:

- If `export` context is missing, currently we're using `detailed` context. Does that make sense? or in recordset we should use `compact`?
- New test cases
