### ISSUE TITLE
Possible bug when running automation tests

### ISSUE THREAD

**Issue by mashuaihh** [informatics-isi-edu/chaise#217]
## Unexpected alert open

This might be a bug but it only appears when doing automation testing and I cannot reproduce the error manually on the Chaise dev website.

In the test, the mouse clicked on **'Mouse Genotype'** and then clicked on **'Wnt1-Cre;Alk5fl/fl'**. After clicking **'Wnt1-Cre;Alk5fl/fl',** the pop-up alert window appeared.

Can anyone give me some ideas what might go wrong here?
Thanks.

![screen shot 2016-03-01 at 6 04 20 pm](https://cloud.githubusercontent.com/assets/7037762/13448476/74bc9620-dfd8-11e5-92df-6f2cdee22e7b.png)

The whole video can be viewed here:
http://saucelabs.com/jobs/16355f25c1514291be501b2e8d441cd7
(you have to choose the screenshot to watch)

**Comment by karlcz** [comment]
Is this error still reproducible in the automated testing or was it transient?

The not found page in the popup is a generic one generated by Apache HTTPD, not by our service.  That would usually indicate a pretty severe error in the URL prefix to prevent it even being dispatched to our code, or a server configuration error leaving ermrest absent from Apache's URL hierarchy.

We migrated the dev.misd host to dev.isrd.isi.edu yesterday and there was a period of time where the Apache HTTPD configuration was not complete and the ermrest service would in fact have been unavailable.

You should also update your tests in general to use the new permanent host name dev.isrd.isi.edu instead of dev.misd.isi.edu.

**Comment by mashuaihh** [comment]
@karlcz Thanks for replying so fast!

This error happened about 4 out of 5 times when I run the test on it today. Two weeks ago the tests were all good. But the pop-up might be because of my incorrect usage of testing syntax and I will look more into it on Thursday.

I will update the host URL to dev.isrd.isi.edu first to see whether it would fix the issue.

**Comment by karlcz** [comment]
I think a flaw in the server configuration was fixed today and this test should no longer fail. Please verify.  The exact error was that URLs including a value with a `/` encoded as `%2F` were being decoded by Apache before we could process them, due to a missing `AllowEncodedSlashes on` configuration directive.

**Comment by mashuaihh** [comment]
@karlcz Thanks, I will verify it as soon as possible.

**Comment by mashuaihh** [comment]
I tested several times today after changing host URL to dev.isrd.isi.edu and no errors have come up so far, so I think it might be fixed now. Thanks.
