### ISSUE TITLE
Optimize position of login popup for multi-monitor setups

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2189]
Recently I changed where we're positioning the login popup as part of [this commit](https://github.com/informatics-isi-edu/chaise/commit/3ca897a2451595c2142c624fb8d1af12641f7f83).

While this will ensure the popup is displayed in the center of the screen for typical single-monitor setups, it fails to position it in a multi-monitor setup.

This behavior is also not consistent between browsers,

- In Chrome, if you open the popup from your primary monitor, it correctly positions it. But if you do it from the secondary monitors, it will fail to center the popup (it shows the popup on the same monitor).

- In Firefox, as long as you have more than one monitor, it fails to position the popup properly. It also opens the popup on a different monitor than the one you're looking at.

Therefore, we should look into other ways to position the popup in multi-monitor setups. I tried some of the solutions mentioned [here](https://stackoverflow.com/questions/16363474/window-open-on-a-multi-monitor-dual-monitor-system-where-does-window-pop-up) and [here](https://stackoverflow.com/questions/31859280/dynamic-height-in-javascript-popup-window). But all of them are making assumptions about the number of monitors or their orientation.

**Comment by PoornimaVKrishnan** [comment]
Current Implementation :
We are subtracting screen width and popup width and dividing it by two and giving that as the left position to centre the popup. This approach will not work in multi-monitor setups as we need to add primary screen width to the left offset.
const popupWidth = Math.min(800, screen.availWidth);
const popupHeight = Math.min(750, screen.availHeight)
const topOffset = 50;
const popupLeft = (screen.availWidth - popupWidth) / 2;
// top should just have some small offset if there's available space
const popupTop = (topOffset + popupHeight) < screen.availHeight ? topOffset : 0;
const win = window.open('', '_blank', `width=${popupWidth},height=${popupHeight},left=${popupLeft},top=${popupTop}`);
// focus on the opened window
win?.focus(); 
// keep track of the window, so we ensure only one is opened at a time. 
popupWindowRef.current = win;
_logInHelper(win, postLoginCB, 'popUp', null, logAction);

Different Approaches I tried:
1) Approach: Tried calculating popup position based on window resolutions.
     Problems Faced: It was causing problems when it is a single screen and if window is minimised the pop takes up the entire screen area.
Link referred: https://stackoverflow.com/questions/4068373/center-a-popup-window-on-screen

2) Approach:

We need to add left offset to centre the popup on secondary monitor. Left offset is the width of the first monitor. Tried calculating based on screen resolution. Used screen. availLeft - (Returns the first available pixel from the left side of the screen.)
const left = Math.max(0, (screen.availWidth - popupWidth) / 2 + screen.availLeft);
const openedWindow = window.open('', '_blank', `width=${popupWidth},height=${popupHeight},left=${left},top=${popupTop}`);
if (openedWindow && openedWindow.focus) {
  openedWindow.focus();
}
This approach gave the expected behaviour in Chrome and Firefox. It centres the popup and opens the popup in the right window.
Problems Faced: .screen. availLeft is non-standard API and we cannot use it
Link referred: https://developer.mozilla.org/en-US/docs/Web/API/Screen/availLeft

3) Approach: Used window.screenLeft instead screen.availLeft
Problems Faced: In a single screen scenario, if your current window is in the middle of the screen, the popup will show up to the right of it.

4) Approach: Tried to build a wrapper for screen.availLeft.
we have to calculate the width of the primary screen as well to centre it on the secondary monitor and add that width to the horizontal offset.
Now the challenge is if the secondary screen is on the right or left of laptop. Based on which we have to calculate right and left offset.

screen.availLeft does the same:
If you work with two screens this property, evaluated on the right screen, returns the width of the left one in pixels (thereby indicating the X coordinate of the left edge of the screen on the right).

[1] [2] - on left screen availLeft returns 0, on the right screen it returns the width of the left one

[2] [1] - on left screen availLeft returns -width of that screen, on the right screen, it returns 0
For this we don't have a built-in approach to calculate width of primary screen if the window is on secondary monitor. There are third-party solutions like:
 npm packages screen-info. It is a very old repo and uses python2. 
window.getScreenDetails() - This gives the screen details and details of screens connected to the monitor. But this is non-standard and works only for chrome.

Overall, in my investigation there are solutions more based on window parameters than screen
