### ISSUE TITLE
Allow float values in "from" and "to" inputs of integer facet range picker

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2232]
In the facet range picker, we allow users to input "from" and "to" values to filter based on a range. The inputs are currently tied to the type of column. So if the facet is showing an "int" column, users can only enter integer values in these two inputs.

Does this make sense? Should we allow users to input float numbers? Would this break the ERMrest requests that we're generating?

**Comment by jrchudy** [comment]
I did some investigation for this issue and it turns out the request we are sending to ermrest also expects the search values to be of the same type as the column we are searching over. 

For instance, I created a table with an integer column with values ranging from 1 to 30. When I modified the inputs in the integer facet range picker to allow for float values, I received a `400 Bad Request` response for the following query when trying to search on an `integer4` column:
```
https://dev.derivacloud.org/ermrest/catalog/82106/entity/M:=histogram-faceting:main/int_col::geq::4.5&int_col::leq::9.9/$M@sort(RID)?limit=26
```

The response:
```
400 Bad Request
Request malformed. Detail: Invalid int4: "4.5"
```
