### ISSUE TITLE
General presentation for content preview and asset download

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#230]
We need a more general solution to present the common UX idiom of an entity having a content preview and optional download for the bulk asset being previewed in the browser.
* content summary variations such as thumbnail images or other complex viewers embedded in iframes.
* multiple assets being available as different encodings of the same conceptual content e.g. multiple file formats. 

We should consider how best to organize the constituent elements in our ERMrest catalog data models as well as how to enable and/or configure the presentation.

**Comment by karlcz** [comment]
I am wondering if we should start storing a `jsonb` column that combines the various aspects here, to allow the UI to continue to follow simple column-by-column presentation decisions.  Consider a hypothetical column value like this:

```
{
   "img": URL0,
   "links": {
     "caption 1": URL1, ...
  }
}
```
Some annotation at the column level in the model could enable us to process this JSON content and activate the right angular template to:
1. Display _URL0_ as an inline image tag
2. Display the downloadable URLs each with their own caption as the link text or button label
3. Either different annotations or just duck-typing rules could handle variants like having an `iframe` field instead of `img` to enable different display modes for _URL0_.

Thoughts?

**Comment by robes** [comment]
A lot of our current URLs are actually patterns that insert the value of one or more cells, like a pubmed column that takes the value of the cell and and inserts it into something like this https//path/to/pubmed/{pubmed_id}.

I don’t follow how we would do something like that or if this is even intended to address that need.

**Comment by karlcz** [comment]
I'm not sure that those cases overlap with asset preview and download. These are substantially different UX and may well be served by different annotation and presentation templates rather than trying to treat all URLs the same.

**Comment by shinyichen** [comment]
Is the asset information already defined in the schema?

**Comment by hongsudt** [comment]
I don't think so.. @bugacov can we define the schema?

**Comment by karlcz** [comment]
@hongsudt @robes @shinyichen @bugacov 
I've updated the annotation document in https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2015-url to reflect our latest meeting. We think that enhancing the implementation to better correspond to this specification and its small enhancements will support the current use cases we know about.
1. Suppressing URL presentation when patternsreferences NULL values in a data record
2. Supporting the array of URL presentation objects in the annotation; the ordered set of annotation objects yields an ordered set of URL presentations. Each presentation can use any of the presentation modes and different patterns without limitation, i.e. multiple embeds, download buttons, thumbnails, etc.
3. Enhancing the url and caption to allow an array of patterns. This will allow a single download button to offer an array of download links for different types of file, rather than cluttering the page with many independent download links.  That's our first implementation goal.  Carousel presentations might be meaningful for embed or thumbnail modes with arrays of patterns in the future...?

**Comment by bugacov** [comment]
what do you mean? there's an asset schema already.
but do you refer to the actual annotation?
Alejandro.

**Comment by bugacov** [comment]
tested this on gpcr stating and is working well 

https://staging.gpcrconsortium.org/chaise/record/#1/gpcr_browser:biomassprodbatch_gui/title=IMPT-13480

The location of the "download" button can probably be improved as is hard to see to which element the download corresponds. One solution might be to add a thin horizontal line to separate items. Another one can be to place it to the left of the caption? But that might create other problems depending on length of the caption? 
In any event I think this feature can be merged

**Comment by hongsudt** [comment]
Can we configure to have the download button on top instead of on the
bottom?

**Comment by crisaless** [comment]
I feel the Download and Reset buttons should be on the same line, below the plot, left-aligned.

**Comment by hongsudt** [comment]
And can we add some space between the two iframe sections? Or add boarder
around the iframe?

**Comment by meihuisu** [comment]
Download button is actually in angular level and so it is not like just move the button into the
plotly's iframe. Have to setup message passing like RBK between outside and within the iframe.

mei

----- Original Message -----

**Comment by karlcz** [comment]
Actually, I don't think reset and download make any sense together, even if we could do that.  If anything, I think the reset button should go up above the controls, closer to the plots that are being controlled, perhaps in the area to the right of the plot.

**Comment by meihuisu** [comment]
At first, I thought the download button is for downloading the plot.


----- Original Message -----

**Comment by bugacov** [comment]
In this case, the download button is for downloading the source FCS file
that was used to
generate the plot (which in a sense it is a plot) but to download the image
of the plot as jpg, etc).

So, yes, the download and reset buttons together makes it confusing.

Alejandro.

**Comment by carlkesselman** [comment]
Right.  I think having the download button being separate from the plot is the right thing to do.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Mar 22, 2016, at 9:42 PM, meihuisu <notifications@github.com<mailto:notifications@github.com>> wrote:


Download button is actually in angular level and so it is not like just move the button into the
plotly's iframe. Have to setup message passing like RBK between outside and within the iframe.

mei

----- Original Message -----

**Comment by crisaless** [comment]
Right, I thought download was for the plot too. The button should say "Download Source" to make that clearer.

We really need to do more user testing. I'll create an issue to start gathering names of potential user testers.
