### ISSUE TITLE
Filtering on the Date Type

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#2306]
We have at https://dev.pdb-dev.org/chaise/recordset/#99/PDB:entry@sort(RCT::desc::,RID) `2` records that have the `Submitter Flag Date` equal to `2023-04-25`.
The filter panel lokks:
<img width="423" alt="Initial" src="https://user-images.githubusercontent.com/1609577/234425817-0636965d-3600-4602-9f41-b19eea8927ab.png">

Is it OK on the `x` coordinate the date `2023-04-24` to appear twice? Also the date `2023-04-25`?
Is it OK on the `y` coordinate to appear `1` twice and `2` twice?

When we are checking the box at the specified range, we are getting:
<img width="422" alt="Range" src="https://user-images.githubusercontent.com/1609577/234425869-88562bb9-8272-4214-820c-4895933dd162.png">

**Comment by jrchudy** [comment]
This is happening for the `yaxis` because plotly is trying to display more "ticks" than it needs to. By turning the "tick" formatting off, I was able to see the yaxis labels as `[0, 0.5, 1, 1.5, 2]`. The formatting was rounding up these half values.

In the old implementation, plotly was automatically setting `tickmode: linear` based on the data type used for the axis.

This is expected in the case of the `xaxis` in very small ranges of data.

**Comment by jrchudy** [comment]
@svoinea Changes to fix this issue have been merged into master and should be available after the next hourly update.

**Comment by svoinea** [comment]
@jrchudy I have tested and looks good.
