### ISSUE TITLE
Allow input value to be copied to selected rows instead of all rows

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2320]
We can set the value for all the forms with the "set all" button in recordedit. In this issue, we want to allow users to set values for specific rows.

This is how it could be done:
- User clicks on the pencil button to open the "set all" UI.
- User selects the value the same way that they currently do.
- We should allow users to select the specific row to which they want the data to be applied. **This requires exploration**. Since we're disabling the inputs, we could allow users to click on each input to select the row that we want the data to be applied to.

**Code details**

[This](https://github.com/informatics-isi-edu/chaise/blob/master/src/components/recordedit/form-container.tsx#L360) is the callback that will set the value of all the inputs. Instead of doing this for all "forms", you would have to selectively do this for the forms that user has selected.

**Comment by PoornimaVKrishnan** [comment]
Action points from the meeting:

1) Implement two Radio Buttons `Select All` and `Select None` and a button `Apply` to apply the changes. Select All will select all the forms and we can deselect from it if we don't want to apply the change to that particular form.  Select None is to deselect all the forms. 

Questions: By default should we have all selected or none selected?

2) Figure out a way to know the form is clickable

3) Experiment `Clear All` button to clear the text from forms

Question: Should we clear text from selected forms or from all forms?

**Comment by PoornimaVKrishnan** [comment]
@RFSH
MOM from todays scrum call:

Move the i icon close to the checkbox label as we are explaining more on how the selection and deselection works
On resize of the textarea the controls on the top(i.e the buttons and checkbox) should also move
Tooltip for checkbox and label should not show once an interaction(i.e a click on checkbox) is made.
Also, in facets we are not making the checkbox label also clickable but in github it is clickable. We have to decide whether we should make it consistent with github or the chaise app
Where should the tooltip be aligned to in all cases(top, bottom, right, left)?
Pending items:

Updating the selection on removing form
Above items from the meeting
A bug which I found: On load one form is selected by default, one deselect of that checkbox is in indeterminate state instead of empty with Select All text
Also please check the tooltip text:

const renderHelpTooltip = () => {
    const splitLine1 = 'You can click on the form to select it and apply changes to it. '+ 
    'You can use the checkbox to select and deselect all records'
    const splitLine2 = 'By default, if there is no previous selection, the first form will be selected. '
    const splitLine4 = 'After the forms are selected, ' + 'you can click Apply button to apply the changes to selected records.'
    const splitLine3 = 'You can also clear the values for selected records by clicking ' +
     'on Clear button.'
  
    return (<>
      <p>{splitLine1}</p>
      <p>{splitLine2}</p>
      <p>{splitLine3}</p>
    </>)
  }

**Comment by PoornimaVKrishnan** [comment]
@RFSH 
I have explored few options more to compare sort range feature similar to google sheets. 
1) [Airtable](https://airtable.com/)
This is a better option where we can show the sort criteria as a dropdown instead of a Modal. We have a **Sort by** label on the top and dropdowns for columns and sort order. We also have a search capability in the column dropdown. 

https://github.com/informatics-isi-edu/chaise/assets/133336338/bf9eb5ee-3007-41c7-84ce-88fc8bdc2396

2) Zoho Sheets
This option is very similar to what we have currently. Attaching screenshot for reference.
<img width="1431" alt="Screenshot 2023-08-25 at 2 18 42 PM" src="https://github.com/informatics-isi-edu/chaise/assets/133336338/1c50166e-c783-41e5-84ed-a6e0cb6f3ac2">

3) [Microsoft Excel](https://www.office.com/launch/excel?auth=2)
This opens up a modal for customized sort with dropdowns for columns and sort order.

https://github.com/informatics-isi-edu/chaise/assets/133336338/573a24f6-9205-46b4-a656-351fd0d8f03b

Overall, Airtable option is more feasible as we have pretty much everything what we need in a neat and clean way. Open to suggestions.
