### ISSUE TITLE
Unable to select text on Chrome and Safari

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2344]
## Summary
Since migrating to React, the text selection on chaise pages only works by double-clicking on the first word and pressing the shift left arrow to highlight text (you cannot just select text by holding down the mouse left-click and moving the cursor). You can see this behavior on Chrome and Safari but not Firefox.

## Details
Use the `angularjs` branch to deploy and compare the old apps. The main difference between the two is the bootstrap version, but as far as I could tell, that alone is not the issue.

**Comment by PoornimaVKrishnan** [comment]
@RFSH 
I debugged this . Below are the steps I followed:
a) I first checked if there is any `user-select:none` for the whole body of html. It was not there
b) I checked if there is any overlay present causing this .
c) Then I figured out, the issue was only there wherever split-view is present. I cross checked for mouse events and found the solution. The issue was we are having `e.preventDefault()` on `mousemove` event in split-view.tsx. I removed it and checked, we were able to select text on chrome and safari.

Let me know your thoughts on the next steps

**Comment by RFSH** [comment]
Thank you for explaining the process of finding the issue. I'm not sure why we never realized that having the `e.preventDefault()` for such a general event handler is a bad idea.

After reviewing the `split-view.tsx` code, I realized that the `e.preventDefault()` was most probably added to avoid text selection while the user dragged the text. So instead of removing it, I moved it to be inside the check that we already have. 

I pushed the changes for this directly to `master` branch.
