### ISSUE TITLE
Annotation Viewer - Text labels - frame dissociates from text

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#2360]
Steps:
1. click the text tool
2. click on image to place the text label
3. click in label's box
4. enter some text
5. click outside the box anywhere else on the image

Box should relocate but text should stay where it was.

<img width="1674" alt="Screenshot 2023-09-27 at 4 19 50 PM" src="https://github.com/informatics-isi-edu/chaise/assets/4202842/35344cbf-b31e-4c91-9d12-e75c9d2c2aa9">

**Comment by RFSH** [comment]
We had a conversation about this on Slack and the following is the summary of it:

This is the expected behavior. When you click outside the box, we save the existing text and initiate a new drawing. This allows users to create multiple text annotations at the same time. It's also similar to how our other drawing tools work, where you can continue adding a new instance one after another. However, given the complexity of the textbox, it's less obvious than our other drawing tools.

From Rob
> Ah so it is starting a new [text] drawing? yeah, I wasn't expecting that.
> so maybe its a feature rather than a bug...
> I'm expecting something a bit more like adding a text label in power point.
> - text cursor only positions within text
> - move cursor only moves box
>
> For comparison, Lucid is a little different. It starts with move cursor then you have to double click to activate the text cursor to select within the text (Google drawing is kind of like PPT too).

We are going to discuss this in our Chaise meeting and I'll update this comment with more info.

**Comment by RFSH** [comment]
After discussing this in the Chaise meeting, we decided we will not change this behavior. As I mentioned in the previous comment, this behavior is consistent among all our drawing tools, and we want to keep it consistent. If we realize this feature is unnecessary and more confusing, we should consistently change this for all the drawing tools.

To make this easier to understand, we're now changing the cursor to "+" in draw mode. So users would know that clicking on the image would add something to the page and not move it. This is similar to how the line/arrow/polygon/etc draw tools work on Google Draw.
