### ISSUE TITLE
Navbar submenu stays open

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2363]
To reproduce this behavior go to [staging.atlas-d2k.org](http://staging.atlas-d2k.org/):
 1. click `Data` navbar menu option
 2. click `Imaging` to open the sub-menu
 3. right-click to open the context menu and select "Open Link in New Tab"
 4. then click another sub-menu like "Transcriptomics"
 
 The first sub-menu for `Imaging` stays open (and moves) to show behind the new sub-menu.
 
 Found on MacOS with Chrome.

**Comment by ladukaraniket** [comment]
## Issue
- This is a commonly occurring issue with the Dropdown in react-bootstrap. This can also be reproduced on the examples given on the [react-bootstrap doc site](https://react-bootstrap.netlify.app/docs/components/dropdowns/#dropdown)
- When the user right-clicks on a menu item in `Dropdown A`, iteracts with the context menu and proceeds to open another `Dropdown B`, react-bootstrap fails to close `Dropdown A`. This causes multiple dropdowns to be visible together.

## Fix
- Since we already assign unique keys to each dropdown, we can use this to track the most recently opened Dropdown.
- We further force only the most recently opened dropdown to be visible using the `show` property of the Dropdown.
