### ISSUE TITLE
Null values shown in 'detailed' context for json columns

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2394]
When a json column has a `null` value, it is being shown in `detailed` context like the following:
<img width="418" alt="image" src="https://github.com/informatics-isi-edu/chaise/assets/2932600/ddc3364b-c882-4961-aa0b-2ab32b8864bc">

To avoid showing this, a markdown pattern can be written but that prevents `ermrestJS` from wrapping the contents in `<pre>` tags making the json object get "pretty printed".

This is related to another issue (#1893) about show_null behavior in record app

**Comment by RFSH** [comment]
I spent some time looking into this, and the following is the summary of what I found out:

## ermrest

  - While creating data, we can send JSONB null or database null (sending `null` or not sending anything).

  - We can distinguish the two through ermrest API (`=null` for JSONB null and `::null::` for database null).

## Record/Recordset

The JSON response from ermrest doesn't tell us whether it's database null or JSONB null. The only way that we could figure this out is by sending a separate request. In read-only mode showing empty is cleaner, so we should treat it as database null.

## Recordedit

- While you can write "null" or leave it empty in the form for JSONB columns, we're not treating these differently. Both are treated as if the value is missing (database null)

  - Which means the "default" logic would be used for them.

  - Chaise won't complain when you use `null` for required columns, but then since null and undefined are treated the same in ermrestjs, we're adding the column as one of the "defaults" so ermrest will eventually complain.

  - Currently, we're setting empty fields as `null` in chaise. But if we were to use `undefined` instead, ermrestjs could distinguish between the two.

- During update, chaise will only update the values that have been "touched"; as long as the column has not been touched, the database value stays the same.
The change detection uses `!=`, which needs to be changed when we do the "null" vs. "undefined" change for JSONB columns.
  - So, if it were database null or JSONB null, it would stay the same. And you cannot change it to be the other one.

**Comment by RFSH** [comment]
We discussed this, and the following is the summary of it:

- [ ] We should stop treating `json`/`jsonb` columns differently in read-only modes. So, a `null` value should be treated like a database null, and therefore, we should honor the `show_null` annotation for it (instead of forcefully showing the `null` in a code block).

- [ ] Related to recordedit, if it doesn't require a lot of changes, we should distinguish between writing "null" and leaving the input empty in `json`/`jsonb` columns. Writing "null" should save a `null,` and leaving the input empty should not send any values for it (similar to other inputs). While chaise won't show different values for these cases in record/recordset, we should ensure we're doing the right thing in recordedit.


P.S. We don't need to worry about the change detection I mentioned above for this issue. We should tackle that as part of [this issue](https://github.com/informatics-isi-edu/ermrestjs/issues/463), and we most probably should use dirty/changed flags for that instead of doing the check in ermrestjs.
