### ISSUE TITLE
Display data in diamond shape

### ISSUE THREAD

**Issue by Zhiweiii** [informatics-isi-edu/chaise#2422]
I have a question regarding Eye-AI multimodal data handling, particularly when dealing with data represented in a diamond shape. I have several columns of such data, and I'm looking for guidance on how to store and display them properly in the UI.

The data is in a mix of numeric values and symbols, including "<0", ".", etc. And the position of each data point matters. They should be aligned horizontally and vertically. These data come from the OCR of Visual Field reports. I attached the report; you can find what the diamond data looks like. The raw data format is attached in Excel. 

Thank you very much for your help and assistance!

[hvf_sample.xlsx](https://github.com/informatics-isi-edu/chaise/files/14797586/hvf_sample.xlsx)
![HVF_sample_report](https://github.com/informatics-isi-edu/chaise/assets/109121987/f5a47a20-97de-44b8-b9f7-4f847a89ca82)

**Comment by RFSH** [comment]
@Zhiweiii It would be much easier if you give us a link to the table that has this data. So we can play with the markdown values that would work the data.

**Comment by hongsudt** [comment]
Let's assume that the data will be stored in 2D array (or json) like @karlcz  suggested.  @Zhiweiii can you put one of the simple 2D arrays here (data not image). The process will be the same for other  arrays.  Let's pick the one that is sometimes positive and sometimes negative to demonstrate padding.

**Comment by Zhiweiii** [comment]
Here is an Example: 
https://dev.eye-ai.org/chaise/record/#eye-ai/eye-ai:HVF_Report/RID=2-5QT4
The raw string format is in the column "string diamond". The `jsonb` column is called "array diamond".

**Comment by RFSH** [comment]
@Zhiweiii 
The main challenge of showing this value is the number of whitespaces that should be printed. Given that the numbers might have different lengths, in the final diamond the numbers should be padded based on the length of each number (and the maximum length of numbers).

When we mentioned a JSONB column, we didn't mean what you currently have. Ideally, it should be an array of arrays. So something like

```
[
  [ "",  "", "",  "2", "2", "4", "4",  "", ""],
  [ "",  "",  "3", "1", "1", "1", "0", "1", ""],
  ...
]
```

Now, the question is whether the Python code should do the padding or should  we add the padding when we're creating the code block in Chaise. This is something that you should decide depending on how you want to save the data.

- If the data is going to be already padded, the `markdown_pattern` that you would add would be like the following:

  ```
  {
    "source": "array_diamond",
    "display": {
      "markdown_pattern": "```\n\n{{#each array_diamond}}{{#each this}} {{{this}}}{{/each}}\n\n{{/each}}\n```\n",
      "template_engine": "handlebars"
    }
  }
  ```
  - I'm adding a whitespace before each value. If you want more, adjust the number of ` ` before `{{{this}}}`.


- If the data won't be padded, you can use the new handlebars function that I just added ([`printf`](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/handlebars.md#printf-helper)) to do it for you:

  ```
  {
    "source": "array_diamond",
    "display": {
      "markdown_pattern": "```\n\n{{#each array_diamond}}{{#each this}} {{#if this}}{{printf this "%4d" }}{{else}}     {{/if}}{{/each}}\n\n{{/each}}\n```\n",
      "template_engine": "handlebars"
    }
  }
  ```
   - Same as previous one you should adjust the white space before the number.
   - I'm using `%4d` because I'm assuming at most four digits. Change that if that's not the case. Also this only works with numbers and doesn't do what we want for `""` values. That's why I'm guarding against it and adding four whitespaces in the `else` case.


P.S. In the record page you linked, I see a "string diamond", which I'm assuming is the previous attempt at showing the diamond. If you use `markdown_pattern` and wrap that in a markdown block (```), it should preserve the space and show the diamond (assuming it has the correct number of whitespace/newlines).
