### ISSUE TITLE
handle the error case when the status is 0 and there is no response text

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#275]
Jill reported this problem when she tried to change the search criteria. See her description and screen capture in the document below. 

[RBX error message 031716.pdf](https://github.com/informatics-isi-edu/chaise/files/207581/RBX.error.message.031716.pdf)

@svoinea suspected that this was due to the slow network.

**Comment by crisaless** [comment]
note this error was originally reported on March 17th (notification was lost in my Microsoft Clutter folder) so it may no longer be an issue

**Comment by hongsudt** [comment]
It is an error handling issue.. Until we handle it properly, there will be chances of recurrence.

**Comment by robes** [comment]
So there are two aspects to this issue:
1- the error
2- how we handle the error

For 1, does this really look like a slow network problem? I'm curious to understand more of such an error if that is really the case. I.e., what part of the stack generates such an error - the browser, angular, etc? Just to rule this out, could this have been due to the slash encoding configuration that was fixed?

For 2,  would it help if we had a catchall for errors that we haven't anticipated encountering? I would say that no error that we encounter should result in an alert box. We should at least have a default catch all error handler in our apps. But the generic error handler should log enough information to the client display and/or to the browser console that we can diagnose it.

And then, along those lines, now that we have seen this error, we should have a handler for it specifically.

**Comment by karlcz** [comment]
If I'm not confused, status 0 in ajax usually means a communication
error, i.e. TCP connection error or timeout.

Communication errors are *always* a possibility and we need to deal
with it by retrying requests (and thereby connections) and degrading
gracefully and functioning without the resource(s) we have yet to
retrieve.

**Comment by robes** [comment]
Right. Need error handling for this in chaise. (And even if we do add retry logic built into ermrestjs, this is still an error that chaise apps will see eventually even after retries.)

**Comment by karlcz** [comment]
Also, our apps need to understand it is async and there is a period of time where you don't know if it is slow, failing, or lost. On communicatin errors, you don't even know whether the request got processed on the server or not. (It might have gone either way and the response got lost on the network. This matters most for PUT/POST/DELETE where an attempt to "retry" is going to have to understand other error conditions since these are not always idempotent.)

**Comment by hongsudt** [comment]
@svoinea what's the progress on this?

**Comment by hongsudt** [comment]
Mark this as won't fix.
