### ISSUE TITLE
Recordset app to use column header link for sorting

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/chaise#278]
Previous implementation for sort by column was using a drop down filter. We want to improve the usability by making column header clickable for sorting.

**Comment by robes** [comment]
is this change in a branch? i deployed master but don't see the change you describe.

**Comment by robes** [comment]
Overall its working well. A few minor comments about it:
- would be nice when the cursor hovers over the column header, that it would change to a cursor icon that indicates it is clickable
- would be good if there could be some padding in the column header so that the sort asc/desc icon would not wrap or cause a resize; i think i've seen some suggestions for using a blank icon as a placeholder to keep the ui from shifting
- i think the URL should be updated at the same time the 'permalink' is updated, so when user sorts on a column that should be reflected in the URL in the location bar as well as in the permalink
- when sorting on a large result set we should probably show a 'loading' indicator so that the user knows something is happening because there is significant latency for the sort to go into effect

**Comment by shinyichen** [comment]
Is the permalink link still necessary if we keep the location bar up-to-date? @robes

**Comment by robes** [comment]
Yes. We still use the permalink because the browser location bar can’t be trusted to copy from because browsers may encode/decode characters.

**Comment by shinyichen** [comment]
Please see latest recordset branch @robes

**Comment by robes** [comment]
This is still putting the sort order into the history. I thought from this morning we wanted to just replace the history so that we don't grow the history stack? I'll wait to close this and reassign.

**Comment by shinyichen** [comment]
It's updated now. @robes

**Comment by robes** [comment]
works well
