### ISSUE TITLE
Cached application code problem

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#28]
Whenever we redeploy Chaise and want to use it right away we have to use the browsers 'clear cache' feature otherwise we will just be using the browser's currently cached version of the .js files it loaded previously.

First, we need to identify the best strategy to avoid this problem. For instance, once basic approach out there is to always deploy your new code to a new path, e.g., path/to/v#/myscript.js where v# is some version number. Then we need to fix the deployment procedure for Chaise. This should be scripted so that with a single command we can (re)deploy Chaise. No manual steps should be involved.

**Comment by karlcz** [comment]
Yes, and having per-file versioning can be more friendly to caches by
avoiding the version number change for content that doesn't change
between releases.  There are probably a lot of 3rd-party files
including icons and other bulky assets we change infrequently compared
to others...

**Comment by howdyjessie** [comment]
After Googling around, per-file versioning seems to be the standard way of solving this issue, in which we append a hash to the names of files that have changed since last release to force the browser to redownload. Since we're already using Gulp in the ermrest.js repo, can we use it here as well (and with #31 )?

**Comment by robes** [comment]
we aren’t using gulp. does that have a feature for this?
