### ISSUE TITLE
Recordset link to records

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/chaise#293]
Link recordset rows to records in the record app.

**Comment by karlcz** [comment]
I think we should be careful to consider how we want cross-record navigation to work and design a consistent UX for this in all apps.

I don't think it should default to the whole row being a link to that record, because rows can have foreign keys in them and these ought to allow navigation to the referenced entity rather than the referencing entity...

**Comment by robes** [comment]
For starters, the two trivial cases to support are:
1. if a column is a PK (i.e., unique), then turn it into a link to the record page, for the same table, filtered by that PK
2. if a column is a FK reference, then turn it into a link to the record page, for the related table, filtered by that FK

**Comment by robes** [comment]
I realized that my trivial cases were not generalizable, so I'm deleting my earlier comment. I think the only trivial case is to make the entire row a link to the record page for that row. This might seem to contradict karl's earlier comment, but if there are foreign keys those can be turned into links to the record page for the related entity linked by the foreign key, and they can override the behavior of linking the entire row. However, this is not a trivial case. I'd like to narrow the scope of this task merely to linking the entire row to the record for the row, since that is the only trivial case to handle. The rest of the non-trivial cases can be reviewed and discuss.
