### ISSUE TITLE
Recordset address bar and history stack

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/chaise#295]
Update the address bar with user interaction but not keeping the history stack (no back button)

**Comment by robes** [comment]
The update to the permalink and history stack are being done correctly, but you'll still need to implement the callback for the onhashchange and force a reload when the hash change was caused by something outside of your page. Example: 

1. go to https://dev.isrd.isi.edu/~schuler/chaise/recordset/#1/legacy:dataset
2. now change it to https://dev.isrd.isi.edu/~schuler/chaise/recordset/#1/legacy:file

After 2, when you hit the [enter] key, the page should refresh/reload but does not.
