### ISSUE TITLE
Serial columns should not allow user input

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#337]
The user should not be able to set or modify the values of the columns that are defined by the server or the database. Depending on the column this may or may not be shown to the user. Possibly create an annotation for which fields should be hidden to the user as well as one for whether modification is allowed.

**Comment by robes** [comment]
Let’s aim for good functionality based purely on sensible heuristics, first. Then, introduce annotations only to override the heuristics.

There’s room for debate here, but I would argue that a column that is “unique” (i.e., a key) and serial can be interpreted as a surrogate key, and a surrogate key is by definition not based on application data, and therefore we could assume it does not need to be displayed to the end user, hence by default it is hidden.

A heuristic could be introduced to override this by making a surrogate key visible. I am not advocating we introduce that heuristic right now, just giving it as an example.

**Comment by howdyjessie** [comment]
@robes Right now the app has the heuristic part (if column type begins with "serial", hide it). Would you say using an annotation to override heuristics is part of this "minimal epic" or will it be addressed in a later iteration?

**Comment by robes** [comment]
First, I would argue that the heuristic should be:
 - “serial” & “unique” = “surrogate key”
 - surrogate keys should be hidden

A “serial” type alone does not imply unique (primary key). And so if a column is serial (but not unique) it should be visible, in my opinion. Apparently when serial was first introduced it was implied to be a unique but that has not been the case for several versions of postgresql.

http://www.postgresql.org/docs/9.4/static/datatype-numeric.html#DATATYPE-SERIAL

To answer your question: No. The “visible” annotation should not be part of this minimal epic. We should put it on the wishlist of things we could do if someone had a good reason for wanting it in practice.

On 5/9/16, 3:00 PM, "Jessie Wong" <notifications@github.com<mailto:notifications@github.com>> wrote:


@robes<https://github.com/robes> Right now the app has the heuristic part (if column type begins with "serial", hide it). Would you say using an annotation to override heuristics is part of this "minimal epic" or will it be addressed in a later iteration?

**Comment by karlcz** [comment]
I think we're mixing topics here...

In the data-entry app, we want to disable data-entry for serial
columns because the "serial" type implies a sequence providing default
values.  It is not so significant whether it is a key or not.  We
don't usually want user input colliding with the generated sequence.

In other apps like record-set or search, we might want other
heuristics to hide "surrogate keys" as they are not very
user-meaningful. However, I don't think we should ever display
truncated records with no unique key material, so I would not hide
surrogate keys unless we have determined what natural key information
to display instead.

**Comment by robes** [comment]
What is the simple statement we can make right now?

- “serial” (which is just postgresql’s syntactic sugar meaning “default from XYZ sequence”) = show but do not allow user input, by default

If the “serial” is also “unique” we may want to hide it, but let’s decide later. For now, just don’t allow input on serials.

Is that a good enough start here?

**Comment by karlcz** [comment]
I think we're going to need an annotation for synapse because columns other than serial need to be blocked for data entry.  I wonder if we can just extend the "hide" annotation to have context and a boolean for that context.  Possible UX context might be:
  - create
  - edit
  - filter
  - display
And I think the boolean could be tri-state for always hide, never hide, or continue to use default heuristics if the context is not specified i.e. is left `null`, same as if the whole annotation was missing.

**Comment by robes** [comment]
Right, those make sense. I can see them being used by use cases like CIRM too.

**Comment by howdyjessie** [comment]
Key columns with a type of `serial*` are now displayed but do not allow input. Static text is displayed instead.

https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#1/public:form_test

**Comment by robes** [comment]
Functionally, good, but I have some comments on the code.

**Comment by howdyjessie** [comment]
@robes I simplified some of the code per your feedback email. Here's the relevant diff: https://github.com/informatics-isi-edu/chaise/commit/5c7dd60c2afe6d5cb998e05f9393f4267d38bfb2

And the link to look at the app: https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#1/public:form_test

**Comment by robes** [comment]
looks good. thanks
