### ISSUE TITLE
After submission, user should be redirected to record or recordset

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#338]
After the user submits the data and it is properly updated in the database, the user should be redirected to the record app if one entry was submitted or recordset if multiple entries were submitted.

**Comment by howdyjessie** [comment]
The data entry app now redirects to the record app when the user successfully submits data. The redirect url is built by selecting the key with the smallest number of columns and appending that key's columns and their values to a base url.

I haven't fully implemented the redirect to recordset yet because we don't support multi-row insertion yet. 

I have 2 questions for @karlcz and @robes:
- @karlcz says the best "primary key" to use in the redirect is one with the smallest colset and all its columns have a `nullok` of false. But what happens if only _some_ or _none_ of the columns have a false `nullok`? Should I calculate the key with the highest percentage of columns with false nulloks?
- Should I have also implemented the multi-row redirect to recordset?

**Comment by karlcz** [comment]
If there really aren't any keys that are completely nullok=false, that means there is no "primary key" and it's a pretty bizarre table.  All bets are off at this point, and I'd just take the shortest unique key as a fallback.

**Comment by robes** [comment]
In that ermrestjs pull request I recently created, I added that “simple” flag which can tell you if a key is made of a single column. But you can also look at the recordset app which picks the shortest key from the set of keys to link to the record app. This is something we should probably think about a good ermrestjs api…

**Comment by howdyjessie** [comment]
@robes Thanks for the heads up; the recordset app's way of finding the shortest key is a lot cleaner to read than my original for loop.

It would be nice to have some sort of "primary key"-esque flag in ermrestjs so that we don't duplicate the code to find this shortest key in multiple Chaise apps. Maybe it could be something along the lines of `table.[uniqueId | uniqueKey].get()`. If not, we could also abstract it away to the `common/` folder, but it feels strange to put this kind of key-finding operation in Chaise.

**Comment by jrchudy** [comment]
I tested this on @howdyjessie's dev environment on dev isrd and found a small bug that was fixed. Tested again after and it's working properly. I reviewed the code as well. 

It currently only redirects to record app as the form does not yet allow multiple rows to be submitted at once.
