### ISSUE TITLE
Search app generates invalid page key query to ERMrest

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#348]
Just visiting `https://synapse-dev.isrd.isi.edu/chaise/search#1/Zebrafish:Subject`  leads to this broken ERMrest request on the server: `GET /ermrest/catalog/1/entity/A:=Zebrafish:Subject/$A/Sub-Sequence=A&Issuer::geq::Dsy&Birth%20Date::geq::undefined;Sub-Sequence::gt::A/$A@sort(Sub-Sequence,Issuer,Birth%20Date)?limit=25`

It shouldn't be setting a filter for the first page.

**Comment by robes** [comment]
So there are probably 2 bugs with this I would guess:
1. that it sets a sort filter for the first page (unnecessary), and
2. that the filter's right-operand for the date is `undefined`.

Is it also using the longer 3-part key rather than picking the `Term` as a simpler key column? Seems to be.

**Comment by svoinea** [comment]
The bug was due to two distinct errors:
- getting values from column names having special characters (in this case spaces) of numeric and date type;
- building a predicate from a unique keys group where the keys might have also NULL values.

The errors were fixed through the commits b4b8c2102c785791504f62bd98dfb71a804d5fc1 and f2b132d09d610d1b340255f09c64bab57d0f0174.

**Comment by karlcz** [comment]
verified on synapse-dev
