### ISSUE TITLE
When user doesn't have access to site Error 403 is returned

### ISSUE THREAD

**Issue by akumar03** [informatics-isi-edu/chaise#353]
Here is screenshot when I logged in to gpcr-dev using my usc id.   The error page should be more informative

**Comment by svoinea** [comment]
Fixed in the commit e244a3cb362955cad2f209bfbc1d37db537e1fee.

A pop up window will now show up with the following message:
```
Access to the requested resource is forbidden.
Please contact the site administrator.
```
After clicking `OK`, the user will be redirected to the page mentioned by the `dataBrowser` parameter in the `chaise-config.js` file. If that parameter does not exist, the redirect will be to the `https://<host:port>` page.
