### ISSUE TITLE
Configure record/detail app link in listings on a per table basis

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#379]
Currently, the search app navigation to record app or view app is in a chaise config. We need to change this to accommodate the navigation at the table level, or schema level.  

The configuration hierarchy should be as follows (lower items override more general items above):
1. Default behavior of codebase is `record` app
2. Chaise config can override in a particular web server
3. Schema-level annotation can override in one schema of one catalog
4. Table-level annotation can override in one table of one catalog
5. ~~Foreign-key level annotation can override for one kind of outbound link on a single table?~~

See the [2016 Record Link](https://github.com/informatics-isi-edu/ermrest/blob/annotation-update/user-doc/annotation.md#2016-record-link) annotation draft.

If we need to fully customize how a an app link is formed, we should use the more general URL annotations to form links from templates, etc.

**Comment by karlcz** [comment]
BTW we need this to be consistent for search and recordset apps.  Should we file two issues?

**Comment by robes** [comment]
@hongsudt I would suggest dropping sub-item 5 from the list.
@karlcz yes, i think we will need 2 issues. i mainly think so because the code bases are so different in this case and need to be assigned to 2 different developers. My opinion...
@svoinea My opinion is that the right way to do this is to define the annotation that you think can address this need. Review it with @karlcz  and @robes. Then implement a reusable function. Then fix it in the search app and let @shinyichen reuse the function to fix recordset.

**Comment by karlcz** [comment]
OK, I drafted an annotation (linked above) and also created #381 for the recordset app version of this task.

**Comment by svoinea** [comment]
Fixed in the commit 0efddae728cc942208bcee41848b78944d9dc255.

The 'recordResource' parameter from chaiseConfig was removed.

The 'tag:isrd.isi.edu,2016:recordlink' annotation is used now at the schema or table level.

The default is "record/". The schema annotation overwrites the default, while the table annotation overwrites the default and/or the schema one.

Available for review on rbk-dev.

**Comment by hongsudt** [comment]
@chiragsanghvi please review this fix. THanks.
