### ISSUE TITLE
Multi-row data entry

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#386]
Extend our data entry form with multi-row entry. The basic functionality should include:
- a `+` or `add another` button
- on clicking that, the display should add a column, and all data entry columns should be of the same width,
- it should also copy over all of the non-auto generate columns

**Comment by robes** [comment]
@karlcz anything else?

**Comment by robes** [comment]
Make sure to work on this one in a development branch.

**Comment by howdyjessie** [comment]
@robes @karlcz How about a `-` or `Delete record` button? Is that necessary for this milestone?

**Comment by robes** [comment]
Yes, I think it would be good if the user could delete one of the rows while editing in multi-row mode. That’s what you meant right?

**Comment by howdyjessie** [comment]
@robes Yep!

**Comment by howdyjessie** [comment]
Please see PR #415 for review.

**Comment by carlkesselman** [comment]
The remove column button doesn’t seem to work for me.

Is the behavior we have on column width what we want?  Might it be better if there was an initial max width that wasn’t the full width of the browser?

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Jun 1, 2016, at 5:44 PM, Jessie Wong <notifications@github.com<mailto:notifications@github.com>> wrote:


Please see PR #415<https://github.com/informatics-isi-edu/chaise/pull/415> for review.

**Comment by howdyjessie** [comment]
@carlkesselman I'm not sure why it wasn't working but I just re-uploaded my code to my user dir and it works now. Try again? 

I also changed the logic a little so that the Remove button only appears if there are at least 2 columns currently being edited because I want to avoid users deleting the only column they have and then submitting 0 records.

**Comment by carlkesselman** [comment]
Yep.  Works now.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Jun 1, 2016, at 10:22 PM, Jessie Wong <notifications@github.com<mailto:notifications@github.com>> wrote:


@carlkesselman<https://github.com/carlkesselman> I'm not sure why it wasn't working but I just re-uploaded my code to my user dir and it works now. Try again?

I also changed the logic a little so that the Remove button only appears if there are at least 2 columns currently being edited because I want to avoid users deleting the only column they have and then submitting 0 records.

**Comment by robes** [comment]
On 6/1/16, 7:03 PM, "Carl Kesselman" <notifications@github.com<mailto:notifications@github.com>> wrote:

Is the behavior we have on column width what we want? Might it be better if there was an initial max width that wasn’t the full width of the browser?

Personally, I’m fine with full width of the form as it is.

**Comment by robes** [comment]
We should think if there is a better label for the button `+ Add Record`. To me that seems confusing with the idea of submitting data. I'm open to other ideas. `+ Copy` ?

And/or can we add a tool tip to the buttons, so if they hover over the Add Record button it says something like "Add another record to this form to enter multiple records. It will copy over the values from the last record in the form." That's quite verbose but I think we could use some explanation.
