### ISSUE TITLE
Support displayname 

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#392]
Support displayname where we display schemas, tables, and columns.

See https://github.com/informatics-isi-edu/ermrestjs/issues/36

**Comment by howdyjessie** [comment]
@robes The data entry app now uses `displayname` when showing schema, table, or column names to the user. For non-presentation purposes, however, we keep using the `name` property. 

Since this was a relatively small update, I pushed directly to `master`. You can see the fix now in [my user dir](https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#1/legacy:dataset) or you'll see it [on dev.isrd](https://dev.isrd.isi.edu/chaise/data-entry/#1/legacy:dataset) in ~15 min when dev.isrd does its next hourly update.
