### ISSUE TITLE
Ignore annotation not working in data-entry

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#449]
1. Go to https://synapse-dev.isrd.isi.edu/chaise/data-entry/#2/Zebrafish:Subject
   - Notice that it is prompting for the `ID` column as a required field
2. Go to https://synapse-dev.isrd.isi.edu/ermrest/catalog/2/schema/Zebrafish/table/Subject/column/ID
  - Notice that it has the ignore on data-entry annotation

If I'm not confused, we already confirmed this to work previously and merged a PR for it, so this is a regression.  This dev VM is running the latest master for chaise.

**Comment by jrchudy** [comment]
This issue is addressed in the latest [commit](https://github.com/informatics-isi-edu/chaise/commit/7f95ca0dc7e1e10ef535ab3850c1b528dc0a66e3). I wrote a `.includes()` function for the annotations object in ermrestJS. When using it in chaise, I used `.includes()` (plural) in `dataEntry.app.js` and `.include()` (singular) in `form.controller.js`. 

Very simple syntax error that I and my reviewer didn't catch.

**Comment by jrchudy** [comment]
Assigning to @karlcz so that you can test it and verify that it's working properly again. This can be tested from my folder on the synapse sever [here]9https://synapse-dev.isrd.isi.edu/~jchudy/chaise/data-entry/#2/Zebrafish:Subject) or wait until the hourly update.

**Comment by karlcz** [comment]
Thanks it worked for me.
