### ISSUE TITLE
viewer: use different glyphs for the arrow annotation

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#457]
When an image is zoomed all the way out, Jill complains that the current arrow icons obscure part of the image.. She asks whether we can use a different glyph or make this smaller or transparent.   

If this is difficult to achieve, maybe the best way to deal with this is to have an on/off switch to control what get displayed on demand?

**Comment by meihuisu** [comment]
The thing to do is to enable visiblility control on annotation instead of changing glyph at this point.
then get the user feedback before deciding which to do next. 

the visibility feature is there in viewer already. I have shown it to Jessie and Joshua before the break. They just
have to add the control logic on Chaise side.

mei

----- Original Message -----

**Comment by hongsudt** [comment]
is there a way for you to control the icon transparency?

**Comment by meihuisu** [comment]
It can be controlled  in CSS

----- Original Message -----

**Comment by hongsudt** [comment]
Mark this as won't fix for now.. Repoen if Jill insists on changing the glyphs.
