### ISSUE TITLE
create a navbar.html prototype that override default navbar for facebase

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#493]
@RFSH please describe your plan here to make it customizable for different projects.

**Comment by RFSH** [comment]
Fixing #492 would give us the ability to customize the branding of navbar. However in some cases (Facebase in this case) we need to be able to customize the whole template of navbar.

One simple solution would be overriding [navbar.html](https://github.com/informatics-isi-edu/chaise/blob/master/common/templates/navbar.html) instead of overriding the whole index.html.in in each app. Following is the navbar.html that can be used in Facebase.

```html
---
layout: null
permalink: /data/common/templates/navbar.html
---

<link href="/css/custom.css" type="text/css" rel="stylesheet">
<script src="/data/chaise-config.js"></script>
<script src="/js/facebase-userlinks.js"></script>

<!-- Google Tag Manager -->
<noscript>
    <iframe src="//www.googletagmanager.com/ns.html?id=GTM-MQXHZN"
            height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
<script>(function (w, d, s, l, i) {
    w[l] = w[l] || [];
    w[l].push({
        'gtm.start': new Date().getTime(), event: 'gtm.js'
    });
    var f = d.getElementsByTagName(s)[0],
            j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
    j.async = true;
    j.src =
            '//www.googletagmanager.com/gtm.js?id=' + i + dl;
    f.parentNode.insertBefore(j, f);
})(window, document, 'script', 'dataLayer', 'GTM-MQXHZN');</script>
<!-- End Google Tag Manager -->

<header class="row" style="z-index: -1; margin-bottom: 70px;">
    <nav id="mainnav" class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#fb-navbar-main-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="md-chevron-down"></span>
                    MENU
                </button>
                <a class="navbar-brand" href="/">
                    <img id="navbarBrandImage"><span id="navbarBrandText">{{ site.name }}</span></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-inverse" id="fb-navbar-main-collapse">

                {% include navigation.html %}

                <p class="navbar-text pull-right">
                    <a ng-show="user === null" ng-click="login()">Log In</a>
                    <span ng-show="user !== null">
                        <a id="login_user" href="https://www.globus.org/app/account" ng-bind="user"></a>
                        <a ng-click="logout()" id="logout_link">Log Out</a>
                    </span>
                </p>

            </div><!-- /.navbar-collapse -->
        </div>
    </nav>
</header>
```

However this just solves the navbar issue. Still we need to be able to customize other parts of the page (This includes title, footer, and any other extra header or elements). We also should be able to include any other project-specific static files(e.g. custom.css). The better solution would be resolving #266.

**Comment by robes** [comment]
We do need to resolve #266, but I don't think it changes this issue of branding, it just eliminates the redundancy of multiple index.html.in... which if you are up for it might be a good thing to take on as well.

Side note: Can you clarify what you mean by 'override' the navbar. Does that entail 'overwriting' the navbar? I think we currently have to overwrite the index.html.

At any rate, yes overriding or overwriting just the navbar seems like an improvement over the whole index.html. It would ideal to have a solution that doesn't require overwriting though.

**Comment by RFSH** [comment]
@robes 
Yes, I meant overwriting or having a more specific navbar (or any other template) for each projects that will be used instead of the common template.

Having one common index.html.in for different applications can ease the process of customizing or overwriting.

Since in Facebase we are adding several html elements to the navbar, I can not think of a better solution other than overwriting for it.

**Comment by hongsudt** [comment]
Regarding #266, we were going to wait until Alejandro and cris fix the
deployment path in the db to be consistent with the other deployments first
before working on it..

**Comment by crisaless** [comment]
I'm working this out now in facebase-www - I think the only other common template we would need would be the footer - not only for branding but also to include some javascript for the navigation dropdowns.

as for possibly making all of this work through configuration alone - the only things missing for FaceBase are the navigation, the "Sign Up" link, and the footer branding. The only tricky one of those is the navigation - but since chaise includes bootstrap, it's not impossible. the jekyll code uses a YAML file to build the navigation - I wonder if that's somehow compatible in angular?

**Comment by karlcz** [comment]
I would expect the modularity to be at the HTML/JS level, after the Jekyll build step consumes the YAML and generates the actual static content.  I think we'd just want that static content to be inserted into Chaise via a configured include statement, iframe, or similar...

**Comment by crisaless** [comment]
What needs to change in the facebase-userlinks.js to work with the current chaise auth? also do we even need this on the chaise side?

https://github.com/informatics-isi-edu/facebase-www/blob/master/www/js/facebase-userlinks.js

**Comment by RFSH** [comment]
I don't think we need [facebase-userlinks.js](https://github.com/informatics-isi-edu/facebase-www/blob/master/www/js/facebase-userlinks.js) and the whole authentication part is done by chaise.

**Comment by crisaless** [comment]
easy to generate static content for navigation - jekyll would pull in the include to an html file at /data/common/templates/navigation.html and then use a config parameter for the path

Footer would be a little more complicated for FaceBase. It could use the same branding color. It uses three columns with logo and extra Contact, Privacy links. 

Would be simpler to just pull it in as a template to override or just downgrade the design so it's just the branding color and then a new copyright text parameter. It's not even seen that often so that might not be a big issue.

**Comment by crisaless** [comment]
@RFSH - cool - but on the static side of the website, we still need to support login/logout - in that case, what files do we need to pull in from chaise to enable authentication? that's what facebase-userlinks.js was for, but using a separate file got out of sync quickly.

**Comment by RFSH** [comment]
@crisaless oh, you're right. I completely forgot the static side. Authentication functions are defined in [here](https://github.com/informatics-isi-edu/chaise/blob/master/common/authen.js) but these are in angularjs scope. Should we make some equivalent version of them outside angular to be used by Facebase?

**Comment by crisaless** [comment]
if we made equivalent version for static side it would be great if it could be done in a way that reuses authn.js so that we don't have to constantly keep the static version sync'd manually.

Is it possible to use some agnostic url to redirect the user to chaise login?

**Comment by crisaless** [comment]
i've re-written and re-orged some of the jekyll code. now there's a navbar.html template in /data/common/templates/

i still have the custom index.html.in files under /data/  (for login/, record/ and search) - but if chaise is set up now to use the navbar template, I should just take all of those out, right? the footer will still be default but that's fine for now.

**Comment by RFSH** [comment]
The current search and record apps are not using navbar template. So I think we should keep the index.html.in until we change those apps to use the navbar template. The new developed applications (recordset, recordedit, etc.) are using this template.

**Comment by crisaless** [comment]
the login/logout code is now in there (on dev) but it doesn't look like it's being processed by angular.

**Comment by crisaless** [comment]
I've got login working on dev.facebase.org/data/search/

log out works, except when you click the second option to log out (Continue to data/logout) it throws a 404.
https://auth.globus.org/data/logout

**Comment by svoinea** [comment]
I have just created an issue (#41) on webauthn for it.

**Comment by robes** [comment]
@crisaless This issue is really old. Have we worked around this or resolved it?

**Comment by crisaless** [comment]
this issue was made obsolete when we made the navbar menu and decoupled dependence on the static site.
