### ISSUE TITLE
Minor visual enhancements for the search/filter experience

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#50]
Based on conversations with @carlkesselman @crisaless @howdyjessie we want to make a few mostly cosmetic changes to the search/filter experience to address some of the feedback we have received.

- [x] make the facet slide out ‘pin-able’
- [x] by default display the facet slide out (by default make it ‘pinned’)
- [x] make the facet slide out search box more obvious (too subtle right now)
- [x] drop the 'filter' button since the slide out will be pinned by default
- [x] hide the facets chiclet box when it is empty before the user has made any facet selections
- [x] don't outline the chiclet box, which confused people by making it look like you can enter search strings in it
- [x] don’t gray out the search results listing when you are faceting, just reflow them on the page
- [x] reposition the “enable more filters” to the bottom of the facet slide out
- [x] instead of "enabled X of Y filters" just say how many filters are available 
- [x] change the text from "Search data" to something else (maybe "Type here to filter" or "Type here to search for filters" something)

Additional functionality that we should document in other issues:
- ability to specify the exact order of filters in the facet control (addressed by #51)
- facet control should show the keyword hits when the user types something like "'msx' in mouse genotype" (addressed by #43)

**Comment by carlkesselman** [comment]
Minor issue.  Are the filters, facets. Keywords?

Carl

Sent from my iPhone

Dr. Carl Kesselman
Dean's Professor, Epstein Dept. Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Phone: +1 (310) 448-9338
Email: carl@isi.edu<mailto:carl@isi.edu>

On Sep 4, 2015, at 4:22 PM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:


Based on conversations with @carlkesselman<https://github.com/carlkesselman> @crisaless<https://github.com/crisaless> @howdyjessie<https://github.com/howdyjessie> we want to make a few mostly cosmetic changes to the search/filter experience to address some of the feedback we have received.

  *    make the facet slide out 'pin-able'
  *    by default display the facet slide out (by default make it 'pinned')
  *    make the facet slide out search box more obvious (too subtle right now)
  *    drop the 'filter' button since the slide out will be pinned by default
  *    hide the facets chiclet box when it is empty before the user has made any facet selections
  *    don't outline the chiclet box, which confused people by making it look like you can enter search strings in it
  *    don't gray out the search results listing when you are faceting, just reflow them on the page
  *    reposition the "enable more filters" to the bottom of the facet slide out
  *    instead of "enabled X of Y filters" just say how many filters are available
  *    change the text from "Search data" to something else (maybe "Type here to filter" or "Type here to search for filters" something)

Additional functionality that we should document in other issues:

  *   ability to specify the exact order of filters in the facet control
  *   facet control should show the keyword hits when the user types something like "'msx' in mouse genotype"

-

**Comment by crisaless** [comment]
Can this be closed?
