### ISSUE TITLE
Page is not scrollable once you press delete button to render Bootstrap modal

### ISSUE THREAD

**Issue by chiragsanghvi** [informatics-isi-edu/chaise#504]
@howdyjessie @jrchudy @robes 

**Scenario**:
1. Open  this [RecordAdd](https://dev.isrd.isi.edu/chaise/recordedit/#1337/product:accommodation) page.
2. Open browser console and run following script to enable edit

``` javascript
$('.modal').remove(), $('.modal-backdrop').remove(), $('body').removeClass('modal-open');
```
1. Click on _add (+)_ button.
2. Now click on _delete_ button. This will show you a confirmation modal.
3. Click on either _cancel_ or _delete_ button.
4. Now try scrolling down.

The reason for this behaviour is due to the `modal-open` class which is left on body even after the confirmation modal is closed.

**Comment by howdyjessie** [comment]
@chiragsanghvi I'm not sure I'm reproducing the bug correctly. Is using the script necessary to reproducing this bug?

When following your instructions, I get stuck at step 3 (clicking the + button) because the form isn't rendered if the app encounters a non-existent catalog id.

If I visit a page for an existing catalog (i.e. 1), then I can reproduce the behavior, but only if I entered your jQuery script. Then I can see that the `modal-open` class remains on the `body`. But if I just press a trash can icon to render the modal, and then click Delete or Cancel on the modal, then the modal disappears and I can still scroll down the page like normal.

**Comment by jrchudy** [comment]
@howdyjessie, remember that this issue was initially filed back in July. So the case to reproduce it may be different now.

**Comment by chiragsanghvi** [comment]
@howdyjessie I think the issue is no more relevant. We have changed a lot since July. Closing the issue.
