### ISSUE TITLE
Inconsistent navbar style record app

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#516]
The record app shows blue anchor text for the "navbarBrand" in top-left while the recordset and recordedit show white anchor text.

The record app also shows blue user identity while the other two show yellow user identity.

They all show blue "Log Out".

I see all this on multiple dev systems using Firefox.

**Comment by hongsudt** [comment]
@crisaless Should this task be assigned to you or @shinyichen ?

**Comment by crisaless** [comment]
i'll assign it to myself - let me know if you need this quickly though

**Comment by howdyjessie** [comment]
So with the new navbar recently rolled out, the navbar's styles should look the same across all apps now. Any discrepancies going forward would be usually due to a later stylesheet overriding the navbar's styles (e.g. since the `customCSS` file is loaded after the navbar's styles, any conflicting classes will follow the custom CSS.)

**Comment by howdyjessie** [comment]
This depends on #584, which is blocked by PR #599. :(

**Comment by howdyjessie** [comment]
Closing because #599 has been merged.
