### ISSUE TITLE
refactor login/logut/get_session to be non-angulra 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#529]
So that the same code can be used for angular and non-angular app.

**Comment by hongsudt** [comment]
@chiragsanghvi if you are blocked, you can work on this issue. @RFSH can you tell you more info. 
If I am not mistaken, the static site (e.g. facebase.org) login is pointing to a different login/logout code from what's in the chaise navbar. The goal is for them to use the same code.

**Comment by RFSH** [comment]
The new apps, are using this [navbar](https://github.com/informatics-isi-edu/chaise/blob/master/common/templates/navbar.html), which uses [navbar directive](https://github.com/informatics-isi-edu/chaise/blob/64abd525764ee52dc42b35a2102fe01bf075accc/common/navbar.js). The goal is extracting the functions that are used in the template; so the login/logout would work in the static pages that are outside angular scope. So the customization of navbar for each project would just require changing the template and not the logic.

Take a look at facebase as an example, our main goal is that the navbar in [record-two](https://dev.facebase.org/data/record-two/#1/legacy:dataset/id=1595), and [main page](https://dev.facebase.org/) use the same template and logic.

Currently [we are overriding the navbar.html template](https://github.com/informatics-isi-edu/facebase-www/blob/master/www/data/common/templates/navbar.html). So both of them are using the same html (they look different because record-two doesn't have access to [custom.css](https://github.com/informatics-isi-edu/facebase-www/blob/master/www/css/custom.css)). However, the functions that are used for the login/logout come from [old ermrest.js](https://github.com/informatics-isi-edu/chaise/blob/master/scripts/ermrest.js), and since record-two doesn't have access to this file, you cannot see the login/logout link in record-two.

**Comment by hongsudt** [comment]
I am tagging this as a wishlist and close the issue.. We can go over wishlist later.
