### ISSUE TITLE
Blank recordedit app when client is forbidden to access ermrest

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#530]
A user who wasn't enrolled in the required group went to a recordedit URL and says the app is just stuck showing the blank record entry page with no model-driven form content and no error message that access is forbidden.

It is the initial fetch of the catalog/1/schema resource that returns 403 forbidden.

This is on a staging system running master commit 4f120d267e71b91b1826c93d4a736da913af4ac6 so I am not sure if this is something already fixed in later revisions...

**Comment by hongsudt** [comment]
can you try to replicate it on dev?

**Comment by jrchudy** [comment]
It looks like this issue was opened for the old recordedit app. This issue is addressed in the refactored app on `recordedit2-master` branch.

When a user navigates to the recordedit page with improper permissions, they are presented with a modal dialog window that notifies them that there was an error and a button to navigate to `chaiseConfig.dataBrowser` (if it is set) or the landing page.
