### ISSUE TITLE
Add "Select All/Deselect All" checkbox to sidebar

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#54]
A checkbox to toggle facet selections

We're not sure if this is doable. As @robes mentioned: "... we might need to discuss this with @svoinea because we can’t have these lists blowing up (a) the Chaise URL now that we put all this in there, and (b) the underlying ERMrest URL. A lot of middleware (browsers, web servers, URL parsers) have limits to how long of an URL they allow."

**Comment by howdyjessie** [comment]
A preliminary Google says it's the URL limit is basically at 2000 characters. http://stackoverflow.com/a/417184/3581097

**Comment by robes** [comment]
It’s really just implementation dependent. Notice the comment that says Chrome handles 20,000+ character URLs. And that’s just the browser side of the equation.

**Comment by howdyjessie** [comment]
Aside from the question of technical feasibility, there's also a question of utility. I don't recall that we have user test data to support a "Select All/Deselect All" checkbox, but I defer to @crisaless to affirm/negate that.

What exactly should a Select All and Deselect All do?

**Comment by karlcz** [comment]
The select-all/deselect-all is a crutch to deal with overly large checkbox lists or to express other constraint concepts. Consider the cases approaching the limits:

1. Select all: every possible value matches the facet, which makes it equivalent to a column-is-not-null constraint.
2. Select all then deselect a few: equivalent to not-null AND not-equal one of those few deselected values.
3. Deselect all then select a few: matches a few (our normal use case), adding a short-cut for delete chicklet, edit facet over again
4. Deselect all is a weird UX corner case which could mean either of:
  - Column-is-null constraint?
  - Facet deactivated, no constraint at all?

I wonder whether the UX should address different scenarios with different constraint forms rather than trying to cram such pathological cases into a checkbox list.

**Comment by robes** [comment]
@howdyjessie I think this is still a good task to keep around and decide on how we want to solve it. But maybe we should un-schedule it from the Sept Sprint.

**Comment by howdyjessie** [comment]
@robes I put it under the nebulous Oct Sprint milestone for now :+1:

**Comment by robes** [comment]
We need to revisit this later. There may be a different approach.
