### ISSUE TITLE
Move "enabled X of Y filters" to the bottom of the sidebar & modify search bar shape

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#57]
The "Enabled X of Y filters" label should read "See all Y filters"

Search bar in the sidebar is a pill shape to make it look more like a search bar. The default text in it should read "Search filters by keyword"

I know I removed the magnifying glass in my prototypes but now that we're moving the "Enabled X of Y filters" link to the bottom, I actually think it's better if we keep the magnifying glass.

**Comment by crisaless** [comment]
Due to the fixed sidebar - I'm still having a problem getting the 'View all filters' bar to stick to the bottom of the column (CSS problems with positioning within a fixed div). I've changed the design somewhat to incorporate it into the 'Selected Attributes' header row as shown in the attached screenshot.
<img width="1280" alt="new-viewallfilters" src="https://cloud.githubusercontent.com/assets/8965132/10032577/b72f2280-6138-11e5-9853-1f33d723a982.png">
.

**Comment by crisaless** [comment]
note the screenshot is the result when my cursor hovers over that header - but the screenshot didn't capture my cursor.

**Comment by robes** [comment]
I'm guessing this gets fixed with the UI enhancements you are making?

**Comment by howdyjessie** [comment]
Affirmative
