### ISSUE TITLE
Recordedit Error: ignoreCol.content.indexOf is not a function

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#620]
recordedit keeps spamming these errors into the web console on firefox:

```
Error: ignoreCol.content.indexOf is not a function
isHiddenColumn@https://synapse-dev.isrd.isi.edu/chaise/recordedit/form.controller.js?v=e53e4dfbce7bac15e5169d44c2c96f5c:311:96
anonymous/fn@https://synapse-dev.isrd.isi.edu/chaise/scripts/vendor/angular.js line 14432 > Function:2:337
oneTimeWatch@https://synapse-dev.isrd.isi.edu/chaise/scripts/vendor/angular.js:15563:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://synapse-dev.isrd.isi.edu/chaise/scripts/vendor/angular.js:17064:34
...
```

**Comment by hongsudt** [comment]
@karlcz this issue can be addressed after refactoring. Can you wait a bit longer for the fix?

**Comment by karlcz** [comment]
It's not urgent for me right now. I don't even know what it breaks, if anything... just reporting the error message I saw while doing some other basic testing.

**Comment by howdyjessie** [comment]
@karlcz This bug should've been addressed when recordedit was refactored. (The code that produces this error no longer exists.) Do you still see this error in your console on synapse-dev?

I remember seeing this error because this line was part of a function that checked whether a column that has a 2016:ignore annotation, and, if it did, then look for whether the annotation's content had any applicable contexts for this app. However, Recordedit app now no longer directly checks for this ignore annotation, so this bug should no longer exist.

**Comment by hongsudt** [comment]
Let's close this issue then.
