### ISSUE TITLE
Chaise config copy for tests

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#622]
The function that copies the chaise config from a specified directory for a set of tests, overwrites `chaise-config.js` in the root directory on my local machine before it is copied to the dev server.

**Comment by chiragsanghvi** [comment]
@jrchudy As mentioned in the [documentation](https://github.com/informatics-isi-edu/chaise/wiki/E2E-tests-guide#chaiseconfigfilepath), it is mandatory to provide a remote_chaise_dir whenever you execute the test-cases. If you don't provide one the local one gets overridden, because the suite has no knowledge of whether the existing chaise-config was the valid one or the copied one.
