### ISSUE TITLE
login not working from firefox

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#645]
This can be seen on dev.facebase.org.

If you click log in from a record page the link takes you to a username/password login page.

If you click log in from a search page the link takes you to the oauth login page.

Not sure exactly who should take this issue. Its a navbar issue showing up on the record page.

**Comment by robes** [comment]
Just to be clear, this bug is reproducible on dev.isrd.isi.edu. Seems to be a general issue.

**Comment by robes** [comment]
Also, it affects both _record_ and _recordset_ but not _search_.

**Comment by karlcz** [comment]
I see completely different (and buggy) behaviors on record and recordset on dev.isrd via firefox

- record errors out about not specifying a catalog since the "Log In" button seems to redirect to https://dev.isrd.isi.edu/chaise/record/#
- "Log In" via recordset just hangs with unrendered angular junk due to "ReferenceError: error is not defined"

**Comment by robes** [comment]
This is absolutely critical -- **show stopper** for the facebase release -- and we need a facebase release on oct 17.

**Comment by robes** [comment]
seems to be fixed
