### ISSUE TITLE
Recordedit needs a 'Cancel' button

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#670]
All I see is 'Submit Data' and no cancel button. I suppose the browser's back button is effectively the same as cancel and go back but I think a cancel button would make it more explicit. As we've learned a lot of users have been 'trained' by other web sites that the browser back button is not to be trusted.

**Comment by hongsudt** [comment]
Upon clicking the cancel button, the app should lead the user back to the previous page.

@shinyichen can tell you how to refer to the page the lead to the recordedit.

**Comment by howdyjessie** [comment]
Still need to discuss with @hongsudt about how to implement this after she returns from the main campus today, so I'm putting this in Blocked for now.

**Comment by karlcz** [comment]
This should be more trivial now that login uses a pop-up and does not contaminate the window location history.  Should just be able to go back one hop...

btw, this issue needs to be reassigned... @hongsudt

**Comment by jrchudy** [comment]
Leaving this issue open but moving this to backlog as it's a feature that has been brought up off and on since this issue was created. I don't think it's "blocked" anymore, this requires discussion on the details and what "canceling" means since users can reach recordedit app from both record and recordset a variety of different ways.
