### ISSUE TITLE
recordedit: remove the x button on the search popup. 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#702]
This seems to be redundant with the cancel button at the bottom of the page which works. The x button doesn't work. We should move the cancel button to top right corner instead.

**Comment by jrchudy** [comment]
The X and cancel button are the same implementation and the same function. If one isn't working, it might be because the control has been fully loaded yet. The cancel button appears to work every time because you are forced to wait for the modal to finish loading so you can scroll to the bottom before you can click it.

**Comment by jrchudy** [comment]
This issue is fixed in the recent commit. The x button was missing some styling to make it appear and react more like a button. The cancel button has been removed.
