### ISSUE TITLE
Need better error message

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#716]
We need a better error messages to let the users know what's wrong and what's can be done. 

@karlcz does this require some modification from errmest?

**Comment by karlcz** [comment]
You need to provide a much more concrete set of goals.  Messages for what kind of errors?  What do you think the client would need to know?

There is an open issue in ermrest to provide more machine-readable error information.  This was mostly intended to expose sub-types of error that are currently all represented as 409 Conflict due to the way HTTP error codes work.  However, this was deprioritized as it wasn't clear which error sub-types would lead to meaningfully different response from our current clients like Chaise.

**Comment by hongsudt** [comment]
Start a list of specific use case: 
- duplicate keys

**Comment by robes** [comment]
FK specific use case:
* For example, let’s say you have a FK reference with a ‘ON DELETE RESTRICT’ rather than CASCADE and you try to delete the referred entity. We get a conflict error and the user gets punted to the home page of the project.

**Comment by hongsudt** [comment]
FK constraints use case:
> 409 Conflict
The request conflicts with the state of the server. update or delete on table "experiment_type" violates foreign key constraint "dataset_experiment_type_experiment_type_fkey" on table "dataset_experiment_type"
DETAIL:  Key (term)=(Confocal microscope images) is still referenced from table "dataset_experiment_type".

**Comment by karlcz** [comment]
I don't think we should try to handle that custom gpcr error in the front end.  If we want, we can try to recognize the general postgres error message pattern and strip some of the uglier parts.
E.g.

    Error 409 Conflict The request conflicts with the state of the server. ERROR: the provided site_name is not consistent with your login profile. Please enter an appropriate site CONTEXT: PL/pgSQL function experiments.userid_update() line 25 at RAISE
    
could be shortened to:

    Error 409 Conflict The request conflicts with the state of the server. the provided site_name is not consistent with your login profile. Please enter an appropriate site 

and I think the SQL procedure should be modified to capitalize the `T` in `The` and to terminate the second sentence with a `.`

Also, this really seems like a permission error so we should try to find a way for the SQL procedure to raise an exception that ermrest understands as `403 Forbidden` rather than `409 Conflict`.

**Comment by RFSH** [comment]
To summarize what is needed,

1. A better and more informative error messages for 
  - Duplicate key violation: When you update/create a record with the same key value.
  - Foreign Key violation: When you delete a record and it has foreign key dependencies.
2. For other 409 error messages, just remove the "Error 409 Conflict The request conflicts with the state of the server." if exists. And only show the provided message (as Karl pointed out in the previous comment).

**Comment by amitjha21** [comment]
It's been merged. Assigning o @hongsudt to verify and close it.
