### ISSUE TITLE
Search modal has area that is not clickable

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#729]
Choose one of the sop drop-down. When a search is poped up, I can click any column to choose the row except the procedure column (which is a markdown).  We should be able to click anywhere to choose, correct? 

https://dev.gpcrconsortium.org/~chirag/chaise/recordedit/#1/experiments:sample

**Comment by jrchudy** [comment]
This is caused by a div that is rendered as markdown. When that div is markdown, it has the event propagation applied to that div whether it has a link or not. We should move the `$event.stopPropagation()` click event to the <a> tag that is rendered in the markdown. This way it only stops propagation on <a> tags instead of all markdown tags.

We need to open an issue in ermrestJS for this.

**Comment by hongsudt** [comment]
Issue moved to [informatics-isi-edu/ermrestjs #271](https://github.com/informatics-isi-edu/ermrestjs/issues/271) via [**ZenHub**](https://www.zenhub.com/)
