### ISSUE TITLE
style long column value to only show a portion of text 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#745]
With the `more` link/button to expand the rest of the next and `less` to contract the text. 

I saw this implemented in amazon comments and we might be able to borrow the concept here. 

@chiragsanghvi please suggestions of existing material that we might be able to use.

**Comment by shinyichen** [comment]
I have played with this yesterday and today. I tried a combination of different things and came up with two ways of doing it, neither can accomplish exactly what we want. (Note: `text-overflow: ellipses` only works for single line.)

First is applying CSS `max-height` on the content and hide the `overflow`. The hard part is figuring out whether this cell's content has overflow in order to display the `... more` link, because I need to do it before rendering. 

The other way I tried was using word count, and truncate if text exceeds max word count. Then I can determine if `... more` is required before rendering. This can accomplish what Hongsuda described, but only if content is text. If content is HTML, I would be cutting off HTML tags. 

I don't have a solution yet. Any suggestions? @chiragsanghvi @howdyjessie @jrchudy

**Comment by shinyichen** [comment]
I just remember that I am out of town next week (11/7-11/11). I push the changes I have, using the second method described, to re2-readmore branch. 
https://github.com/informatics-isi-edu/chaise/tree/re2-readmore
In case someone needs to pick it up where I left off.

**Comment by hongsudt** [comment]
@chiragsanghvi Do you think you can take over this issue?

**Comment by chiragsanghvi** [comment]
This is how it looks [before wrapping](https://dev.isrd.isi.edu/chaise/recordset/#9862/product-record:accommodation/id=2002) and [after wrapping](https://dev.isrd.isi.edu/~chirag/chaise/recordset/#9862/product-record:accommodation/id=2002)
