### ISSUE TITLE
Generic "Record" text in labels

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#782]
I think that having the generic text "Record" in labels does not add much to the interface. It shows up in places like "Create Record", "Edit Record", "Add Record", "View All Records".

I would propose one of two options here:
- either simply drop "Record" from each label because the rest of the text is meaningful on its own.
- or replace "Record" with the `reference.displayName` so those labels would instead read something like "Create Specimen", "Edit Specimen", "Add Slide", "View All Slides" (not sure how the plural form is achieved but in that case "View All" is really all you need to have).

Also, "{Show | Hide} Related "Entities" is inconsistent and should at least be consistent by using "Records" in place of "Entities".

**Comment by hongsudt** [comment]
I would prefer the first option e.g. drop the word record. 

For the toggle, maybe "Show|Hide empty related records"? I think the word `empty` needs to be there for it to be clear.

**Comment by howdyjessie** [comment]
I've dropped "record" from the labels where appropriate and pushed to master. Here's how it looks on the Record app:
<img width="592" alt="screen shot 2016-11-22 at 11 29 07 am" src="https://cloud.githubusercontent.com/assets/4585431/20538696/228c70a0-b0a7-11e6-9cab-a46da08548cf.png">
<img width="1344" alt="screen shot 2016-11-22 at 11 29 30 am" src="https://cloud.githubusercontent.com/assets/4585431/20538703/27739760-b0a7-11e6-92ff-470bc0c7c33d.png">

How about the "Delete Record" button in RecordEdit? I think "record" is helpful here since just "Delete" might be confusing, but I want to bring it up anyway in case others feel differently.

**Comment by robes** [comment]
I would keep the labels uniform. So if its simply "Delete" on the record app, I would be of the opinion that it should be "Delete" on recordedit app too.

One other thing. I believe that karl and hongsuda felt that everything except "Permalink" should use a style that looks more like a button than simply a link. They felt that simply looking like a link didn't give the user the right indication of its affordances.

**Comment by howdyjessie** [comment]
I created a separate issue (#798) to track the buttons vs links discussion. Giving it back to @robes for review.

**Comment by jrchudy** [comment]
@howdyjessie, @robes: Is this issue completed? It has been in review for ~3 weeks.
