### ISSUE TITLE
Revisit Selection Badges

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#79]
The general feedback we are getting is that the numbers in the badges are confusing.  We should revisit these and figure out if they make sense, if they need better explanation, or perhaps should be removed or replaced with something else.

**Comment by howdyjessie** [comment]
I think they should be removed because the numbers make users think the sidebar is a hierarchical ontology tree when it isn't.

Or the numbers could be rejiggered to align with this hierarchical ontology tree mindset.

If/when we implement #43, then we should keep the numbers because then there's no more "drilling down" to facilitate the perception that the sidebar is a hierarchical tree.

Uh, if anyone absolutely don't have anything better to do for 5 minutes, I get on a soap box [here](https://gist.github.com/howdyjessie/ebbd15131c9e3ffad1e9) and talk about how I feel this issue is part of the broader Google vs faceted searching paradigms.

**Comment by carlkesselman** [comment]
We need to make sure we remove calculation code for this.

**Comment by robes** [comment]
probably better for serban to take a look at this?

**Comment by robes** [comment]
#182 to address the removal of the calculation code
