### ISSUE TITLE
Automatically update the search directive if the typing in the search box is paused by 2 s.

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#791]
The app should make sure that it won't keep submitting the same request. As the user continue to type, new requests should be submitted and old results should be ignored.

**Comment by karlcz** [comment]
It's not a really big deal to repeat an identical query, since our
cache management should detect that as a repeat and quickly let the
browser reuse its cached result, as long as we don't repeat until the
previous response has been received.

I would suggest logic like the following, distinguishing a
"background" search we perform based on idle time and a "foreground"
search we perform due to user hitting enter or a search button:

1. Keep flags for whether background or foreground searches are in
   progress.

2. Only start a background search if we have no outstanding searches.

3. Only start a foreground search if we have no outstanding foreground
   searches.

4. If we have already started a foreground search, discard any
   background search result that arrives.

5. Ideally, lock the search input as busy while a foreground search is
   pending.

Since we cannot cancel a slow search, we shouldn't make the user think
they are still able to initiate an action. Nor should we actually
submit concurrent foreground searches since this abuses the server.


karl
