### ISSUE TITLE
faceting skeleton

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#792]
- Create a UI element for faceting operation. This pane should be on the left hand-side. It should allow the user to adjust the pane width. The pane should allow scrolling horizontally and vertically. The result set should be on the right hand 
- The faceting pane should list the main entity column names with the down arrow indicating an expanded area of operation. 
- This faceting pane should be configurable to be displayed on hidden based on a chaise config parameter. 

Note: this skeleton should incorporate all the flow mentioned in https://github.com/informatics-isi-edu/chaise/wiki/Faceting for one column.

**Comment by hongsudt** [comment]
@RFSH  should you merge the UX code that you have to chaise?

**Comment by RFSH** [comment]
@hongsudt It is just a mock-up. I cannot see the value of merging it now. It is not functional and just shows how the UI works. It also needs improvement to its UI and UX. I will keep it in my own directory ([https://dev.isrd.isi.edu/~ashafaei/chaise2/recordset/#1/isa:dataset](https://dev.isrd.isi.edu/~ashafaei/chaise2/recordset/#1/isa:dataset)).

**Comment by hongsudt** [comment]
- integrate the row count, column min/max into the flow.. 
  - min/max will be used for default facet values
  - row count is used to display # of matches

**Comment by hongsudt** [comment]
some more UX feedback: 
- we should have the black x to clear the existing entry box for all types
- for checkbox, every time I check a box it goes back to the first page. Can we remember the current search page, so it won't bounce back? 
- Can we make the area that summarizes existing filters sizable? 
- The max of the facet pane width should be half a page
- There is a bug listing the current text filter. If I start with a pattern, then add the checkboxes, the same text pattern was listed instead of the item that I just selected.

**Comment by jrchudy** [comment]
>  Can we remember the current search page
This won't be possible because selecting a new checkbox to facet on will produce a new set of data. That set of data may or may not include the data from the previous query that was being shown.

> Can we make the area that summarizes existing filters sizable
Do you mean on each facet or above the `recordset` table? Either way, this should be simple.

**Comment by hongsudt** [comment]
Based on the feedback today: 
- Put the page title in the sticky area
- Search result area:
  - consolidate all filters associated with a facet together. 
  - user should be able to click on the facet name to get to the facet list (auto-focus)
  - clear a facet, clear all filters associated with that facet? 
- for text column
  - Show the checklist without any search box in a list format
  - All filters that have been checked will always be visible
  - There should be a default page size say 10. Don't show no more than page size - number of existing filters.
  - Have a find more in the bottom of the list which upon clicking shows a modal of all available options
  - Ignore the pattern search for the moment.
- UX
  - The facet pane and the search result pane should be independent. Each has its own auto scroll
  - Upon issue a new search, the search result page can be refresh to the top of the page. (Note: some people might like the position of the page to be the same instead of having the page scrolled up)
  - have a visual indicator that the facet pane is resizable
  - have a clear feature on all entry boxes

**Comment by RFSH** [comment]
- [ ] Move create button to the top of the page. (It should be optional in the recordset directive since it should still be functional in the modal).
- [ ] Make sure that the title and subtitle of the page wrap (not truncate).
- [ ] Fix the scroll in the recordset app (Left and right pane must be scrollable, not just table).
- [ ] Make sure that table is overflow-x:auto (right now it's disabled).
- [ ] Reduce the space between facet title and the content.
- [ ] Fix the null/empty.
- [ ] Increase the modal width. It's more visible in the entity pickers.
- [ ] Modal scroll?!
- [ ] Reduce the jumping when the facet columns are updated (we can introduce extra white space, etc.).
- [ ] Tooltip is buggy (not taking care of html, and also sometimes it doesn't work).
- [ ] Limit width of filter pills by pixel (same size as search app).
- [ ] Pagination for attribute group is buggy.
- [ ] Calculate the size of url on each select and throw warning (?!).
- [ ] Change pills in the modal to be the same as the one in recordset app (truncate).
- [ ] Drop shadow is visible before page content has been loaded.
- [ ] Go to is:project, click on Abstract. It's throwing error. Investigate it.
- [ ] The select all is selecting duplicates in the modal (if it was selected before opening the modal).
- [ ] Fix default opening logic

**Comment by jrchudy** [comment]
@RFSH as I start working on a new task I will mark it in the above list. I am working from top to bottom.

**Comment by jrchudy** [comment]
Functional changes:
 [ ] Create button needs to use on focus and invalidate logic
 [ ] Edit button needs to use a url that doesn't include facets *OR* `recordedt` understands how to parse the faceting hash structure in the uri

**Comment by RFSH** [comment]
UX:
- [ ] The text in tooltip should be left justified
- [ ] For each chicklet, the x button tooltip should be "clear facet".
- [ ]  For the tooltip of all filters on top: instead of comma separated it should be bullet (requires change in ermrestjs)
- [ ]  Reduce the space between heading and content in range picker
- [ ]  Add animation for when you click on a facet
- [ ]  spinner is taking space. So page jumps a little
- [ ] opening a facet is happening in two steps.

Functionality:
- [ ]  Clear all is not unchecking the range
- [ ]  when you come back from find more,  it should update
- [ ]  Open the first facet always
- [ ]  add search filter to the list of facets. Clear all should clear everything
- [ ]  ermrestjs bug: cnt(*) of total should be can't(shortestkey)
- [ ]  Focus on most top opened
- [ ]  merge permalink with visible columns list
- [ ]  add chaise config to use recordset or recordset with facetting

**Comment by karlcz** [comment]
It occurred to me that we might want a small UX toggle to expand/hide the faceting sidebar and a query parameter in the fragment ID to expose the toggle state.  There might be scenarios where the DBA is constructing URLs from landing pages etc. and may want to make it open or closed depending on whether the page is intended to be more of a listing or more of a search interface.  But having a small GUI toggle would let the user override the DBA choice if they have a different goal in mind...

**Comment by jrchudy** [comment]
- [ ] Chaise config option should enable/disable faceting completely
- [ ] query param option to show/hide faceting panel in RS
- [ ] make more options bold
- [ ] (BUG) keys for own table should not be entity picker
- [ ] allow facets to be open based on annotation definition and being set in the faceting uri (save state of open facets for bookmarks)
- [ ] facet panel width facts
    - [ ] default width -> 20%
    - [ ] min width -> 150 px because of date and time inputs
- [ ] date/time inputs need a set width
- [ ] date/time inputs should remove the padding on left/right inside input box
- [ ] translate columns/foreign keys to proper facets (BUG that was showing "Publication (Dataset)" on dev.facebase)

**Comment by robes** [comment]
Bug: infinite spinner...

1. go to https://dev.facebase.org/~jchudy/chaise/recordset/#1/isa:dataset
2. expand Organism
3. select 'Mouse'
4. expand Mouse Gene
5. search on 'msx'
6. select 'MSX1'
7. expand Phenotype
8. spinning

**Comment by robes** [comment]
Bug: Accession should be scalar

As I mentioned in stand up, the Accession should be a set of scalar value 'FB00001232',... choices.

**Comment by robes** [comment]
Bug: factor in the 'view more' filters

As I mentioned in slack room. When you get to a recordset page from a record page's nested table's 'view more' link, the facets do not account for the join filters.

**Comment by robes** [comment]
Bug: "Error: TypeError"

I don't know if its just stale code but as I mentioned on slack, I always get the above terminal error just going to the test link.

https://dev.facebase.org/~jchudy/chaise/recordset/#1/isa:dataset@sort(release_date::desc::,id)

I can dismiss it, in order to use and evaluate the new feature.

**Comment by robes** [comment]
Bug: show some label like "No value" in place of _empty_ to represent the `NULL`s

I mentioned this in stand up too.

**Comment by robes** [comment]
Bug: use the display name for related references

I may be wrong... but I have a feeling you may not be using the display name of the related reference for the facets.

For example, 

https://dev.facebase.org/~jchudy/chaise/recordset/#1/isa:person

Notice that there are two "Project" facets, because there are two assocations in the data model between `person` and `project`.

If you drill down you will see the nested table is named differently.

https://dev.facebase.org/~jchudy/chaise/record/#1/isa:person/name=Annette%20M.%20Werner

Faceting should be using the same heuristic. If it is already, then this issue is invalid.

**Comment by robes** [comment]
Bug: some shading effect which seems like it might be caused by different height divs/panels

See, 
https://dev.facebase.org/~jchudy/chaise/recordset/#1/isa:enhancer

It looks this way in both FF and Chrome. If needed I can post a screen shot.

**Comment by robes** [comment]
Bug: overlapping facets

See
https://dev.facebase.org/~jchudy/chaise/recordset/#1/isa:enhancer/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM4gBsBLJAFwH0UAzcyMUlAWyKzAPLIzS1MxyRAAaEFgAWKFvziIQANzZo8sEACMMkMUTYACMNlGDtVMFi0FtjfjghiAnpaEgoJAA4Ewt+QUX41G0Wa6+obGpjqWSNZ2DsIkABIAKgCyADJwxgSRAL4AurlZQA@sort(id)

To recreate:
1. go to https://dev.facebase.org/~jchudy/chaise/recordset/#1/isa:enhancer
2. expand List of Anatomical Structure
3. select 'branchial arch, facial mesenchyme'
4. the Original Species Assembly facet is now overlapping the facet beneath it.

**Comment by robes** [comment]
Note: I cannot recreate but appears to be a bug lurking in there.

> After playing around with expanding/collapsing facets; selecting/unselecting from one facet to reduce the set of options in another facet; I can work my way into a state where the _other_ facets list will not get restored even though I’ve unselected all of the options in a different facet.

**Comment by jrchudy** [comment]
I have collected all of the bug reports and unfinished features that were discussed in this PR as well as in the slack channel, `isrd-chaise`, and created issues for them. Each of these issues were attached to either the round 1 epic (#678) or the round 2 epic (#1257).
