### ISSUE TITLE
Basic table presentation in details pages

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#8]
The UI needs to be able to present "nested entities" (i.e., entities that are related by a foreign key or an association table) in a compact table view rather than a repeating list. That is, right now we embed them as lists rather than tables. There should be one table per nested entity type. So for example is you are searching on a model that has Experiments, and it has Samples and Slides, the display page for Experiments could have 2 tables for the nested Samples and Slides data. This feature should be generalizable to handle any data model. It should use schema annotations to determine whether the nested entity should be displayed in table vs list. By default we might even want to do with tables and only use lists if the annotation says so.

**Comment by robes** [comment]
Earlier discussion (Rob):

For example, looking at the multicelldb server,

https://multicelldb.misd.isi.edu/chaise/app.html#/retrieve

If you click on the first result you see a bunch of associated/related tables displayed in a list (e.g., birthrate, duration, etc.).

When you look at www.facebase.org,

If you filter on a chromosome and look at a detail page for one item, the chromosome is displayed in a table.

Question:

1. is this a generalized feature that we can turn on/off by an annotation?
2. if so, what is that annotation (I assume its a table annotation).

**Comment by robes** [comment]
Earlier discussion (Mike):

> Question:
>
> 1. is this a generalized feature that we can turn on/off by an
annotation?
> 2. if so, what is that annotation (I assume its a table annotation).

*...snip...*

So I asked for pretty much the same exact thing: that for any given table I could put an annotation in that caused the data to be displayed in a tabular format that would support multiple rows per table (since my data contains quite a few "longitudinal" one-to-many relationships) and the current behavior of each row getting repeated as if it was just another table is a bit awkward looking, not to mention space consuming.

If you are curious to see what it looks like with my dataset go to https://misd-vm-12.isi.edu/ermrest-ui/app.html#/retrieve and click on any patient to get the full-blown detail view.  You can clearly see how numerous longitudinal tables in my data (e.g., adverse event logs, vitals, biospecimen inventory, blood chemistry) would benefit from a more compact tabular view.  

> ...snip...

I couldn’t agree more that this would be a great first task.  It will add significant value to the many projects that need this kind of display mode.  Ultimately, I would love to see a nice tabular view that had column sizing, reordering and hiding, along with being able to collapse/expand the entire table vertically to consolidate space while scrolling through the page.  Of course, I would be perfectly happy with a static table to start out with ;-)

**Comment by carlkesselman** [comment]
Piling on, we would like this table to be a bit interactive:

1) It should be possible to collapse the table.
2) It should be possible to sort on columns
3) It should be possible to reorder columns.
4) It should be possible to select subsets of columns.
5) If there are values that are foreign keys, we may want to link to them?
6) All of these settings should be savable in a user profile.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl







On Jul 6, 2015, at 10:35 AM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:


Earlier discussion (Mike):

Question:

  1.  is this a generalized feature that we can turn on/off by an annotation?
  2.  if so, what is that annotation (I assume its a table annotation).

...snip...

So I asked for pretty much the same exact thing: that for any given table I could put an annotation in that caused the data to be displayed in a tabular format that would support multiple rows per table (since my data contains quite a few "longitudinal" one-to-many relationships) and the current behavior of each row getting repeated as if it was just another table is a bit awkward looking, not to mention space consuming.

If you are curious to see what it looks like with my dataset go to https://misd-vm-12.isi.edu/ermrest-ui/app.html#/retrieve and click on any patient to get the full-blown detail view. You can clearly see how numerous longitudinal tables in my data (e.g., adverse event logs, vitals, biospecimen inventory, blood chemistry) would benefit from a more compact tabular view.

...snip...

I couldn’t agree more that this would be a great first task. It will add significant value to the many projects that need this kind of display mode. Ultimately, I would love to see a nice tabular view that had column sizing, reordering and hiding, along with being able to collapse/expand the entire table vertically to consolidate space while scrolling through the page. Of course, I would be perfectly happy with a static table to start out with ;-)

**Comment by carlkesselman** [comment]
Nuts, I should have read to the bottom of the email.  Mike hit all the issues I thought we should….

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl







On Jul 6, 2015, at 10:35 AM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:


Earlier discussion (Mike):

Question:

  1.  is this a generalized feature that we can turn on/off by an annotation?
  2.  if so, what is that annotation (I assume its a table annotation).

...snip...

So I asked for pretty much the same exact thing: that for any given table I could put an annotation in that caused the data to be displayed in a tabular format that would support multiple rows per table (since my data contains quite a few "longitudinal" one-to-many relationships) and the current behavior of each row getting repeated as if it was just another table is a bit awkward looking, not to mention space consuming.

If you are curious to see what it looks like with my dataset go to https://misd-vm-12.isi.edu/ermrest-ui/app.html#/retrieve and click on any patient to get the full-blown detail view. You can clearly see how numerous longitudinal tables in my data (e.g., adverse event logs, vitals, biospecimen inventory, blood chemistry) would benefit from a more compact tabular view.

...snip...

I couldn’t agree more that this would be a great first task. It will add significant value to the many projects that need this kind of display mode. Ultimately, I would love to see a nice tabular view that had column sizing, reordering and hiding, along with being able to collapse/expand the entire table vertically to consolidate space while scrolling through the page. Of course, I would be perfectly happy with a static table to start out with ;-)

**Comment by robes** [comment]
The code should implement the following heuristics. First we define a couple terms used here.

Say there is a table `A` with relationships to tables `B` and `C`.

`A -> B` lets say is a foreign key reference (FKR) from A to B, we can call it an "outbound" reference from the perspective of A

`A <- C` let's say is a FKR from C to A, we can call it an "inbound" reference from the perspective of A

So if the details page is displaying a result for a row of A,
 - show the one related row in `B` as if it were an extension of the columns of `A`
 - show the one to many rows in `C` as a nested table.

If `A` has multiple "inbound" references, not only from `C` but also from `D` and `E` and so on, then show each of those as separate nested tables under the heading of `table name` which would be `C`, `D`, `E` and so on.

**Comment by carlkesselman** [comment]
Should match latest spec that Karl has produced.

**Comment by robes** [comment]
we should revisit the requirements for the table display, but i would consider this high level task done with respect to having "basic" table presentation. clearly there are significant enhancements we need in order to support some of our use cases. so we should revisit and spec that out and make more granular issues for ongoing work.
