### ISSUE TITLE
recordedit: UI clean-up

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#809]
- [x] psuedo-column: 
  - div: round-box instead of square box
  - if disabled, use the same style as regular columns
- [x] vertical line to separate between columns. 
- [x] add table header
  - add "Record Number" as a column name
  - add a record number to each column - left justified 
  - move trash to be right-justified
- [x] column names (first column) and column headers (first row) should use the same style 
- [x] fix the border of right most vertical line
- [x] change "Automatically generated by the server" to "Automatically generated"
- [x] generated columns should have consistent style regardless of types (e.g. pseudo- and date columns should use the same display as other regular columns) 
- [x] immutable pesudo columns should be treated consistently in the editing mode.... show the column values.. don't show the input operation.
- [x] the column comments are drawn behind the subsequent column labels and partially obscured. Should I file the bug separately or is this something to fix in this same PR? See https://synapse-dev.isrd.isi.edu/chaise/recordedit/#1/Zebrafish:Subject for example which is now tracking the recordedit-changes branch
- [x] fix the scroll-bar problem on firefox

**Comment by jrchudy** [comment]
- Example of the tooltip behind a column name div:
![image](https://cloud.githubusercontent.com/assets/2932600/20775100/29bef010-b70e-11e6-978e-6d6be9454d40.png)


- Example of a tooltip being cut off by edge of content area:
![image](https://cloud.githubusercontent.com/assets/2932600/20775121/3bf16e20-b70e-11e6-80ec-01288b007a56.png)
This is happening because the tooltip is adding to the scrollable buffer and actually extends the scrollable content area.

- After scrolling the content area:
![image](https://cloud.githubusercontent.com/assets/2932600/20775165/798a3884-b70e-11e6-818d-d26fa0e33303.png)
