### ISSUE TITLE
Opening new tab should show alert

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#836]
When the user clicks an action that expects to open a new tab and that action fails because of a popup blocker, we should *not* redirect the user from the current page.

Ideally the browser will notify the user that a popup was blocked. We can make sure the user is aware that this happened by also showing an alert message on top of the page.

There are currently 2 actions that have this behavior that need to be fixed. The `add related record` button on the related tables in `record` and the `add an entity` button on the recordset directive.

**Comment by hongsudt** [comment]
@howdyjessie @shinyichen who should be working on this? I heard @howdyjessie name in the meeting..

**Comment by howdyjessie** [comment]
It should be noted that if a user has set her browser to simply open links, that would normally open in a new window, in the current tab/window, then the alert will not appear because the browser will have left the current page and loaded the link.

**Comment by howdyjessie** [comment]
In general, as @karlcz has mentioned in a standup last week, it is better UX to offer links that allow the user to open in a new tab/window or current tab and save us from trying to override a user's browser settings. It would mean upending the cookie refresh feature that @shinyichen just built, but since we're moving to `localStorage` soon, I hope we'll also remove links that automatically open in new tabs.

**Comment by hongsudt** [comment]
In the two cases that josh mentioned, we do want new tabs to open for ux
reason. For the search directive, you can't replace the existing tab with
the new recordedit until we can remember the page content and repopulate it
when the users get back to that page. For the add an entry to a related
table, since the main record page could take quite a bit to load (a page
with 20 related tables), if I have to go through the sequence of add an
entry, then click back to get to the record page to add the next entry,
that will just be too painful and annoying.

**Comment by howdyjessie** [comment]
@hongsudt Those are certainly valid reasons to want a user to open a link in a new window, but my point is that **we should not assume these reasons are the best UX** and then make the decision for the user by removing other choices. We can hope they'll click it in a new tab but we shouldn't do it automatically for them.

> For the search directive, you can't replace the existing tab with
the new recordedit until we can remember the page content and repopulate it
when the users get back to that page. For the add an entry to a related
table, since the main record page could take quite a bit to load ...

You are describing limitations of our current implementations. What I'm hearing is:
1. "We can't rebuild a previous state of our app": But our pending transition to `localStorage` would help us remember the page and repopulate it when users get back to it.
2. "The performance of our apps is slow so let's not allow the user to reload it": We all agree a problem like this should be resolved by attempting to improve performance. Beyond that, however, if a page takes long to load; if a page contains information that the user needs to refer back to while being diverted to a different task; then the user would recognize that they need to open a link in a new tab and then we should let them do that. If a user sees a Record page takes a while to load, will she not recognize this and adjust her browsing behavior accordingly by opening a link in a new tab?

I'm not advocating an urgent, immediate conversion of all our links to links that do not automatically open in a new tab at this very moment. Constrained by competing priorities, time, and limited man hours, that would be impractical. What I am saying is that *our current UX could be further improved* by considering a default link behavior that doesn't make assumptions that we know better than the user on how she wants to navigate the pages in her browser.

**Comment by howdyjessie** [comment]
AFAIK there's not a way to tell Selenium to prevent a link from opening in a new tab in E2E tests.

I'm not sure what's the best way to test this manually. Is there a Chrome or FF extension that can prevent a link from opening in a new tab or window?

**Comment by howdyjessie** [comment]
So since there doesn't seem to be a setting in Chrome or Firefox that would prevent links from opening in a new tabs/windows _and_ in the current tab/window (i.e. do nothing), it seems like this is wasn't really an issue to begin with. As such, I'm closing this issue for now; we can always come back to this if it becomes an issue later.
