### ISSUE TITLE
support auto-increment sequence number

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#840]
These sequences could be: 
1. singular sequence: which can be:
  1.1 traditional integer serial number e.g. 1, 2, 3, etc.
  1.2. alphabetical sequence e.g. a, b, c, etc.
2. a composite sequence number consisting of a number of singular sequences e.g. A1, A2, etc. can be used to represent 2D table. There needs to be a rule that specifies how these number get incremented. For example in a 2D 10x10 grid, number 11 will be represented as B1. 

@karlcz @robes We probably need an annotation for this.. I don't think defining this as a column type will work. Here is my attempt

tag:isrd.isi.edu,2016:sequence
* {... "sequence": [..., sub-sequence, ...}: an array of subsequence, where each subsequence is an object consists of 
  - "type" : which is either "integer" or "alphabet"
  - "min": the beginning of the sequence. If omit, the min is 0 or A.
  - "max": the end of the sequence. If omit, the max is max-positive number or ZZZZZZ.
* {... "separator": character ...}: The character to use as the separator between subsequence elements (e.g. '-' will generate A-1)
* null or {} : default to an integer sequence.

**Comment by karlcz** [comment]
I think that you should separate out several concepts here into more basic primitives:
1. An annotation for client-generated value sequences to populate a column
    - Always on an ordered column type.
    - Can handle basic "starting value" or default scenarios: 0, 1, "now", null
    - Optionally set an upper limit or other range restriction?
    - Might extend with other "successor" function choices in future? Step size, time granularity, arbitrary function we can run in JS.
2. An annotation for chaining several sequenced columns as "digits" in a modular composite key scenario
    - Handles your chip array or similar: column "C" ranges `1` to `12`, column "R" ranges `A` to `I`, column "P" starts at `1` and has no upper limit.
3. Column types for introducing different symbol sets
    - integer
    - timestamp
    - date
    - define new one for excel-like alpha sequence `A` .. `Z`, `AA` ... `AZ`, etc.
4. Use server-side trigger to compose accession IDs or similar out of these component fields. If necessary revisit this later as a client-side mechanism using mustache templates or similar?

This would allow the model-driven UI elements to provide input controls for the constituent symbol sets, only needing new controls for new types like excel-type labels instead of decimal integers. The annotation would let the DBA say how the input control gets a default value (for new otherwise blank forms).

You don't want to be in a situation where you have to parse out some accession ID to reconstitute the component fields when getting user input, editing an existing record, or cloning a record. So, we want each of the components to remain stored as separate columns with clear serialization/deserialization rules based on the column type.

**Comment by karlcz** [comment]
OK, based on discussions I am thinking of something more like this:

1. add a new text domain type like "alphasequence" or something if you need funky `A`... `Z` `AA` sequences
2. tag:isrd.isi.edu,2016:client-generated to indicate that a column has some client-side protocol to follow
    - apply to column to say how to populate one column
    - options to specify how to populate the value, e.g. default, successor, boundaries
    - option to "overflow" a successor sequence into another column which should also have this same annotation to configure its own client-generation instructions

The generating options should include sequential as well as random, time-based, or predefined call-outs to get values from "minting" services or similar.

Does this make sense?

**Comment by karlcz** [comment]
@hongsudt @robes  is this still relevant?  it seems to me that we've moved on with different approaches and are unlikely to want to come back to this.

**Comment by robes** [comment]
Right. Seems like the back end approaches are working out. I don't think this is a priority anymore.
