### ISSUE TITLE
add row number to the recordset directive

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#877]
@carlkesselman suggested that there should be a row number in the tabular presentation.

Here is a nice article suggested by @carlkesselman 
http://uxmovement.com/content/9-design-techniques-for-user-friendly-tables/

**Comment by robes** [comment]
should we just show the serial pk then? that seems like the most consistent numerical id. i can't think of a way to generate a row number otherwise.

**Comment by karlcz** [comment]
I assume this is row number within the displayed page (always 1-N regardless of sort order applied)

**Comment by karlcz** [comment]
ugg that article shows the row numbers being sortable and inverted w/ a reverse sort.  not going to happen...

**Comment by karlcz** [comment]
if this is anything more than rows 1-N on the page, to help you figure out how far you scrolled (kind of like the zebra stripes), I think it's misguided.

**Comment by hongsudt** [comment]
I think we just need the simple rows 1-N on the page, and we can leave the column header blank or print the number outside the table boundary.

**Comment by robes** [comment]
@karlcz right, hence why I can't see a way to do this by just sticking row numbers in the directive.

**Comment by robes** [comment]
@hongsudt I don't think we should be doing that.

What happens when you sort? what happens when you page? etc. This doesn't work unless its the serial number.

**Comment by karlcz** [comment]
On Dec 16, robes modulated:
> @hongsudt I don't think we should be doing that.
> 
> What happens when you sort? what happens when you page? etc. This
> doesn't work unless its the serial number.
> 

I think you're arguing for a different "this" than Hongsuda.  Ignore
the article as we certainly won't implement "that".

We can provide row number in the page 1-N always ascending order as
part of the directive.  It will always have row 1 at top of page and
row N at bottom of page.  Sorting and paging will change the content
appearing in those numbered slots.

If someone wants record identifiers, clearly that is a job for the DBA
who modeled the domain and does not require any new Chaise feature.

**Comment by robes** [comment]
@carlkesselman I think row numbers in the directive will be confusing because they are not record numbers. E.g., When you page to the next set of results you will see 1-N row numbers (no matter if you are on the first or the Nth page of results). I like the article you shared. But I think the way to interpret it in our case is for the data modeler (DBA) to have record identifiers that could serve this purpose, which take the form of the accession number in most cases. That's my thought.

**Comment by karlcz** [comment]
I agree.  And to be clear, record IDs may be sparse or discontinuous due to filtering, row-level authz, and sort by other properties.

Also, we do not have any notion of a numeric/ordinal stream position for the current page of results. We can never feasibly state that you are viewing "Record X ... X+k" for pagesize k.  At best, we could repeat some info from the first row being displayed to say we are showing k records starting at value V0 in the sort order.

**Comment by hongsudt** [comment]
I am closing this issue and tag it with `won't fix`..
