### ISSUE TITLE
Boolean drop-down occluded by next field in recordedit

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#921]
See:

https://synapse-dev.isrd.isi.edu/chaise/recordedit/#1/Zebrafish:Image/ID=ImgZfZdu20160908A6

The "Good?" column is boolean and has a drop-down.  When I try to choose a value, the null (empty) choice and the very top of the "true" text is visible but the remainder of the "true" text and the "false" text is truncated and hidden by the next field for the column "Notes".

Edit: updated demonstration page URL to one that still works

**Comment by jrchudy** [comment]
The corresponding PR has been merged. @karlcz could you verify this after the hourly update at 2 pm today?

**Comment by karlcz** [comment]
It's still buggy on the page given in the issue description on firefox.  When opening the drop-down, the table display area does not get larger.  Instead, a vertical scroll pops up and the drop-down contents are still occluded.

**Comment by jrchudy** [comment]
That was the fix that we discussed without completely replacing the dropdown. Now the user can access the rest of the values in the dropdown if they scroll the table section down.

We can leave this open and rename it to track when we want to do work to change the dropdown menu implementation and see if that fixes the problem.

**Comment by hongsudt** [comment]
@jrchudy @chiragsanghvi  can you document the alternative solutions to solve this problem? Since Karl will deal with this issue using a work-around, we can come back and work on this later. I just want to have the potential solutions documented.

**Comment by jrchudy** [comment]
We discussed a number of a ways to change the behavior of this dropdown:
- the viewport for the table get resized (height-wise) when the dropdown is clicked on
- the dropdown menu can look for the bottom of the viewport instead of the bottom of the browser to determine if it should be drawn upwards
- the dropdown implementation can be replaced with one that includes the dropdown content outside of the parent div

**Comment by chiragsanghvi** [comment]
You can use `append-to-body` attribute on the `ui-select` element. This will basically append the dropdown to the body, instead of the table. This should fix the issue.


I've a proof of concept in my userdir. Just zoom out the screen to 50% and then try opening the dropdown.

https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#18709/product:accommodation

**Comment by hongsudt** [comment]
The link works pretty well.. 
@jrchudy please take a look. If this is a quick fix, let's get it out of the way.

**Comment by jrchudy** [comment]
The changes that @chiragsanghvi suggested have been made. This can be reviewed after the next dev hourly update at 3 pm today.

**Comment by karlcz** [comment]
the drop-down looks good now, but the example page in the issue description now shows a horizontal scrollbar even with very wide windows.  is this related to the change in CSS, or a separate issue I should open?

**Comment by jrchudy** [comment]
It does look like the change to the CSS in PR #993 caused this.

**Comment by karlcz** [comment]
OK this looks good to me now.
