### ISSUE TITLE
Don't show 'add' link on nested table when it is 'generated'

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#946]
If a table is annotated with the 'generated' annotation, then the 'add' link should not be shown when that table is nested in another record page.

For example, this is a record for a Slide that has a Scan.

https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Slide/ID=20160915-Gdf15het48hGA22-GA-0-01-000

The scan table has an "Add" link which can only lead to an error if you click it.

I would think this should be a simple as the 'record' app checking the 'canCreate' property of the nested entities Reference object to decide whether to determine whether to show that link or not.

**Comment by robes** [comment]
Also... make sure the separator `|` is not shown when the `Add` is not shown. Was just looking at this record and saw the "Add" is gone (yay) but the `|` is still there (boo).

https://dev.facebase.org/data/record/#1/legacy:dataset/id=263

Makes me wonder if this is being worked on in another issue since this one isn't even assigned.

**Comment by hongsudt** [comment]
Shouldn't canEdit or canCreate deal with the generated annotation already?

Maybe the app hasn't checked canCreate before adding the "Add" link..

**Comment by howdyjessie** [comment]
Not sure if these issues were already fixed in another issue since the time this issue was created. I see the Add link does have a check that whether a related reference's `canCreate` property is true to determine whether to show this link. The pipe also doesn't appear for me on neither the facebase-dev nor the cirm-dev pages anymore. @robes Do you still see these issues on your end?

**Comment by robes** [comment]
I believe this has been resolved.
