### ISSUE TITLE
app fails at/near startup on MS IE

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#957]
Environment:
- Windows 7
- IE 11.0

Steps:
1. go to dev.facebase.org
2. go to any search app link
3. drill down to any record app link

What you see is an Error dialog and in it is says the object does not have `startsWith`. That may be a bug in itself but it is probably not the initial bug. If you watch the app load in IE developer tools the first bug is this:

```
Unable to get property 'length' of undefined or null reference.
File: record.controller.js, Line: 180, Column: 33
```

We are dereferencing a property of the `$rootScope` _without_ first validating that the property exists. But since we assume the property exists we should probably start by figuring out why the assumption didn't hold.

**Comment by jrchudy** [comment]
The first error is not a blocking error but instead telling you that calling `length` on the given property is undefined or null, in this case `Object.keys(completed)` where `completed = {}`. `Object.keys()` should return an empty object if it has no keys, but in either case it would fail that side of the `||` statement. 

The `startsWith` bug is the real problem here. `String.startsWith()` and `String.endsWith()` are not available in IE so we need a polyfill for it. Chaise already has a polyfill for this which means the error is actually coming from ermrestJS. ErmrestJS does not have these polyfills defined. Adding the polyfills fixes this problem.

**Comment by robes** [comment]
tested on cirm-dev and it works
