### ISSUE TITLE
auto-focus search box when search modal is open

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#971]
Currently, this feature works on chrome, but doesn't work on firefox. Please test this on safari as well..

**Comment by howdyjessie** [comment]
Rather than relying on the `autofocus` attribute to do the focusing for us, we should focus on the input via JS instead because:

1. The reason it doesn't work in FF is because FF's implementation of `autofocus` doesn't focus the input box if the autofocus attribute is inserted after the page has loaded (e.g. via AJAX). Chrome and Safari do this fine.

2. Additionally, `autofocus` is only supported on IE10+.

3. `autofocus` will only focus the desired input the first time it's loaded. Loading the desired input a second time, like re-opening a modal in a search popup modal, will lose the autofocus.

The solution is to manually focus on the desired element every time the modal opened, something like `angular.element(searchBox).focus()`...

**Comment by howdyjessie** [comment]
PR #988 has been merged... closing now.
