### ISSUE TITLE
Numbers in nested table header without explanation are confusing

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#980]
Our nested tables have the headings

> Table Display Name (#)

Without explaining what # is for is confusing.

Some suggestions for improving it:
- "showing # of total# results"
- "showing first # results"
- or just drop the number

**Comment by hongsudt** [comment]
I prefer "showing first # results"..

**Comment by nitishksahu** [comment]
The PR has been merged with the master branch. Assigned to @robes to test the changes

**Comment by robes** [comment]
I think the UX is still not quite right.

1. if there are 0 results
    - "Heading (No results)"
1. if less than LIMIT records
    - "Heading (Showing all results)"
2. if there exists more than LIMIT records
    - "Heading (Showing first LIMIT records)"
    - do not use a "+" in the message like "Showing first 25+ records". 

@karlcz @hongsudt @ljpearlman @mikedarcy any opinions...? You can see an example here.
https://dev.facebase.org/data/record/#1/isa:dataset/id=14102

**Comment by hongsudt** [comment]
For the second case, instead of "Heading (Showing all results)", what about
""Heading (Showing all LIMIT records)"

Then we should change the first case from "(No results)" to "(No records)"
for consistency.

**Comment by karlcz** [comment]
I agree "results" or "records" should be used consistently but the more appropriate word might depend on whether there are search or other filtering criteria?

If we want to have an indicator in the heading for the first case I'd use `(No results available)` and we should make sure this is consistent with what we put into the empty table's body as well.

**Comment by robes** [comment]
@karlcz Woops. Sorry I meant to use "results" consistently. I'm okay with "records" or "results" but using them consistently was the intention.

@hongsudt the problem with your suggestion for the second case is that there are **less than LIMIT** records/results being displayed. Did you mean to say "Showing all NUMBER records" where NUMBER is the actual number (NUMBER < LIMIT) returned? In that case, I can see your point and I was considering that too.

**Comment by hongsudt** [comment]
Yes. I meant the actual number..

**Comment by robes** [comment]
OK. That message would make sense to me too.

**Comment by nitishksahu** [comment]
As per my conversation with @hongsudt, here is the implementation plan:

**1st Case:** (When all the results are displayed)
- "**Showing** first 15 results" to "**showing** first 15 results" (sentence case was somehow looking more prominent so we decided to have all verbose in small case) 

**2nd Case:** (When no results are displayed)
- "**no results**" to "**no results found**" so that this is consistent with what was shown in the empty table body.

Preview: 
![screen shot 2017-06-09 at 5 40 30 pm](https://user-images.githubusercontent.com/7412235/26998592-d525a698-4d3a-11e7-9ff2-9df2e41251f3.png)


@robes @karlcz @ljpearlman any suggestions?

**Comment by robes** [comment]
good plan
