### ISSUE TITLE
Can't increase page size after paging back to the first page

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#999]
This is honestly a little tricky and probably not the highest priority bug if its hard. Although it might also reveal something wrong with how we are handling the interaction between pagination and page size.

Steps:
1. If you go to a recordset app and click 'next' arrow
2. then click 'previous' arrow
3. Now try to increase the page size

It won't increase because the page is bounded by the `@before(...)` condition.

What its doing might be technically correct, but I think I would consider this a UX bug. This is probably not a high priority (IMO) relative to other issues.

**Comment by karlcz** [comment]
We could probably use a simple heuristic in Chaise.

If the result of the "before" request is less than requested page size
N, we must have reached the beginning of the stream.  So we could drop
the "before" modifier and just try again to get the first N records,
just like when the app first starts up on the initial page.

Can confine this change to the prev-page handler, to just extend the
promise chain when the retrieved page is undersized?  We'd need to
make sure the app determines its new page reference from the result of
this chain, rather than assuming the reference remains the same as
what was initially requested.

**Comment by jrchudy** [comment]
Assigning back to @robes to verify that the issue has been fixed.

**Comment by robes** [comment]
it seems right
